# ERCOT Data Cleaning

Converts raw monthly CSVs into analysis-ready parquet files.

**Scope (data cleaning):** type coercion, timestamp construction, DST resolution, deduplication, null reporting.  
**Not here (preprocessing):** feature engineering, normalization, log-returns, train/test splits — those belong in a separate notebook.

All datasets loaded from **2017-07-01** onward (aligned with postDateTime availability).

| Dataset | Content | Granularity | Coverage (loaded) |
|---|---|---|---|
| NP6-346-CD | Actual load — 4 pricing zones | Hourly | 2017-07 → 2025-12 |
| NP6-345-CD | Actual load — 8 weather zones | Hourly | 2017-07 → 2025-12 |
| NP3-565-CD | Load forecast — 8 weather zones (InUseFlag=Y) | Hourly | 2017-07 → 2025-12 |
| NP6-905-CD | RTM prices — 4 hubs (15-min → hourly) | 15-min | 2017-07 → 2025-12 |
| NP4-732-CD | Wind actual + forecast — system + 3 LZ zones | Hourly | 2017-07 → 2025-12 |
| NP4-190-CD | DAM settlement prices — 4 hubs | Hourly | 2017-07 → 2025-12 |
| NP4-523-CD | System Lambda (marginal energy cost) | Hourly | 2017-07 → 2025-12 |
| NP4-188-CD | Ancillary service prices (MCPC) | Hourly | 2017-07 → 2025-12 |
| NP3-233-CD | Hourly resource outage capacity (total + IRR) | Hourly | 2017-07 → 2025-12 |

## 1. Setup

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

print('pandas:', pd.__version__)
print('numpy: ', np.__version__)

RAW_ROOT          = Path('data/raw/ercot')
PROCESSED_ROOT    = Path('data/processed/ercot')
PROCESSED_ROOT.mkdir(parents=True, exist_ok=True)

WEATHER_ROOT      = Path('data/sample/weather')   # switch to data/raw/weather for full history (must be downloaded first; see DATA_DOWNLOAD.md)
WEATHER_PROCESSED = Path('data/processed/weather')
WEATHER_PROCESSED.mkdir(parents=True, exist_ok=True)

pandas: 3.0.1
numpy:  2.4.2

In [2]:
# Validate data directories
import sys
_required = [
    Path('data/raw/ercot'),
    Path('data/sample/weather'),
]
_missing = [p for p in _required if not p.exists()]
if _missing:
    print("WARNING: Missing expected directories:")
    for p in _missing:
        print(f"  {p.resolve()}")
    print("\nMake sure you are running this notebook from the project root.")
else:
    print("Data directories OK.")

Data directories OK.

The helpers below handle CSV ingestion and timestamp parsing across all datasets. `read_monthly_csvs` concatenates per-month files; `parse_ts_cst` converts ERCOT's local HourEnding + DSTFlag into a fixed UTC-6 timestamp (`ts_utc`) used as the join key throughout this notebook.

In [3]:
# ── Helper functions ─────────────────────────────────────────────────────────

def read_monthly_csvs(dataset_id: str, usecols=None,
                      from_year: int = None, from_month: int = None,
                      to_year: int = None, to_month: int = None,
                      chunksize: int = 200_000) -> pd.DataFrame:
    """Load all monthly CSVs for a dataset, optionally restricted to a year-month range."""
    files = sorted((RAW_ROOT / dataset_id).glob('*/*/*.csv'))
    files = [f for f in files if not f.name.endswith('.docids')]
    if from_year is not None:
        lo = (from_year, from_month or 1)
        files = [f for f in files
                 if (int(f.parent.parent.name), int(f.parent.name)) >= lo]
    if to_year is not None:
        hi = (to_year, to_month or 12)
        files = [f for f in files
                 if (int(f.parent.parent.name), int(f.parent.name)) <= hi]
    if not files:
        raise FileNotFoundError(f'No CSV files found for {dataset_id}')
    chunks = []
    for f in files:
        for chunk in pd.read_csv(f, usecols=usecols, low_memory=False, chunksize=chunksize):
            chunks.append(chunk)
    return pd.concat(chunks, ignore_index=True)


def parse_hour_ending(series: pd.Series) -> pd.Series:
    """Parse HourEnding values like '1', '24', '01:00', '24:00' -> int 1..24."""
    return pd.to_numeric(
        series.astype(str).str.strip().str.split(':').str[0],
        errors='coerce'
    )


def parse_ts_cst(date_col: pd.Series, hour_ending_col: pd.Series,
                 dst_flag_col: pd.Series) -> pd.Series:
    """
    Build a naive local (America/Chicago) timestamp from ERCOT DeliveryDate + HourEnding + DSTFlag.

    ERCOT uses HourEnding convention: HE=N covers local hour N-1 to N.
    DSTFlag disambiguates the repeated hour on fall-back days:
      N = first occurrence (CDT, UTC-5)
      Y = repeated occurrence (CST, UTC-6)

    Strategy: build the naive local timestamp, then use tz_localize with
    America/Chicago so pandas applies the exact DST transition instants for
    each year — no manual month/day approximation needed.

    ambiguous array: True=CDT (DSTFlag=N), False=CST (DSTFlag=Y).
    For non-ambiguous hours pandas ignores the array value and uses the
    timezone rules directly.

    nonexistent='NaT': the spring-forward gap (HE=03 on spring-forward day)
    is absent from ERCOT data, so NaT is the correct sentinel if it appears.
    """
    he = parse_hour_ending(hour_ending_col)
    local_ts = (
        pd.to_datetime(date_col, format='%m/%d/%Y', errors='coerce')
        + pd.to_timedelta(he - 1, unit='h')
    )
    is_cdt = (dst_flag_col.str.upper() != 'Y').values   # True=CDT, False=CST
    ct = local_ts.dt.tz_localize('America/Chicago', ambiguous=is_cdt, nonexistent='NaT')
    return ct.dt.tz_convert('UTC').dt.tz_localize(None) - pd.Timedelta(hours=6)  # fixed UTC-6


def null_report(df: pd.DataFrame, label: str) -> None:
    null_rate = df.isna().mean()
    nulls = null_rate[null_rate > 0]
    print(f'\n{label}: {len(df):,} rows')
    if nulls.empty:
        print('  no nulls')
    else:
        for col, rate in nulls.items():
            print(f'  {col}: {rate:.2%} null')


def dataset_summary(df: pd.DataFrame, label: str) -> None:
    """
    Print row count, time range, column names + dtypes, null rates,
    numeric describe (with tail percentiles), categorical value counts, and head.
    """
    ts_col = 'ts_utc' if 'ts_utc' in df.columns else None
    print(f'\n{"─"*60}')
    print(f'{label}')
    print(f'  {len(df):,} rows  ×  {len(df.columns)} cols')
    if ts_col:
        print(f'  range : {df[ts_col].min()}  →  {df[ts_col].max()}')

    # Column names and dtypes
    print(f'\n  columns:')
    for col in df.columns:
        print(f'    {col:<35} {str(df[col].dtype)}')

    # Nulls
    null_rate = df.isna().mean()
    nulls = null_rate[null_rate > 0]
    print(f'\n  nulls : {"none" if nulls.empty else ""}')
    for col, rate in nulls.items():
        print(f'    {col}: {rate:.2%}')

    # Numeric describe
    num = df.select_dtypes(include='number')
    if not num.empty:
        display(num.describe(percentiles=[.05, .25, .5, .75, .95]).round(3))

    # Categorical value counts
    for col in df.select_dtypes(include='object').columns:
        print(f'\n  {col}  ({df[col].nunique()} unique):')
        display(df[col].value_counts().rename('count').to_frame())

    # Head
    print(f'\n  head:')
    display(df.head())

### DST reference

ERCOT publishes hourly data in **local time (CST/CDT)** with a `DSTFlag` column.  
Texas observes CDT (UTC−5) mid-March through early November, CST (UTC−6) otherwise.

**Spring-forward** (e.g. Mar 12): `HourEnding=03:00` is absent — clocks jump 2→3 am. That day has 23 rows per series, not 24. No flag needed.

**Fall-back** (e.g. Nov 5): `HourEnding=02:00` appears **twice** — that day has 25 rows.  
- `DSTFlag=N` → first occurrence, CDT (UTC−5)  
- `DSTFlag=Y` → second occurrence, CST (UTC−6)

Example from NP4-190-CD, Nov 5 2017, HB_NORTH:
```
HE=02:00  price= 9.46  DSTFlag=N   ← CDT hour (UTC-5)
HE=02:00  price=12.84  DSTFlag=Y   ← CST hour (UTC-6), after clock falls back
```

All cleaning below converts delivery timestamps to **fixed UTC-6 (CST)** via `parse_ts_cst()` to produce a unique, monotonic time index. Summer CDT hours shift 1h earlier under the fixed offset.

## 2. Dataset Inventory

In [4]:
rows = []
for ds_dir in sorted(RAW_ROOT.iterdir()):
    if not ds_dir.is_dir():
        continue
    csvs = sorted([f for f in ds_dir.rglob('*.csv') if not f.name.endswith('.docids')])
    if not csvs:
        continue
    earliest = f"{csvs[0].parent.parent.name}-{csvs[0].parent.name}"
    latest   = f"{csvs[-1].parent.parent.name}-{csvs[-1].parent.name}"
    rows.append({'dataset': ds_dir.name, 'months': len(csvs),
                 'earliest': earliest, 'latest': latest})

inv = pd.DataFrame(rows)
display(inv)

      dataset  months earliest   latest
0  NP3-233-CD     104  2017-07  2026-02
1  NP3-565-CD     104  2017-07  2026-02
2  NP4-188-CD     104  2017-07  2026-02
3  NP4-190-CD     142  2014-05  2026-02
4  NP4-523-CD     104  2017-07  2026-02
5  NP4-732-CD     104  2017-07  2026-02
6  NP6-345-CD     142  2014-05  2026-02
7  NP6-346-CD     104  2017-07  2026-02
8  NP6-905-CD     104  2017-07  2026-02

## 2.1 DST Timestamp Verification

Before loading any dataset, verify that `parse_ts_cst()` correctly handles both DST transitions using actual raw CSV rows.

**Reference dates (2019, a clean year):**
- **Spring-forward Mar 10 2019**: clocks jump 2→3 AM (CST→CDT). `HE=3` is absent from ERCOT files. `parse_ts_cst` returns `NaT` for any `HE=3` row (`nonexistent='NaT'`).
- **Fall-back Nov 3 2019**: clocks repeat 1→2 AM (CDT→CST). `HE=2` appears twice.  
  - `DSTFlag=N` → first occurrence (CDT = UTC−5) → expected `ts_cst = 00:00` (midnight, UTC−6 of 06:00 UTC)  
  - `DSTFlag=Y` → second occurrence (CST = UTC−6) → expected `ts_cst = 01:00` (1 AM CST, UTC−6 of 07:00 UTC)

**NP3-233-CD** has no `DSTFlag` — both the nonexistent spring hour and the ambiguous fall hour map to `NaT` (correct sentinel behaviour).

In [5]:
# ── DST raw-data snapshot: verify parse_ts_cst before loading any dataset ─────

_RAW = Path('data/raw/ercot')
_SP  = '03/10/2019'   # spring-forward (MM/DD/YYYY — ERCOT date format)
_FB  = '11/03/2019'   # fall-back


def _dst_detail(paths, date_col, he_col, dst_col, val_col, label,
                di_col=None, post_col='postDateTime',
                filter_col=None, filter_val=None):
    if isinstance(paths, Path):
        paths = [paths]

    want = list(dict.fromkeys(
        c for c in [post_col, date_col, he_col, di_col, dst_col, val_col, filter_col]
        if c is not None
    ))

    chunks = []
    for p in paths:
        try:
            hdr  = pd.read_csv(p, nrows=0).columns.tolist()
            load = [c for c in want if c in hdr]
            chunks.append(pd.read_csv(p, usecols=load, low_memory=False))
        except Exception as e:
            print(f'  [WARN] {Path(p).name}: {e}')
    if not chunks:
        return

    df = pd.concat(chunks, ignore_index=True)
    if filter_col and filter_col in df.columns:
        df = df[df[filter_col] == filter_val]

    df['_dd'] = pd.to_datetime(
        df[date_col].astype(str), format='%m/%d/%Y', errors='coerce'
    ).dt.strftime('%m/%d/%Y')
    he_int = pd.to_numeric(
        df[he_col].astype(str).str.split(':').str[0], errors='coerce'
    )

    print(f'\n{"━"*72}')
    print(f'  {label}')

    for day_str, title, he_show in [
        (_SP, f'Spring-forward {_SP}  →  HE=3 nonexistent (expect NaT)', [1, 2, 3, 4, 5]),
        (_FB, f'Fall-back     {_FB}  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6', [1, 2, 3]),
    ]:
        rows = df[(df['_dd'] == day_str) & he_int.isin(he_show)].copy()
        if rows.empty:
            print(f'\n  {title}\n    — no rows found for this date')
            continue

        sort_k = [c for c in [he_col, di_col, dst_col] if c and c in rows.columns]
        rows = rows.sort_values(sort_k)

        dedup_k = [c for c in [date_col, he_col, di_col, dst_col]
                   if c and c in rows.columns]
        rows = rows.drop_duplicates(subset=dedup_k)

        he_n = pd.to_numeric(
            rows[he_col].astype(str).str.split(':').str[0], errors='coerce'
        )
        local = (
            pd.to_datetime(rows[date_col], format='%m/%d/%Y', errors='coerce')
            + pd.to_timedelta(he_n - 1, unit='h')
        )
        if di_col and di_col in rows.columns:
            di_n = pd.to_numeric(rows[di_col], errors='coerce')
            local = local + pd.to_timedelta((di_n - 1) * 15, unit='min')

        if dst_col and dst_col in rows.columns:
            is_cdt = (rows[dst_col].astype(str).str.upper() != 'Y').values
            ct = local.dt.tz_localize('America/Chicago',
                                      ambiguous=is_cdt, nonexistent='NaT')
            rows['ts_utc'] = (ct.dt.tz_convert('UTC').dt.tz_localize(None) - pd.Timedelta(hours=6)).values
        else:
            # No DSTFlag: fixed UTC-6 offset, no tz_localize, no NaT.
            rows['ts_utc'] = local.values  # UTC-6 = local CST (no DSTFlag; no adjustment)

        show = [c for c in [post_col, date_col, he_col, di_col, dst_col, val_col, 'ts_utc']
                if c and c in rows.columns]
        print(f'\n  {title}')
        display(rows[show].reset_index(drop=True))


def _paths(ds, months=(('2019', '03'), ('2019', '11'))):
    return [_RAW / ds / y / m / f'{ds}_{y}{m}.csv' for y, m in months]


# ── 1. NP6-346-CD — Actual load ──────────────────────────────────────────────────────
_dst_detail(_paths('NP6-346-CD'),
            'OperDay', 'HourEnding', 'DSTFlag', 'TOTAL',
            'NP6-346-CD — Actual load, TOTAL MW')

# ── 2. NP6-345-CD — Actual load 8 weather zones ──────────────────────────────────────────
_dst_detail(_paths('NP6-345-CD'),
            'OperDay', 'HourEnding', 'DSTFlag', 'TOTAL',
            'NP6-345-CD — Actual load 8 WZ, TOTAL MW')

# ── 3. NP3-565-CD — Load forecast (InUseFlag=Y) ───────────────────────────────────────────
_dst_detail(_paths('NP3-565-CD'),
            'DeliveryDate', 'HourEnding', 'DSTFlag', 'SystemTotal',
            'NP3-565-CD — Load forecast, SystemTotal MW  (InUseFlag=Y)',
            filter_col='InUseFlag', filter_val='Y')

# ── 4. NP6-905-CD — RTM 15-min (HB_NORTH) ───────────────────────────────────────────────────────────────────────────
_dst_detail(_paths('NP6-905-CD'),
            'DeliveryDate', 'DeliveryHour', 'DSTFlag', 'SettlementPointPrice',
            'NP6-905-CD — RTM 15-min HB_NORTH ($/MWh)  [spring: HE=3 absent; fall: HE=2 ×5]',
            di_col='DeliveryInterval',
            filter_col='SettlementPointName', filter_val='HB_NORTH')

# ── 5. NP4-732-CD — Wind ─────────────────────────────────────────────────────────────────────────────────────────
_dst_detail(_paths('NP4-732-CD'),
            'DELIVERY_DATE', 'HOUR_ENDING', 'DSTFlag', 'SYSTEM_WIDE_GEN',
            'NP4-732-CD — Wind, SYSTEM_WIDE_GEN MW')

# ── 6. NP4-190-CD — DAM (HB_NORTH) ─────────────────────────────────────────────────────────────────────────────
_dst_detail(_paths('NP4-190-CD'),
            'DeliveryDate', 'HourEnding', 'DSTFlag', 'SettlementPointPrice',
            'NP4-190-CD — DAM HB_NORTH ($/MWh)',
            filter_col='SettlementPoint', filter_val='HB_NORTH')

# ── 7. NP4-523-CD — System Lambda ──────────────────────────────────────────────────────────────────────────
_dst_detail(_paths('NP4-523-CD'),
            'DeliveryDate', 'HourEnding', 'DSTFlag', 'SystemLambda',
            'NP4-523-CD — System Lambda ($/MWh)')

# ── 8. NP4-188-CD — Ancillary MCPC (RRS) ────────────────────────────────────────────────────────────────
_dst_detail(_paths('NP4-188-CD'),
            'DeliveryDate', 'HourEnding', 'DSTFlag', 'MCPC',
            'NP4-188-CD — MCPC RRS ($/MWh)  [postDateTime sorting inverted in file — see §3]',
            filter_col='AncillaryType', filter_val='RRS')

# ── 9. NP3-233-CD — Generation (no DSTFlag) ──────────────────────────────────────────────────────────
# No DSTFlag: fixed UTC-6 offset (+ 6h), no tz_localize, no NaT.
# Spring-forward: HE=1-5 -> 06:00-10:00 UTC. Fall-back: HE=1-3 -> 06:00-08:00 UTC.
_dst_detail(_paths('NP3-233-CD'),
            'Date', 'HourEnding', None, 'TotalResourceMW',
            'NP3-233-CD — Generation, TotalResourceMW  (no DSTFlag → fixed UTC-6, no NaT)')

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP6-346-CD — Actual load, TOTAL MW

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,OperDay,HourEnding,DSTFlag,TOTAL,ts_utc
0,2019-03-11T05:50:00.000,03/10/2019,01:00,N,31469.75,2019-03-10 00:00:00
1,2019-03-11T05:50:00.000,03/10/2019,02:00,N,30379.69,2019-03-10 01:00:00
2,2019-03-11T05:50:00.000,03/10/2019,04:00,N,29692.68,2019-03-10 02:00:00
3,2019-03-11T05:50:00.000,03/10/2019,05:00,N,29452.83,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,OperDay,HourEnding,DSTFlag,TOTAL,ts_utc
0,2019-11-04T05:50:00.000,11/03/2019,01:00,N,33467.77,2019-11-02 23:00:00
1,2019-11-04T05:50:00.000,11/03/2019,02:00,N,33174.89,2019-11-03 00:00:00
2,2019-11-04T05:50:00.000,11/03/2019,02:00,Y,33139.78,2019-11-03 01:00:00
3,2019-11-04T05:50:00.000,11/03/2019,03:00,N,33344.88,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP6-345-CD — Actual load 8 WZ, TOTAL MW

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,OperDay,HourEnding,DSTFlag,TOTAL,ts_utc
0,2019-03-11T05:50:00.000,03/10/2019,01:00,N,31469.75,2019-03-10 00:00:00
1,2019-03-11T05:50:00.000,03/10/2019,02:00,N,30379.69,2019-03-10 01:00:00
2,2019-03-11T05:50:00.000,03/10/2019,04:00,N,29692.68,2019-03-10 02:00:00
3,2019-03-11T05:50:00.000,03/10/2019,05:00,N,29452.83,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,OperDay,HourEnding,DSTFlag,TOTAL,ts_utc
0,2019-11-04T05:50:00.000,11/03/2019,01:00,N,33467.77,2019-11-02 23:00:00
1,2019-11-04T05:50:00.000,11/03/2019,02:00,N,33174.89,2019-11-03 00:00:00
2,2019-11-04T05:50:00.000,11/03/2019,02:00,Y,33139.78,2019-11-03 01:00:00
3,2019-11-04T05:50:00.000,11/03/2019,03:00,N,33344.88,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP3-565-CD — Load forecast, SystemTotal MW  (InUseFlag=Y)

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,DeliveryDate,HourEnding,DSTFlag,SystemTotal,ts_utc
0,2019-03-03T00:30:01.694,03/10/2019,1:00,N,32328.6925,2019-03-10 00:00:00
1,2019-03-03T00:30:01.694,03/10/2019,2:00,N,30656.8081,2019-03-10 01:00:00
2,2019-03-03T00:30:01.694,03/10/2019,4:00,N,29465.1031,2019-03-10 02:00:00
3,2019-03-03T00:30:01.694,03/10/2019,5:00,N,29460.5157,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,DeliveryDate,HourEnding,DSTFlag,SystemTotal,ts_utc
0,2019-11-01T00:30:01.939,11/03/2019,1:00,N,35486.2010,2019-11-02 23:00:00
1,2019-11-01T00:30:01.939,11/03/2019,2:00,N,35055.3846,2019-11-03 00:00:00
2,2019-11-01T00:30:01.939,11/03/2019,2:00,Y,35055.3846,2019-11-03 01:00:00
3,2019-11-01T00:30:01.939,11/03/2019,3:00,N,34752.4416,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP6-905-CD — RTM 15-min HB_NORTH ($/MWh)  [spring: HE=3 absent; fall: HE=2 ×5]

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)
    — no rows found for this date

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6
    — no rows found for this date

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP4-732-CD — Wind, SYSTEM_WIDE_GEN MW

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,DELIVERY_DATE,HOUR_ENDING,DSTFlag,ts_utc
0,2019-03-03T01:56:17.623,03/10/2019,1,N,2019-03-10 00:00:00
1,2019-03-03T02:56:21.143,03/10/2019,2,N,2019-03-10 01:00:00
2,2019-03-03T04:56:20.708,03/10/2019,4,N,2019-03-10 02:00:00
3,2019-03-03T05:56:12.982,03/10/2019,5,N,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,DELIVERY_DATE,HOUR_ENDING,DSTFlag,ts_utc
0,2019-11-01T00:56:23.785,11/03/2019,1,N,2019-11-02 23:00:00
1,2019-11-01T00:56:23.785,11/03/2019,2,N,2019-11-03 00:00:00
2,2019-11-01T00:56:23.785,11/03/2019,2,Y,2019-11-03 01:00:00
3,2019-11-01T00:56:23.785,11/03/2019,3,N,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP4-190-CD — DAM HB_NORTH ($/MWh)

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,DeliveryDate,HourEnding,DSTFlag,SettlementPointPrice,ts_utc
0,2019-03-09T13:11:42.000,03/10/2019,01:00,N,25.41,2019-03-10 00:00:00
1,2019-03-09T13:11:42.000,03/10/2019,02:00,N,20.19,2019-03-10 01:00:00
2,2019-03-09T13:11:42.000,03/10/2019,04:00,N,18.65,2019-03-10 02:00:00
3,2019-03-09T13:11:42.000,03/10/2019,05:00,N,19.11,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,DeliveryDate,HourEnding,DSTFlag,SettlementPointPrice,ts_utc
0,2019-11-02T12:32:30.000,11/03/2019,01:00,N,16.57,2019-11-02 23:00:00
1,2019-11-02T12:32:30.000,11/03/2019,02:00,N,15.90,2019-11-03 00:00:00
2,2019-11-02T12:32:30.000,11/03/2019,02:00,Y,15.98,2019-11-03 01:00:00
3,2019-11-02T12:32:30.000,11/03/2019,03:00,N,12.77,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP4-523-CD — System Lambda ($/MWh)

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,DeliveryDate,HourEnding,DSTFlag,SystemLambda,ts_utc
0,2019-03-09T13:11:40.428,03/10/2019,1:00,N,25.4776,2019-03-10 00:00:00
1,2019-03-09T13:11:40.428,03/10/2019,2:00,N,20.2326,2019-03-10 01:00:00
2,2019-03-09T13:11:40.428,03/10/2019,4:00,N,18.6745,2019-03-10 02:00:00
3,2019-03-09T13:11:40.428,03/10/2019,5:00,N,19.1494,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,DeliveryDate,HourEnding,DSTFlag,SystemLambda,ts_utc
0,2019-11-02T12:32:29.115,11/03/2019,1:00,N,16.3487,2019-11-02 23:00:00
1,2019-11-02T12:32:29.115,11/03/2019,2:00,N,15.7318,2019-11-03 00:00:00
2,2019-11-02T12:32:29.115,11/03/2019,2:00,Y,15.8493,2019-11-03 01:00:00
3,2019-11-02T12:32:29.115,11/03/2019,3:00,N,11.5111,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP4-188-CD — MCPC RRS ($/MWh)  [postDateTime sorting inverted in file — see §3]

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,DeliveryDate,HourEnding,DSTFlag,MCPC,ts_utc
0,2019-03-09T13:11:40.000,03/10/2019,01:00,N,8.00,2019-03-10 00:00:00
1,2019-03-09T13:11:40.000,03/10/2019,02:00,N,5.08,2019-03-10 01:00:00
2,2019-03-09T13:11:40.000,03/10/2019,04:00,N,5.01,2019-03-10 02:00:00
3,2019-03-09T13:11:40.000,03/10/2019,05:00,N,5.20,2019-03-10 03:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,DeliveryDate,HourEnding,DSTFlag,MCPC,ts_utc
0,2019-11-02T12:32:28.000,11/03/2019,01:00,N,10.22,2019-11-02 23:00:00
1,2019-11-02T12:32:28.000,11/03/2019,02:00,N,10.15,2019-11-03 00:00:00
2,2019-11-02T12:32:28.000,11/03/2019,02:00,Y,11.19,2019-11-03 01:00:00
3,2019-11-02T12:32:28.000,11/03/2019,03:00,N,10.00,2019-11-03 02:00:00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  NP3-233-CD — Generation, TotalResourceMW  (no DSTFlag → fixed UTC-6, no NaT)

  Spring-forward 03/10/2019  →  HE=3 nonexistent (expect NaT)

,postDateTime,Date,HourEnding,TotalResourceMW,ts_utc
0,2019-03-03T01:01:02.769,03/10/2019,1,22732,2019-03-10 00:00:00
1,2019-03-05T14:00:57.283,03/10/2019,2,22768,2019-03-10 01:00:00
2,2019-03-08T04:00:53.338,03/10/2019,3,23867,2019-03-10 02:00:00
3,2019-03-07T22:00:55.795,03/10/2019,4,23895,2019-03-10 03:00:00
4,2019-03-03T09:00:58.838,03/10/2019,5,23062,2019-03-10 04:00:00

  Fall-back     11/03/2019  →  HE=2 twice: N=CDT/UTC−5, Y=CST/UTC−6

,postDateTime,Date,HourEnding,TotalResourceMW,ts_utc
0,2019-11-01T00:01:05.949,11/03/2019,1,24577,2019-11-03 00:00:00
1,2019-11-01T04:01:13.398,11/03/2019,2,24577,2019-11-03 01:00:00
2,2019-11-01T02:01:09.716,11/03/2019,3,24577,2019-11-03 02:00:00

### 2.2 One-Time Raw CSV Pre-filter

Reduces disk footprint and speeds up all subsequent loads by filtering the
three largest datasets in-place before any analysis is run.  **Run once, then
leave `FILTER_RAW_CSVS = False`.**

| Dataset | Filter | Expected reduction |
|---|---|---|
| NP3-565-CD | `InUseFlag == 'Y'` (row filter) | ~7× fewer rows (drops inactive model runs) |
| NP6-905-CD | `SettlementPointName ∈ {HB_HOUSTON, HB_BUSAVG}` (row filter) | ~200× fewer rows (drops all non-hub points) |
| NP4-732-CD | Drop `LZ_WEST` and `LZ_NORTH` columns | ~4 fewer columns per file |

Writes are atomic (temp file → rename).  Stale `.sortcache.json` sidecars are
removed.  Already-filtered files are detected and skipped, so re-running is safe.

In [6]:

# ── One-time raw CSV pre-filter ───────────────────────────────────────────────
# Set to True, run once, then set back to False.
FILTER_RAW_CSVS = False

if FILTER_RAW_CSVS:
    # ── Row-filter specs (NP3-565-CD, NP6-905-CD) ────────────────────────────
    _ROW_SPECS = {
        'NP3-565-CD': {
            'col':   'InUseFlag',
            'keep':  {'Y'},
            'check': lambda df: set(df['InUseFlag'].unique()) <= {'Y'},
        },
        'NP6-905-CD': {
            'col':   'SettlementPointName',
            'keep':  {'HB_HOUSTON', 'HB_BUSAVG'},
            'check': lambda df: set(df['SettlementPointName'].unique()) <= {'HB_HOUSTON', 'HB_BUSAVG'},
        },
    }

    for _ds, _spec in _ROW_SPECS.items():
        _csvs = sorted((RAW_ROOT / _ds).rglob('*.csv'))
        print(f'\n{_ds}  ({len(_csvs)} files)  filter: {_spec["col"]} ∈ {_spec["keep"]}')
        _ds_before = _ds_after = 0
        for _p in _csvs:
            _df = pd.read_csv(_p, low_memory=False)
            _n0 = len(_df)
            if _spec['check'](_df):
                print(f'  skip  {_p.name}  ({_n0:,} rows already filtered)')
                _ds_before += _n0; _ds_after += _n0
                continue
            _df2 = _df[_df[_spec['col']].isin(_spec['keep'])].reset_index(drop=True)
            _n1  = len(_df2)
            _tmp = _p.with_suffix('.tmp')
            try:
                _df2.to_csv(_tmp, index=False)
                _tmp.replace(_p)
            except Exception:
                _tmp.unlink(missing_ok=True)
                raise
            (_p.parent / (_p.name + '.sortcache.json')).unlink(missing_ok=True)
            _ds_before += _n0; _ds_after += _n1
            print(f'  done  {_p.name}  {_n0:>10,} → {_n1:>10,} rows  '
                  f'(-{100*(1-_n1/_n0):.1f}%)')
        print(f'  total: {_ds_before:,} → {_ds_after:,} rows  '
              f'(-{100*(1-_ds_after/_ds_before):.1f}%)')

    # ── Column-drop spec (NP4-732-CD) ────────────────────────────────────────
    # Drop LZ_WEST and LZ_NORTH columns; keep system-wide + LZ_SOUTH_HOUSTON.
    # Works across both schemas (pre/post 2024-10 rename).
    print(f'\nNP4-732-CD  — drop LZ_WEST and LZ_NORTH columns')
    _732_csvs = sorted((RAW_ROOT / 'NP4-732-CD').rglob('*.csv'))
    _DROP_PAT  = ('LZ_WEST', 'LZ_NORTH')
    for _p in _732_csvs:
        _df = pd.read_csv(_p, low_memory=False)
        _drop = [c for c in _df.columns if any(pat in c for pat in _DROP_PAT)]
        if not _drop:
            print(f'  skip  {_p.name}  (already filtered)')
            continue
        _df2 = _df.drop(columns=_drop)
        _tmp = _p.with_suffix('.tmp')
        try:
            _df2.to_csv(_tmp, index=False)
            _tmp.replace(_p)
        except Exception:
            _tmp.unlink(missing_ok=True)
            raise
        (_p.parent / (_p.name + '.sortcache.json')).unlink(missing_ok=True)
        print(f'  done  {_p.name}  dropped {_drop}')

    print('\nDone. Set FILTER_RAW_CSVS = False to skip on future runs.')
else:
    print('FILTER_RAW_CSVS=False — skipping (set to True to run)')

FILTER_RAW_CSVS=False — skipping (set to True to run)

## 3. Load and Clean Each Dataset

Each dataset is parsed to a **fixed UTC-6 (CST) timestamp** (`ts_utc`, = local CST; CDT hours shift 1h earlier), key columns kept, and duplicates dropped.

| Dataset | Recommended dedup key |
|---|---|
| NP6-346-CD | `OperDay, HourEnding` |
| NP6-345-CD | `OperDay, HourEnding` |
| NP3-565-CD | `DeliveryDate, HourEnding, Model, InUseFlag` (or just use InUseFlag=Y — reduces to single active model) |
| NP6-905-CD | `DeliveryDate, DeliveryHour, DeliveryInterval, SettlementPointName` |
| NP4-732-CD | `DELIVERY_DATE, HOUR_ENDING` |
| NP4-190-CD | `DeliveryDate, HourEnding, SettlementPoint` |
| NP4-523-CD | `DeliveryDate, HourEnding` |
| NP4-188-CD | `DeliveryDate, HourEnding, AncillaryType` |
| NP3-233-CD | `Date, HourEnding` |

### NP6-346-CD — Actual Load, 4 Pricing Zones (hourly)

Columns: `postDateTime, OperDay, HourEnding, NORTH, SOUTH, WEST, HOUSTON, TOTAL, DSTFlag`  
Zones match the 4 hub pricing zones directly.  
Coverage: 2017-07 → 2025-12.

In [7]:
load346_raw = read_monthly_csvs(
    'NP6-346-CD',
    usecols=['OperDay', 'HourEnding', 'NORTH', 'SOUTH', 'WEST', 'HOUSTON', 'TOTAL', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

load346 = load346_raw.copy()
for col in ['NORTH', 'SOUTH', 'WEST', 'HOUSTON', 'TOTAL']:
    load346[col] = pd.to_numeric(load346[col], errors='coerce')
load346['ts_utc'] = parse_ts_cst(load346['OperDay'], load346['HourEnding'], load346['DSTFlag'])
load346 = (
    load346[['ts_utc', 'NORTH', 'SOUTH', 'WEST', 'HOUSTON', 'TOTAL']]
    .rename(columns=str.lower)
    .drop_duplicates(subset=['ts_utc'])
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

dataset_summary(load346, 'NP6-346-CD — Actual load, 4 pricing zones')

────────────────────────────────────────────────────────────
NP6-346-CD — Actual load, 4 pricing zones
  74,521 rows  ×  6 cols
  range : 2017-06-29 23:00:00  →  2025-12-30 23:00:00

  columns:
    ts_utc                              datetime64[us]
    north                               float64
    south                               float64
    west                                float64
    houston                             float64
    total                               float64

  nulls : none

           north      south       west    houston      total
count  74521.000  74521.000  74521.000  74521.000  74521.000
mean   16522.913  12487.370   6273.990  12490.124  47774.396
std     4408.968   3207.139   1897.557   2851.890  11189.454
min     8670.510   6688.850   2790.270   4770.730  26808.680
5%     10906.990   8300.670   3777.600   8834.950  33104.460
25%    13379.410  10090.550   4766.250  10371.850  39514.800
50%    15408.530  11762.650   5716.720  11800.990  45419.970
75%    18854.890  14381.300   7822.020  14191.120  54245.030
95%    25547.850  18815.520   9628.760  18154.120  69894.620
max    32587.170  23745.320  11881.610  22693.080  85558.980

  head:

               ts_utc     north     south     west   houston     total
0 2017-06-29 23:00:00  16962.41  12773.25  4085.46  12325.89  46147.01
1 2017-06-30 00:00:00  16018.65  12049.90  3930.27  11794.53  43793.35
2 2017-06-30 01:00:00  15387.91  11513.66  3813.11  11430.60  42145.28
3 2017-06-30 02:00:00  15023.12  11200.89  3744.59  11244.33  41212.93
4 2017-06-30 03:00:00  14998.17  11074.91  3686.25  11290.21  41049.55

Three-panel overview: total system load, Houston-zone load, and the Houston/total ratio. The ratio (~23–26%) tracks Houston's share of grid demand and serves as a proxy for north–south congestion.

In [8]:
fig, axes = plt.subplots(3, 1, figsize=(16, 9), sharex=True)
axes[0].plot(load346['ts_utc'], load346['total'], lw=0.3, color='steelblue', alpha=0.8)
axes[0].set_title('NP6-346-CD — Total actual load (MW)')
axes[0].set_ylabel('MW')

axes[1].plot(load346['ts_utc'], load346['houston'], lw=0.3, color='tomato', alpha=0.8)
axes[1].set_title('NP6-346-CD — Houston zone actual load (MW)')
axes[1].set_ylabel('MW')

axes[2].plot(load346['ts_utc'], load346['houston'] / load346['total'], lw=0.3, color='darkorange', alpha=0.8)
axes[2].set_title('NP6-346-CD — Houston / total load ratio')
axes[2].set_ylabel('ratio')

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2324903466.py:21: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### ⚠️ Data Anomaly — NP6-346-CD: 24 future-dated rows (2025-11-17)

A single source document posted on **2025-11-15 05:50:00** covers all 24 delivery hours of **2025-11-17**, giving a positive horizon of +42.2h to +65.2h. All other 75,913 rows are correctly retrospective (negative horizon).

| Field | Value |
|---|---|
| postDateTime | 2025-11-15 05:50:00 |
| Delivery date | 2025-11-17 (all 24 hours) |
| horizon_h range | +42.2h → +65.2h |
| Row count | 24 |
| Source file | `data/raw/ercot/NP6-346-CD/2025/11/NP6-346-CD_202511.csv` |

**Assessment**: Likely an early-release or mis-filed document — actual load data published two days before delivery. Impact is negligible: the `drop_duplicates(keep='last')` deduplication retains the most recent posting per delivery slot, so these rows are overwritten by the correct retrospective values once they are published.

### NP6-345-CD — Actual Load, 8 Weather Zones (hourly)

Columns: `postDateTime, OperDay, HourEnding, COAST, EAST, FAR_WEST, NORTH, NORTH_C, SOUTHERN, SOUTH_C, WEST, TOTAL, DSTFlag`  
Same actual load as NP6-346-CD but at weather-zone granularity. Used to compute forecast errors against NP3-565-CD forecasts, which share the same 8-zone structure.  
Coverage: 2017-07 → 2025-12.

In [9]:

load345_raw = read_monthly_csvs(
    'NP6-345-CD',
    usecols=['OperDay', 'HourEnding', 'COAST', 'EAST', 'FAR_WEST', 'NORTH', 'NORTH_C',
             'SOUTHERN', 'SOUTH_C', 'WEST', 'TOTAL', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

load345 = load345_raw.copy()
ZONE_COLS_345 = ['COAST', 'EAST', 'FAR_WEST', 'NORTH', 'NORTH_C', 'SOUTHERN', 'SOUTH_C', 'WEST', 'TOTAL']
for col in ZONE_COLS_345:
    load345[col] = pd.to_numeric(load345[col], errors='coerce')
load345['ts_utc'] = parse_ts_cst(load345['OperDay'], load345['HourEnding'], load345['DSTFlag'])
load345 = (
    load345[['ts_utc'] + ZONE_COLS_345]
    .rename(columns=str.lower)
    .drop_duplicates(subset=['ts_utc'])
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

dataset_summary(load345, 'NP6-345-CD — Actual load, all 8 weather zones + Total')

────────────────────────────────────────────────────────────
NP6-345-CD — Actual load, all 8 weather zones + Total
  74,521 rows  ×  10 cols
  range : 2017-06-29 23:00:00  →  2025-12-30 23:00:00

  columns:
    ts_utc                              datetime64[us]
    coast                               float64
    east                                float64
    far_west                            float64
    north                               float64
    north_c                             float64
    southern                            float64
    south_c                             float64
    west                                float64
    total                               float64

  nulls : none

,coast,east,far_west,north,north_c,southern,south_c,west,total
count,74521.000,74521.000,74521.000,74521.000,74521.000,74521.000,74521.000,74521.000,74521.000
mean,12942.900,1734.340,4708.642,1274.122,14142.432,3831.445,7737.633,1402.883,47774.396
std,2955.032,423.548,1694.871,432.759,3851.538,942.486,2134.622,299.894,11189.454
min,4935.200,500.000,1086.590,300.000,7439.160,1859.650,3923.680,400.000,26808.680
5%,9154.700,1185.570,2489.320,743.720,9265.850,2551.750,4974.760,995.830,33104.460
25%,10748.090,1431.240,3405.750,934.520,11406.910,3103.810,6149.160,1187.370,39514.800
50%,12228.670,1631.750,4121.590,1172.430,13141.990,3647.660,7249.750,1350.700,45419.970
75%,14705.860,1972.740,6189.570,1537.890,16151.630,4454.920,8948.580,1573.140,54245.030
95%,18811.620,2573.820,7698.620,2120.790,22058.210,5616.140,12000.200,1987.520,69894.620
max,23515.820,3674.090,9461.680,3066.370,28268.770,7209.290,15564.030,4000.000,85558.980

  head:

,ts_utc,coast,east,far_west,north,north_c,southern,south_c,west,total
0,2017-06-29 23:00:00,12772.35,1750.20,2442.93,1133.77,14642.03,3858.07,7928.67,1619.00,46147.01
1,2017-06-30 00:00:00,12221.90,1663.85,2363.99,1094.61,13802.06,3649.33,7460.13,1537.48,43793.35
2,2017-06-30 01:00:00,11844.95,1604.83,2306.38,1048.68,13253.64,3507.53,7096.73,1482.53,42145.28
3,2017-06-30 02:00:00,11652.00,1533.51,2270.51,1038.57,12964.89,3393.53,6918.35,1441.56,41212.93
4,2017-06-30 03:00:00,11699.66,1576.41,2240.14,989.58,12925.32,3333.60,6854.05,1430.78,41049.55

NP6-345-CD breaks demand into 8 finer weather zones. The **Coast** zone (Houston metro) is the dominant contributor and is used as the Houston-zone proxy in later analyses. This granularity aligns with the NP3-565-CD load forecasts.

In [10]:

fig, axes = plt.subplots(2, 1, figsize=(16, 6), sharex=True)

axes[0].plot(load345['ts_utc'], load345['coast'], lw=0.3, color='tomato', alpha=0.8, label='Coast')
axes[0].plot(load345['ts_utc'], load345['total'], lw=0.3, color='black', alpha=0.6, label='Total')
axes[0].set_title('NP6-345-CD — Coast zone (Houston proxy) and system total load (MW)')
axes[0].set_ylabel('MW')
axes[0].legend(fontsize=8, loc='upper left')

axes[1].plot(load345['ts_utc'], load345['coast'] / load345['total'], lw=0.3, color='darkorange', alpha=0.8)
axes[1].set_title('NP6-345-CD — Coast / total load ratio (Houston weather zone share)')
axes[1].set_ylabel('ratio')

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3871411267.py:20: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### NP3-565-CD — 7-Day Load Forecast, 8 Weather Zones (hourly)

Columns: `postDateTime, DeliveryDate, HourEnding, Coast, East, FarWest, North, NorthCentral, SouthCentral, Southern, West, SystemTotal, Model, InUseFlag, DSTFlag`

ERCOT runs 8 forecast models simultaneously. `InUseFlag='Y'` marks the single active model per (postDateTime, DeliveryHour) — filtered here to reduce 8× row count.

A `horizon_h` column is computed (rounded hours from post time to delivery hour start). All posts are at `:30` so horizons always land on even integers. Useful for downstream filtering to specific lead times (e.g. keep only `horizon_h ∈ {2, 4, 6, 12}` for 1h/3h/6h/12h-ahead forecasts).

Zone column names are aligned to NP6-345-CD conventions for direct forecast-error joins.  
Coverage: 2017-07 → 2025-12.

> **⚠ Known anomaly — May 2020 (`NP3-565-CD_202005.csv`):** 168 rows with `postDateTime=2020-05-14` and `DeliveryDate=05/13/2020` (delta = −1 day). These are forecasts published one day *after* the delivery date — a legitimate ERCOT retroactive correction, not a processing error. Expect a small spike in `delta_days` around this month.

In [11]:

ZONE_COLS_565 = ['Coast', 'SystemTotal']

fc565_raw = read_monthly_csvs(
    'NP3-565-CD',
    usecols=['postDateTime', 'DeliveryDate', 'HourEnding'] + ZONE_COLS_565 + ['Model', 'InUseFlag', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

# Keep active model only (drops 7 of 8 model rows per delivery slot)
fc565 = fc565_raw[fc565_raw['InUseFlag'] == 'Y'].copy()

for col in ZONE_COLS_565:
    fc565[col] = pd.to_numeric(fc565[col], errors='coerce')

# Delivery timestamp (UTC)
fc565['ts_utc'] = parse_ts_cst(fc565['DeliveryDate'], fc565['HourEnding'], fc565['DSTFlag'])

# Compute forecast horizon: integer hours from floor(postDateTime) to delivery start.
_he = parse_hour_ending(fc565['HourEnding'])
_post_floor = pd.to_datetime(fc565['postDateTime'].str[:19], errors='coerce').dt.floor('h')
fc565['horizon_h'] = ((fc565['ts_utc'] - _post_floor).dt.total_seconds() / 3600).astype('Int64')

# days_ahead: calendar days from posting date to delivery date.
_post_date = pd.to_datetime(fc565['postDateTime'].str[:10], errors='coerce')
_del_date  = pd.to_datetime(fc565['DeliveryDate'], format='%m/%d/%Y', errors='coerce')
fc565['days_ahead'] = (_del_date - _post_date).dt.days

fc565 = (
    fc565[['ts_utc', 'horizon_h', 'days_ahead'] + ZONE_COLS_565]
    .rename(columns={
        'Coast':       'coast',
        'SystemTotal': 'system_total',
    })
    .drop_duplicates(subset=['ts_utc', 'horizon_h', 'days_ahead'])
    .sort_values(['ts_utc', 'horizon_h'])
    .reset_index(drop=True)
)

dataset_summary(fc565, 'NP3-565-CD — Load forecast, Coast + SystemTotal (InUseFlag=Y)')
print(f'  horizon_h: {fc565.horizon_h.min()} → {fc565.horizon_h.max()} h')
print(f'  unique horizons (first 20): {sorted(fc565.horizon_h.dropna().unique())[:20]}')
print(f'  days_ahead: {fc565.days_ahead.min()} → {fc565.days_ahead.max()}')

────────────────────────────────────────────────────────────
NP3-565-CD — Load forecast, Coast + SystemTotal (InUseFlag=Y)
  14,303,648 rows  ×  5 cols
  range : 2017-06-30 23:00:00  →  2026-01-07 23:00:00

  columns:
    ts_utc                              datetime64[us]
    horizon_h                           Int64
    days_ahead                          int64
    coast                               float64
    system_total                        float64

  nulls : none

        horizon_h    days_ahead         coast  system_total
count  14303648.0  1.430365e+07  1.430365e+07  1.430365e+07
mean       83.348  3.500000e+00  1.293874e+04  4.775257e+04
std        55.858  2.291000e+00  2.918609e+03  1.135589e+04
min         -43.0 -1.000000e+00  4.192190e+03  2.548852e+04
5%           -3.0  0.000000e+00  9.188180e+03  3.300474e+04
25%          35.0  1.000000e+00  1.075680e+04  3.930881e+04
50%          83.0  3.000000e+00  1.221520e+04  4.526800e+04
75%         131.0  5.000000e+00  1.470087e+04  5.420364e+04
95%         170.0  7.000000e+00  1.871580e+04  7.034293e+04
max         191.0  7.000000e+00  2.366020e+04  8.933611e+04

  head:

               ts_utc  horizon_h  days_ahead       coast  system_total
0 2017-06-30 23:00:00        -24           0  13488.5996    47160.3198
1 2017-06-30 23:00:00        -23           0  13488.5996    47160.3198
2 2017-06-30 23:00:00        -22           0  13488.5996    47160.3198
3 2017-06-30 23:00:00        -21           0  13488.5996    47160.3198
4 2017-06-30 23:00:00        -20           0  13488.5996    47160.3198

  horizon_h: -43 → 191 h
  unique horizons (first 20): [np.int64(-43), np.int64(-42), np.int64(-41), np.int64(-40), np.int64(-39), np.int64(-38), np.int64(-37), np.int64(-36), np.int64(-35), np.int64(-34), np.int64(-33), np.int64(-32), np.int64(-31), np.int64(-30), np.int64(-29), np.int64(-28), np.int64(-27), np.int64(-26), np.int64(-25), np.int64(-24)]
  days_ahead: -1 → 7

Two features are derived from the multi-horizon forecast data and merged into `master`:

- **`fc_<zone>` / `fc_system_total`** — D+1 closest forecast: last posting from the prior calendar day (`days_ahead=1`, `idxmin('horizon_h')`). Operationally actionable day-ahead load forecast with no same-day leakage.
- **`fc_<zone>_rev_std` / `fc_system_total_rev_std`** — 7-day revision std dev: for `days_ahead=1..7`, take the last posting of each day, then compute `std(ddof=1)` across those 7 values per delivery hour. High std signals that forecasters kept revising this hour as the date approached — a proxy for meteorological uncertainty and elevated price-spike risk.

In [12]:

# ── 6PM D-1 snapshot + 48h revision std ──────────────────────────────────────
# For each D+1 delivery hour:
#   cutoff      = delivery_date − 1 day + 18:00  (6PM "today", when DAM + actuals are all available)
#   window      = [cutoff − 48h, cutoff]
#   point est.  = forecast with min horizon_h in window (= latest posting before 6PM)
#   std         = revision std over all postings in the 48h window
#
# Using horizon_h as a proxy for postDateTime:
#   postDateTime_floor ≈ ts_utc − horizon_h
#   posted ≤ cutoff  →  horizon_h ≥ ts_utc − cutoff   (= _h_min, varies by delivery hour)
#   posted ≥ win_start → horizon_h ≤ ts_utc − win_start (= _h_min + 48)

_ZONE_COLS = ['coast', 'system_total']

_del_date = fc565['ts_utc'].dt.normalize()
_cutoff   = _del_date - pd.Timedelta(days=1) + pd.Timedelta(hours=18)
_h_min    = (fc565['ts_utc'] - _cutoff).dt.total_seconds() / 3600
_h_max    = _h_min + 48

fc_window = fc565[
    (fc565['horizon_h'] >= _h_min) &
    (fc565['horizon_h'] <= _h_max)
].copy()

# Point estimate: min horizon_h per delivery slot = latest posting ≤ 6PM
fc565_d1 = (
    fc_window.loc[fc_window.groupby('ts_utc')['horizon_h'].idxmin()]
    .drop(columns='days_ahead')
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

# Revision std over 48h window (ddof=1; NaN when fewer than 2 snapshots)
_rev_std = (
    fc_window.groupby('ts_utc')[_ZONE_COLS]
    .std(ddof=1)
    .rename(columns={c: f'{c}_std_48h' for c in _ZONE_COLS})
    .reset_index()
)

# Combined output with fc_ prefix for master merge
fc565_f1 = (
    fc565_d1
    .merge(_rev_std, on='ts_utc', how='left')
    .rename(columns=lambda c: c if c == 'ts_utc' else
                              'fc_horizon_h' if c == 'horizon_h' else
                              f'fc_{c}')
)

print(f'fc_window : {len(fc_window):,} rows  '
      f'(avg {len(fc_window) / max(fc565_d1.ts_utc.nunique(), 1):.1f} snapshots/slot)')
print(f'fc565_d1  : {len(fc565_d1):,} rows')
print(f'  fc_horizon_h range: {fc565_d1.horizon_h.min()} – {fc565_d1.horizon_h.max()} h')
print(f'fc565_f1  : {len(fc565_f1):,} rows, {fc565_f1.shape[1]} columns')
print(f'  std_48h (system_total): median={_rev_std.system_total_std_48h.median():.1f} MW, '
      f'max={_rev_std.system_total_std_48h.max():.1f} MW')

# ── Plots ─────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(3, 1, figsize=(16, 9), sharex=True)

axes[0].plot(fc565_d1['ts_utc'], fc565_d1['system_total'], lw=0.3, color='steelblue', alpha=0.8)
axes[0].set_title('NP3-565-CD — Load forecast (6PM D-1 snapshot): system total (MW)')
axes[0].set_ylabel('MW')

axes[1].plot(fc565_d1['ts_utc'], fc565_d1['coast'], lw=0.3, color='tomato', alpha=0.8)
axes[1].set_title('NP3-565-CD — Load forecast (6PM D-1 snapshot): Coast zone (MW)')
axes[1].set_ylabel('MW')

axes[2].plot(_rev_std['ts_utc'], _rev_std['system_total_std_48h'], lw=0.3, color='purple', alpha=0.8)
axes[2].set_title('NP3-565-CD — 48h forecast revision std dev: system total (MW)')
axes[2].set_ylabel('std (MW)')

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

fc_window : 3,650,328 rows  (avg 48.9 snapshots/slot)
fc565_d1  : 74,592 rows
  fc_horizon_h range: 6 – 72 h
fc565_f1  : 74,592 rows, 6 columns
  std_48h (system_total): median=390.0 MW, max=5947.4 MW

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2923602319.py:80: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


> **Optional — save full multi-horizon forecast data.**
> `fc565` contains all 7-day × ~24-per-day postings (~105M rows). It is **not needed for modeling** — all derived features are in `fc565_f1`. Set `SAVE_FC565_FULL = True` in the cell below only if you need the raw revision history for custom horizon analysis. The file will be several GB on disk and is excluded from the default pipeline.

In [13]:

# ── Optional: save full multi-horizon load forecast data ─────────────────────
# Not needed for modeling. Flip to True only for custom horizon analysis.
SAVE_FC565_FULL = False

if SAVE_FC565_FULL:
    _p = PROCESSED_ROOT / 'np3_565_load_forecast.parquet'
    fc565.to_parquet(_p, index=False)
    print(f'  np3_565_load_forecast.parquet  ({_p.stat().st_size / 1e6:.1f} MB, {len(fc565):,} rows)')
else:
    print('  Skipped (SAVE_FC565_FULL=False)')

# Free memory — fc565 and fc565_raw no longer needed downstream.
del fc565_raw, fc565, fc_window

  Skipped (SAVE_FC565_FULL=False)

Forecast revision plots for each December (2017–2024): each line shows the load forecast published N hours before delivery for a representative week. Convergence of lines toward the delivery hour illustrates how forecast skill improves at shorter horizons.

In [14]:
# ── Same two plots for every other December (2017–2023) ──────────────────────
# Matches the Dec 2024 sample above: Plot 1 = week overlay, Plot 2 = single-day revision.
HORIZONS = [2, 6, 12, 24, 48, 72, 120, 168]
_hcolors = plt.cm.plasma_r(np.linspace(0.1, 0.9, len(HORIZONS)))

for yr in range(2017, 2025):
    _p = Path(f'data/raw/ercot/NP3-565-CD/{yr}/12/NP3-565-CD_{yr}12.csv')
    if not _p.exists():
        continue

    _raw = pd.read_csv(_p, usecols=['postDateTime', 'DeliveryDate', 'HourEnding', 'Coast', 'InUseFlag'])
    _df = _raw[_raw['InUseFlag'] == 'Y'].copy()
    _df['Coast'] = pd.to_numeric(_df['Coast'], errors='coerce')

    _df['del_dt'] = (
        pd.to_datetime(_df['DeliveryDate'], format='%m/%d/%Y')
        + pd.to_timedelta(_df['HourEnding'].str.split(':').str[0].astype(int) - 1, unit='h')
    )
    _df['post_floor'] = pd.to_datetime(_df['postDateTime'].str[:19]).dt.floor('h')
    _df['horizon_h'] = ((_df['del_dt'] - _df['post_floor']).dt.total_seconds() / 3600).round().astype(int)
    _df = _df[(_df['horizon_h'] >= 0) & (_df['horizon_h'] <= 172)].copy()

    # ── Plot 1: week overlay Dec 8–14 ───────────────────────────────────────
    _week = _df[(_df['del_dt'] >= f'{yr}-12-08') & (_df['del_dt'] < f'{yr}-12-15')]

    fig, ax = plt.subplots(figsize=(14, 5))
    for h, c in zip(HORIZONS, _hcolors):
        sub = _week[_week['horizon_h'] == h].sort_values('del_dt')
        if not sub.empty:
            ax.plot(sub['del_dt'], sub['Coast'], label=f'{h}h ahead', color=c, lw=1.5, alpha=0.85)

    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
    ax.xaxis.set_major_locator(mdates.DayLocator())
    ax.set_xlabel('Delivery hour')
    ax.set_ylabel('Coast load forecast (MW)')
    ax.set_title(f'NP3-565-CD — Coast forecast by lead time, Dec 8–14 {yr}')
    ax.legend(title='Lead time', bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=9)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    # ── Plot 2: forecast revision for Dec 10 ────────────────────────────────
    _day = _df[_df['del_dt'].dt.date == pd.Timestamp(f'{yr}-12-10').date()].copy()
    _pivot = _day.groupby(['horizon_h', 'del_dt'])['Coast'].mean().unstack('del_dt')
    if _pivot.empty:
        continue

    fig, ax = plt.subplots(figsize=(14, 5))
    for col in _pivot.columns:
        hour_label = col.strftime('%H:00')
        ax.plot(_pivot.index, _pivot[col], lw=1.0, alpha=0.6, label=hour_label)

    ax.invert_xaxis()
    ax.set_xlabel('Horizon (hours before delivery) — right = closer to delivery')
    ax.set_ylabel('Coast load forecast (MW)')
    ax.set_title(f'NP3-565-CD — Forecast revision for Dec 10 {yr} (each line = one delivery hour)')
    ax.axvline(24, color='red', ls='--', lw=1, label='24h-ahead')
    ax.axvline(2,  color='orange', ls='--', lw=1, label='2h-ahead')
    ax.legend(title='Delivery hour', bbox_to_anchor=(1.01, 1), loc='upper left',
              fontsize=7, ncol=2)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:40: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2743052003.py:63: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### Weather-Zone → Forecast-Zone Mapping

NP6-345-CD and NP3-565-CD use 8 weather zones; NP6-346-CD uses 4 forecast/pricing zones. This section finds the best single weather-zone proxy for each forecast zone using Pearson correlation and ratio stability over the full aligned history.

In [15]:

# Weather-zone → forecast-zone mapping (Coast only, Houston focus)
# Full 8-zone correlation analysis was run previously; Coast → Houston is the
# confirmed best proxy (corr > 0.999). With usecols reduced to Coast + Total,
# only the Coast → Houston relationship is verified here.

aligned = load345[['ts_utc', 'coast']].merge(
    load346[['ts_utc', 'houston']], on='ts_utc'
)
corr   = aligned['coast'].corr(aligned['houston'])
ratio  = (aligned['coast'] / aligned['houston'])
print(f'Coast (345) → Houston (346):  corr={corr:.4f}  ratio={ratio.mean():.3f} ± {ratio.std():.4f}')
print(f'Aligned rows: {len(aligned):,}  ({aligned.ts_utc.min().date()} → {aligned.ts_utc.max().date()})')

Coast (345) → Houston (346):  corr=1.0000  ratio=1.036 ± 0.0001
Aligned rows: 74,521  (2017-06-29 → 2025-12-30)

### NP6-905-CD — Real-Time Settlement Point Prices (15-min)

Columns: `postDateTime, DeliveryDate, DeliveryHour, DeliveryInterval, SettlementPointName, SettlementPointType, SettlementPointPrice, DSTFlag`

`DeliveryInterval` is 1–4 within each hour. Hub prices have `SettlementPointType == 'HU'` (note: NP4-190-CD uses `'HB'` — different dataset, different type code). Five hubs exist: `HB_NORTH`, `HB_SOUTH`, `HB_WEST`, `HB_HOUSTON`, `HB_PAN`. Filtered here to the 4 main liquid hubs (excluding Panhandle).

Aggregated to hourly mean, std, max, min — `rtm_price_std` is the intra-hour realized volatility proxy (4 observations per hour).  
Coverage: 2017-07 → 2025-12.

In [16]:
rtm905_raw = read_monthly_csvs(
    'NP6-905-CD',
    usecols=['DeliveryDate', 'DeliveryHour', 'DeliveryInterval',
             'SettlementPointName', 'SettlementPointType', 'SettlementPointPrice', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

# HB_HOUSTON (type HU) = Houston hub; HB_BUSAVG (type SH) = system bus average.
# Keep only these two: Houston-zone focus + system reference.
HUBS_RTM = ['HB_HOUSTON', 'HB_BUSAVG']
rtm905 = rtm905_raw[rtm905_raw['SettlementPointName'].isin(HUBS_RTM)].copy()
rtm905['SettlementPointPrice'] = pd.to_numeric(rtm905['SettlementPointPrice'], errors='coerce')

dh = pd.to_numeric(rtm905['DeliveryHour'], errors='coerce')
di = pd.to_numeric(rtm905['DeliveryInterval'], errors='coerce')
local_ts = (
    pd.to_datetime(rtm905['DeliveryDate'], format='%m/%d/%Y', errors='coerce')
    + pd.to_timedelta(dh - 1, unit='h')
    + pd.to_timedelta((di - 1) * 15, unit='min')
)
is_cdt = (rtm905['DSTFlag'].str.upper() != 'Y').values
ct = local_ts.dt.tz_localize('America/Chicago', ambiguous=is_cdt, nonexistent='NaT')
rtm905['ts_utc'] = ct.dt.tz_convert('UTC').dt.tz_localize(None) - pd.Timedelta(hours=6)
rtm905 = (
    rtm905[['ts_utc', 'SettlementPointName', 'SettlementPointPrice']]
    .rename(columns={'SettlementPointName': 'hub', 'SettlementPointPrice': 'rtm_price'})
    .drop_duplicates(subset=['ts_utc', 'hub'])
    .sort_values(['ts_utc', 'hub'])
    .reset_index(drop=True)
)

dataset_summary(rtm905, 'NP6-905-CD — RTM hub prices (15-min)')

# Aggregate to hourly
rtm905['ts_hour_utc'] = rtm905['ts_utc'].dt.floor('h')
rtm905_hourly = (
    rtm905.groupby(['ts_hour_utc', 'hub'], as_index=False)
       .agg(rtm_price_mean=('rtm_price', 'mean'),
            rtm_price_std=('rtm_price', 'std'),
            rtm_price_max=('rtm_price', 'max'),
            rtm_price_min=('rtm_price', 'min'))
    .rename(columns={'ts_hour_utc': 'ts_utc'})
    .sort_values(['ts_utc', 'hub'])
    .reset_index(drop=True)
)
dataset_summary(rtm905_hourly, 'NP6-905-CD — RTM hub prices (hourly aggregated)')

────────────────────────────────────────────────────────────
NP6-905-CD — RTM hub prices (15-min)
  596,354 rows  ×  3 cols
  range : 2017-06-30 22:45:00  →  2025-12-31 23:30:00

  columns:
    ts_utc                              datetime64[us]
    hub                                 str
    rtm_price                           float64

  nulls : none

        rtm_price
count  596354.000
mean       49.993
std       360.635
min      -251.000
5%          8.900
25%        17.300
50%        21.650
75%        31.800
95%        75.880
max      9160.850

  hub  (2 unique):

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3091357164.py:107: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

             count
hub
HB_BUSAVG   298177
HB_HOUSTON  298177

  head:

               ts_utc         hub  rtm_price
0 2017-06-30 22:45:00   HB_BUSAVG      21.98
1 2017-06-30 22:45:00  HB_HOUSTON      22.32
2 2017-06-30 23:00:00   HB_BUSAVG      21.48
3 2017-06-30 23:00:00  HB_HOUSTON      21.64
4 2017-06-30 23:15:00   HB_BUSAVG      21.57

────────────────────────────────────────────────────────────
NP6-905-CD — RTM hub prices (hourly aggregated)
  149,092 rows  ×  6 cols
  range : 2017-06-30 22:00:00  →  2025-12-31 23:00:00

  columns:
    ts_utc                              datetime64[us]
    hub                                 str
    rtm_price_mean                      float64
    rtm_price_std                       float64
    rtm_price_max                       float64
    rtm_price_min                       float64

  nulls :
    rtm_price_std: 0.00%

       rtm_price_mean  rtm_price_std  rtm_price_max  rtm_price_min
count      149092.000     149090.000     149092.000     149092.000
mean           49.992          8.994         60.948         41.528
std           355.536         69.173        388.978        336.152
min          -173.182          0.000       -163.010       -251.000
5%              9.020          0.118         10.610          6.650
25%            17.348          0.426         18.060         16.550
50%            21.848          1.061         23.130         20.570
75%            32.602          2.869         36.710         28.450
95%            77.991         18.839         92.220         64.740
max          9062.542       3213.867       9160.850       9044.820

  hub  (2 unique):

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3091357164.py:107: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

            count
hub
HB_BUSAVG   74546
HB_HOUSTON  74546

  head:

,ts_utc,hub,rtm_price_mean,rtm_price_std,rtm_price_max,rtm_price_min
0,2017-06-30 22:00:00,HB_BUSAVG,21.9800,NaN,21.98,21.98
1,2017-06-30 22:00:00,HB_HOUSTON,22.3200,NaN,22.32,22.32
2,2017-06-30 23:00:00,HB_BUSAVG,21.4975,0.058523,21.57,21.43
3,2017-06-30 23:00:00,HB_HOUSTON,21.6300,0.165328,21.86,21.50
4,2017-07-01 00:00:00,HB_BUSAVG,21.1500,0.546626,21.68,20.40

The 15-min RTM prices are aggregated to hourly frequency — **mean** and **std** per hub-hour. The intra-hour std is retained as a realized-volatility proxy and carried into `master`. The plot clips at 3,000 $/MWh to keep the y-axis readable; spikes (Uri 2021) are captured separately in §4.

In [17]:
fig, axes = plt.subplots(3, 1, figsize=(16, 9), sharex=True)

# Panel 0: HB_HOUSTON + HB_BUSAVG
for hub, c in zip(HUBS_RTM, ['#1f77b4', '#ff7f0e']):
    sub = rtm905_hourly[rtm905_hourly['hub'] == hub].sort_values('ts_utc')
    axes[0].plot(sub['ts_utc'], sub['rtm_price_mean'].clip(upper=3000), lw=0.25, alpha=0.6,
                 label=hub.replace('HB_', ''), color=c)
axes[0].set_title('NP6-905-CD — RTM hourly mean $/MWh (clipped at 3000)')
axes[0].set_ylabel('$/MWh')
axes[0].legend(fontsize=8, loc='upper left', ncol=2)

# Panel 1: HB_HOUSTON alone
_hou = rtm905_hourly[rtm905_hourly['hub'] == 'HB_HOUSTON'].sort_values('ts_utc')
axes[1].plot(_hou['ts_utc'], _hou['rtm_price_mean'].clip(upper=3000), lw=0.3, color='#1f77b4', alpha=0.8)
axes[1].set_title('NP6-905-CD — HB_HOUSTON RTM hourly mean $/MWh (clipped at 3000)')
axes[1].set_ylabel('$/MWh')

# Panel 2: HB_HOUSTON / HB_BUSAVG ratio (Houston premium over system bus average)
_rtm_hou = rtm905_hourly[rtm905_hourly['hub'] == 'HB_HOUSTON'][['ts_utc', 'rtm_price_mean']].rename(columns={'rtm_price_mean': 'hou'})
_rtm_bus = rtm905_hourly[rtm905_hourly['hub'] == 'HB_BUSAVG'][['ts_utc', 'rtm_price_mean']].rename(columns={'rtm_price_mean': 'busavg'})
_rtm_r   = _rtm_hou.merge(_rtm_bus, on='ts_utc').sort_values('ts_utc')
axes[2].plot(_rtm_r['ts_utc'], _rtm_r['hou'] / _rtm_r['busavg'], lw=0.3, color='darkorange', alpha=0.8)
axes[2].axhline(1.0, color='black', lw=0.8, linestyle='--', alpha=0.5)
axes[2].set_title('NP6-905-CD — HB_HOUSTON / HB_BUSAVG RTM price ratio')
axes[2].set_ylabel('ratio')

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3010326578.py:34: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### 🚨 Data Anomaly — NP6-905-CD: 2 extreme outlier rows (horizon = −604.9h, ~25 days)

A single source document has a `postDateTime` of **2020-03-16 15:51:30** but covers delivery on **2020-02-20 Hour 12**, giving a horizon of −604.86h (~25 days stale). Both rows are for the same delivery slot, one per hub.

| Field | Value |
|---|---|
| postDateTime | 2020-03-16 15:51:30.202 |
| DeliveryDate | 02/20/2020 |
| DeliveryHour | 12 |
| SettlementPointName | HB_BUSAVG, HB_HOUSTON |
| SettlementPointPrice | 10.67, 13.25 |
| horizon_h | −604.86h (~25.2 days) |
| Row count | 2 |
| Source file | `data/raw/ercot/NP6-905-CD/2020/03/NP6-905-CD_202003.csv` |

**Assessment**: The `postDateTime` is almost certainly wrong — a March 2020 document was backfilled with a date ~25 days after the delivery slot it covers. This is a ERCOT source data error, unresolvable. Impact is negligible for the hourly aggregated dataset (`rtm905_hourly`): the `drop_duplicates(keep='last')` on `(ts_utc, hub)` in the 15-min data will retain the latest posting, and this slot (2020-02-20 Hour 12) will have correct values from earlier postings.

### NP4-732-CD — Wind Power Production, Actual + Forecast (hourly)

Columns: `postDateTime, DELIVERY_DATE, HOUR_ENDING, SYSTEM_WIDE_GEN, COP_HSL_SYSTEM_WIDE, STWPF_SYSTEM_WIDE, WGRPP_SYSTEM_WIDE, GEN_LZ_SOUTH_HOUSTON, ..._LZ_WEST, ..._LZ_NORTH, SYSTEM_WIDE_HSL, DSTFlag`

Four values per zone: `GEN` (actual), `COP_HSL` (capacity high sustainable limit), `STWPF` (short-term wind power forecast), `WGRPP` (wind generation resource production potential).  
Wind zones: system-wide + 3 load zones (`LZ_SOUTH_HOUSTON`, `LZ_WEST`, `LZ_NORTH`).  
Wind forecast error = `GEN - STWPF`.  
Coverage: 2017-07 → 2025-12.

In [18]:
# Schema changed at 2024-10: ACTUAL_* renamed to GEN_*/SYSTEM_WIDE_GEN; SYSTEM_WIDE_HSL added.
# 2024-09 has both old and new names simultaneously.
# Fix: normalize column names per file before concat to avoid post-concat duplicates.
_732_rename = {
    'ACTUAL_SYSTEM_WIDE':      'SYSTEM_WIDE_GEN',
    'ACTUAL_LZ_SOUTH_HOUSTON': 'GEN_LZ_SOUTH_HOUSTON',
}

WIND_COLS = [
    'SYSTEM_WIDE_GEN', 'COP_HSL_SYSTEM_WIDE', 'STWPF_SYSTEM_WIDE', 'WGRPP_SYSTEM_WIDE',
    'GEN_LZ_SOUTH_HOUSTON', 'COP_HSL_LZ_SOUTH_HOUSTON', 'STWPF_LZ_SOUTH_HOUSTON', 'WGRPP_LZ_SOUTH_HOUSTON',
    'SYSTEM_WIDE_HSL',
]

def _read_wind_file(path):
    df = pd.read_csv(path, low_memory=False)
    df = df.rename(columns=_732_rename)
    df = df.loc[:, ~df.columns.duplicated()]   # drop redundant old-name copies
    return df

_wind_files = sorted((RAW_ROOT / 'NP4-732-CD').glob('*/*/*.csv'))
_wind_files = [f for f in _wind_files if not f.name.endswith('.docids')]
_wind_files = [f for f in _wind_files
               if (int(f.parent.parent.name), int(f.parent.name)) >= (2017, 7)
               and (int(f.parent.parent.name), int(f.parent.name)) <= (2025, 12)]
wind_raw = pd.concat((_read_wind_file(f) for f in _wind_files), ignore_index=True)

# SYSTEM_WIDE_HSL absent in pre-2024-10 files — fill with NaN.
for col in WIND_COLS:
    if col not in wind_raw.columns:
        wind_raw[col] = pd.NA

wind = wind_raw.copy()
for col in WIND_COLS:
    wind[col] = pd.to_numeric(wind[col], errors='coerce')
# Drop physically impossible generation values (data error: 2024-08 has ~270k MW retro-posts).
_bad = wind['SYSTEM_WIDE_GEN'] > 60_000
if _bad.any():
    print(f'  dropping {_bad.sum():,} rows with SYSTEM_WIDE_GEN > 60,000 MW (bad retro-posts)')
    wind = wind[~_bad].copy()

# 2018 spring-forward anomaly: ERCOT published HE=3 instead of HE=2 on 03/11/2018.
# HE=3 on a spring-forward day is a non-existent local hour → NaT.
# Treat it as HE=2 (the hour ERCOT intended to publish).
_dst_mask = (wind['DELIVERY_DATE'] == '03/11/2018') & (wind['HOUR_ENDING'] == 3) & (wind['DSTFlag'] == 'N')
if _dst_mask.sum() > 0:
    print(f'  patching {_dst_mask.sum():,} rows: 2018-03-11 HE=3 → HE=2 (spring-forward anomaly)')
    wind.loc[_dst_mask, 'HOUR_ENDING'] = 2

wind['ts_utc']       = parse_ts_cst(wind['DELIVERY_DATE'], wind['HOUR_ENDING'], wind['DSTFlag'])
wind['postDateTime'] = pd.to_datetime(wind['postDateTime'].str[:19], errors='coerce')

_post_floor = wind['postDateTime'].dt.floor('h')
wind['horizon_h'] = ((wind['ts_utc'] - _post_floor).dt.total_seconds() / 3600).astype('Int64')

_post_date_w = wind['postDateTime'].dt.normalize()
_del_date_w  = pd.to_datetime(wind['DELIVERY_DATE'], format='%m/%d/%Y', errors='coerce')
wind['days_ahead'] = (_del_date_w - _post_date_w).dt.days

# wind_all: all horizons, used for forecast1 selection
wind_all = (
    wind[['ts_utc', 'horizon_h', 'days_ahead'] + WIND_COLS]
    .rename(columns=str.lower)
    .drop_duplicates(subset=['ts_utc', 'horizon_h', 'days_ahead'])
    .sort_values(['ts_utc', 'horizon_h'])
    .reset_index(drop=True)
)

# wind: one row per delivery hour — keep final actual (latest postDateTime)
wind = (
    wind.sort_values('postDateTime')
    .drop_duplicates(subset=['ts_utc'], keep='last')
    [['ts_utc'] + WIND_COLS]
    .rename(columns=str.lower)
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

# Derived: wind forecast error (actual - short-term forecast)
wind['wind_error_system']  = wind['system_wide_gen']      - wind['stwpf_system_wide']
wind['wind_error_houston'] = wind['gen_lz_south_houston'] - wind['stwpf_lz_south_houston']

dataset_summary(wind, 'NP4-732-CD — Wind power production, system-wide + Houston (actual + forecast)')
print(f'  horizon_h: {wind_all.horizon_h.min()} → {wind_all.horizon_h.max()} h')
print(f'  days_ahead: {wind_all.days_ahead.min()} → {wind_all.days_ahead.max()}')
print(f'  unique horizons (first 20): {sorted(wind_all.horizon_h.dropna().unique())[:20]}')

  dropping 1,078 rows with SYSTEM_WIDE_GEN > 60,000 MW (bad retro-posts)
  patching 215 rows: 2018-03-11 HE=3 → HE=2 (spring-forward anomaly)

────────────────────────────────────────────────────────────
NP4-732-CD — Wind power production, system-wide + Houston (actual + forecast)
  74,760 rows  ×  12 cols
  range : 2017-06-28 23:00:00  →  2026-01-07 22:00:00

  columns:
    ts_utc                              datetime64[us]
    system_wide_gen                     float64
    cop_hsl_system_wide                 float64
    stwpf_system_wide                   float64
    wgrpp_system_wide                   float64
    gen_lz_south_houston                float64
    cop_hsl_lz_south_houston            float64
    stwpf_lz_south_houston              float64
    wgrpp_lz_south_houston              float64
    system_wide_hsl                     float64
    wind_error_system                   float64
    wind_error_houston                  float64

  nulls :
    system_wide_gen: 1.06%
    cop_hsl_system_wide: 0.00%
    gen_lz_south_houston: 1.06%
    cop_hsl_lz_south_houston: 0.00%
    system_wide_hsl: 85.12%
    wind_error_system: 1.06%
    wind_error_houston: 1.06%

,system_wide_gen,cop_hsl_system_wide,stwpf_system_wide,wgrpp_system_wide,gen_lz_south_houston,cop_hsl_lz_south_houston,stwpf_lz_south_houston,wgrpp_lz_south_houston,system_wide_hsl,wind_error_system,wind_error_houston
count,73970.000,74758.000,74760.000,74760.000,73970.000,74758.000,74760.000,74760.000,11123.000,73970.000,73970.000
mean,10733.502,11096.642,11232.564,8858.504,2470.618,2578.748,2601.897,2017.891,13934.156,-499.847,-134.144
std,6120.668,6510.939,6702.731,6078.526,1586.977,1727.849,1786.936,1584.627,7706.340,1037.719,348.044
min,37.960,132.900,54.900,0.000,0.070,5.400,2.300,0.000,195.470,-23819.820,-6828.120
5%,2102.514,2311.285,2172.990,1162.270,325.280,388.100,340.400,165.595,2859.671,-2598.702,-885.216
25%,5661.768,5790.225,5764.900,3910.750,1141.230,1186.000,1152.275,742.675,7410.215,-667.675,-143.017
50%,10021.835,10089.500,10207.050,7667.050,2238.170,2241.800,2255.700,1636.000,13185.820,-201.430,-31.975
75%,15147.553,15581.450,15818.275,12771.325,3612.428,3653.675,3730.525,2946.300,19884.970,-1.833,15.810
95%,21776.362,23272.905,23695.205,20472.310,5392.369,6024.230,6159.505,5230.510,27420.725,424.679,165.935
max,58023.590,65396.300,62096.300,40831.700,7328.220,8186.400,12192.700,11647.400,43272.110,16716.050,2516.940

  head:

,ts_utc,system_wide_gen,cop_hsl_system_wide,stwpf_system_wide,wgrpp_system_wide,gen_lz_south_houston,cop_hsl_lz_south_houston,stwpf_lz_south_houston,wgrpp_lz_south_houston,system_wide_hsl,wind_error_system,wind_error_houston
0,2017-06-28 23:00:00,12892.95,13379.1,13759.8,12174.5,1685.11,1965.1,1926.2,1543.3,NaN,-866.85,-241.09
1,2017-06-29 00:00:00,13212.22,13506.7,13821.0,12237.1,1687.13,1967.7,1816.4,1434.0,NaN,-608.78,-129.27
2,2017-06-29 01:00:00,13085.11,13354.5,14036.3,12451.6,1798.87,1931.6,1877.9,1495.2,NaN,-951.19,-79.03
3,2017-06-29 02:00:00,12887.65,13120.0,13746.1,12161.3,1983.31,1852.2,1907.8,1525.1,NaN,-858.45,75.51
4,2017-06-29 03:00:00,12512.80,12918.9,13412.4,11828.4,1957.04,1789.0,2011.3,1629.0,NaN,-899.60,-54.26

  horizon_h: -58 → 167 h
  days_ahead: -2 → 7
  unique horizons (first 20): [np.int64(-58), np.int64(-57), np.int64(-56), np.int64(-55), np.int64(-54), np.int64(-53), np.int64(-52), np.int64(-51), np.int64(-50), np.int64(-49), np.int64(-48), np.int64(-47), np.int64(-46), np.int64(-45), np.int64(-44), np.int64(-43), np.int64(-42), np.int64(-41), np.int64(-40), np.int64(-39)]

#### Spring 2018 DST Anomaly

In March 2018 ERCOT published an HE=3 row on the spring-forward day (2018-03-11) instead of the correct HE=2. Since 2:00 AM local time does not exist on a spring-forward day, `parse_ts_cst` would map HE=3 → NaT.

**Fix applied in the loading cell**: rows matching `DELIVERY_DATE == '03/11/2018'` and `HOUR_ENDING == 3` and `DSTFlag == 'N'` are patched to `HOUR_ENDING = 2` before `parse_ts_cst` is called. This recovers the row as `2018-03-11 01:00:00 UTC` (the same slot that HE=2 in all other years maps to), preserving the data rather than losing it to NaT.

All other years (e.g. 2019) correctly skip HE=3 on the spring-forward day.

In [19]:
# ── NP4-732-CD: 2018 spring anomaly ──────────────────────────────────────────
# In 2018 only, ERCOT published HE=3 instead of HE=2 on the spring-forward day.
# parse_ts_cst maps HE=3 → local 02:00 (nonexistent) → NaT.
# Compare with 2019 (normal: skips HE=3, keeps HE=2).

print('NP4-732-CD — Wind: 2018 anomaly (HE=3 instead of HE=2) vs 2019 normal')
print('─' * 70)

for _yr, _mm, _ds in [('2018', '03', '03/11/2018'), ('2019', '03', '03/10/2019')]:
    _csvs = sorted(f for f in (RAW_ROOT / 'NP4-732-CD' / _yr / _mm).glob('*.csv')
                   if not f.name.endswith('.docids'))
    _df = pd.concat([pd.read_csv(f, usecols=['DELIVERY_DATE', 'HOUR_ENDING', 'DSTFlag'],
                                  low_memory=False) for f in _csvs], ignore_index=True)
    _day = _df[_df['DELIVERY_DATE'] == _ds].drop_duplicates(['HOUR_ENDING', 'DSTFlag']).copy()
    _day['_he'] = parse_hour_ending(_day['HOUR_ENDING'])
    _day['ts_utc'] = parse_ts_cst(_day['DELIVERY_DATE'], _day['HOUR_ENDING'], _day['DSTFlag'])
    _s = _day[_day['_he'].between(1, 5)].sort_values(['_he', 'DSTFlag'])
    _nh = _day['ts_utc'].dropna().nunique()
    _nat = _day['ts_utc'].isna().sum()
    _flag = '  << ANOMALY' if _nat > 0 else ''
    print(f'\n  {_yr} Spring ({_ds})  [{_nh} UTC hours, {_nat} NaTs]{_flag}')
    print(_s[['DELIVERY_DATE', 'HOUR_ENDING', 'DSTFlag', 'ts_utc']].to_string(index=False))

NP4-732-CD — Wind: 2018 anomaly (HE=3 instead of HE=2) vs 2019 normal
──────────────────────────────────────────────────────────────────────

  2018 Spring (03/11/2018)  [22 UTC hours, 1 NaTs]  << ANOMALY
DELIVERY_DATE  HOUR_ENDING DSTFlag              ts_utc
   03/11/2018            1       N 2018-03-11 00:00:00
   03/11/2018            3       N                 NaT
   03/11/2018            4       N 2018-03-11 02:00:00
   03/11/2018            5       N 2018-03-11 03:00:00

  2019 Spring (03/10/2019)  [23 UTC hours, 0 NaTs]
DELIVERY_DATE  HOUR_ENDING DSTFlag              ts_utc
   03/10/2019            1       N 2019-03-10 00:00:00
   03/10/2019            2       N 2019-03-10 01:00:00
   03/10/2019            4       N 2019-03-10 02:00:00
   03/10/2019            5       N 2019-03-10 03:00:00

#### NP4-732-CD Horizon Exploration — Dec 2024 Sample

Wind power **forecast** (`STWPF_LZ_SOUTH_HOUSTON`) by lead time. Each postDateTime covers the next 7 days; ~167 forecast updates per delivery hour.  
Plot 1 overlays selected horizons over a week. Plot 2 shows how the forecast for a single day revises as delivery approaches.

In [20]:
# ── Load Dec 2024, STWPF South Houston ─────────────────────────────────────
_path732 = 'data/raw/ercot/NP4-732-CD/2024/12/NP4-732-CD_202412.csv'
_raw732 = pd.read_csv(_path732, usecols=[
    'postDateTime', 'DELIVERY_DATE', 'HOUR_ENDING',
    'STWPF_LZ_SOUTH_HOUSTON', 'GEN_LZ_SOUTH_HOUSTON', 'DSTFlag'
])
_df732 = _raw732.copy()
_df732['STWPF_LZ_SOUTH_HOUSTON'] = pd.to_numeric(_df732['STWPF_LZ_SOUTH_HOUSTON'], errors='coerce')
_df732['GEN_LZ_SOUTH_HOUSTON']   = pd.to_numeric(_df732['GEN_LZ_SOUTH_HOUSTON'],   errors='coerce')

# Delivery hour start timestamp
_df732['del_dt'] = (
    pd.to_datetime(_df732['DELIVERY_DATE'], format='%m/%d/%Y')
    + pd.to_timedelta(_df732['HOUR_ENDING'].astype(int) - 1, unit='h')
)

# Horizon (floor post to hour)
_df732['post_floor'] = pd.to_datetime(_df732['postDateTime'].str[:19]).dt.floor('h')
_df732['horizon_h'] = ((_df732['del_dt'] - _df732['post_floor']).dt.total_seconds() / 3600).round().astype('Int64')

_df732 = _df732[(_df732['horizon_h'] >= 0) & (_df732['horizon_h'] <= 172)].copy()

print(f"NP4-732-CD Dec 2024: {len(_df732):,} rows (valid horizons)")
print(f"Horizon range: {_df732['horizon_h'].min()} → {_df732['horizon_h'].max()} h")

# ── Plot 1: week overlay ────────────────────────────────────────────────────
HORIZONS = [2, 6, 12, 24, 48, 72, 120, 168]
_week732 = _df732[(_df732['del_dt'] >= '2024-12-08') & (_df732['del_dt'] < '2024-12-15')]

fig, ax = plt.subplots(figsize=(14, 5))
colors = plt.cm.plasma_r(np.linspace(0.1, 0.9, len(HORIZONS)))

for h, c in zip(HORIZONS, colors):
    sub = _week732[_week732['horizon_h'] == h].sort_values('del_dt')
    if not sub.empty:
        ax.plot(sub['del_dt'], sub['STWPF_LZ_SOUTH_HOUSTON'], label=f'{h}h ahead', color=c, lw=1.5, alpha=0.85)

ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
ax.xaxis.set_major_locator(mdates.DayLocator())
ax.set_xlabel('Delivery hour')
ax.set_ylabel('STWPF South Houston (MW)')
ax.set_title('NP4-732-CD — Wind forecast (STWPF LZ_SOUTH_HOUSTON) by lead time, Dec 8–14 2024')
ax.legend(title='Lead time', bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ── Plot 2: forecast revision for Dec 10 ───────────────────────────────────
_day732 = _df732[_df732['del_dt'].dt.date == pd.Timestamp('2024-12-10').date()].copy()
_pivot732 = (
    _day732.groupby(['horizon_h', 'del_dt'])['STWPF_LZ_SOUTH_HOUSTON']
    .mean().unstack('del_dt')
)

fig, ax = plt.subplots(figsize=(14, 5))
for col in _pivot732.columns:
    ax.plot(_pivot732.index, _pivot732[col], lw=1.0, alpha=0.6, label=col.strftime('%H:00'))

ax.invert_xaxis()
ax.set_xlabel('Horizon (hours before delivery) — right = closer to delivery')
ax.set_ylabel('STWPF South Houston (MW)')
ax.set_title('NP4-732-CD — Wind forecast revision for Dec 10 2024 (each line = one delivery hour)')
ax.axvline(24, color='red',    ls='--', lw=1, label='24h-ahead')
ax.axvline(2,  color='orange', ls='--', lw=1, label='2h-ahead')
ax.legend(title='Delivery hour', bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=7, ncol=2)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

NP4-732-CD Dec 2024: 124,992 rows (valid horizons)
Horizon range: 0 → 167 h

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3561948199.py:30: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, ax = plt.subplots(figsize=(14, 5))
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3561948199.py:46: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3561948199.py:68: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

STWPF (Short-Term Wind Power Forecast) is ERCOT's internal next-day wind generation estimate. Comparing actual `SYSTEM_WIDE_GEN` against STWPF exposes forecast bias and high-error events. LZ_SOUTH_HOUSTON is shown as a regional breakdown — the largest coastal wind cluster in ERCOT.

In [21]:
fig, axes = plt.subplots(3, 1, figsize=(16, 9), sharex=True)
axes[0].plot(wind['ts_utc'], wind['system_wide_gen'],   lw=0.3,  color='forestgreen', alpha=0.7, label='Actual GEN')
axes[0].plot(wind['ts_utc'], wind['stwpf_system_wide'], lw=0.25, color='darkorange',  alpha=0.5, label='STWPF')
axes[0].set_title('NP4-732-CD — System-wide wind: actual vs short-term forecast (MW)')
axes[0].set_ylabel('MW')
axes[0].legend(fontsize=8, loc='upper left')

axes[1].plot(wind['ts_utc'], wind['gen_lz_south_houston'],   lw=0.3,  color='forestgreen', alpha=0.7, label='Actual GEN')
axes[1].plot(wind['ts_utc'], wind['stwpf_lz_south_houston'], lw=0.25, color='darkorange',  alpha=0.5, label='STWPF')
axes[1].set_title('NP4-732-CD — LZ_SOUTH_HOUSTON wind: actual vs short-term forecast (MW)')
axes[1].set_ylabel('MW')
axes[1].legend(fontsize=8, loc='upper left')

axes[2].plot(wind['ts_utc'], wind['gen_lz_south_houston'] / wind['system_wide_gen'], lw=0.3, color='darkorange', alpha=0.8)
axes[2].set_title('NP4-732-CD — LZ_SOUTH_HOUSTON / system-wide wind generation ratio')
axes[2].set_ylabel('ratio')

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/1219288149.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [22]:

# ── NP4-732-CD: 6PM D-1 snapshot + 48h revision std ─────────────────────────
# Same 6PM/48h window logic as NP3-565-CD.
# STWPF only — GEN columns are 0/NaN for future slots and are captured in `wind`.

_STWPF_COLS = ['stwpf_system_wide', 'stwpf_lz_south_houston']

_del_date_w = wind_all['ts_utc'].dt.normalize()
_cutoff_w   = _del_date_w - pd.Timedelta(days=1) + pd.Timedelta(hours=18)
_h_min_w    = (wind_all['ts_utc'] - _cutoff_w).dt.total_seconds() / 3600
_h_max_w    = _h_min_w + 48

wfc_window = wind_all[
    (wind_all['horizon_h'] >= _h_min_w) &
    (wind_all['horizon_h'] <= _h_max_w)
].copy()

# Point estimate: min horizon_h per delivery slot = latest posting ≤ 6PM
wind_d1 = (
    wfc_window.loc[wfc_window.groupby('ts_utc')['horizon_h'].idxmin()]
    .drop(columns='days_ahead')
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

# Revision std over 48h window (ddof=1)
_wrev_std = (
    wfc_window.groupby('ts_utc')[_STWPF_COLS]
    .std(ddof=1)
    .rename(columns={c: f'{c}_std_48h' for c in _STWPF_COLS})
    .reset_index()
)

# Combined output with wf_ prefix for master merge
wind_f1 = (
    wind_d1[['ts_utc', 'horizon_h'] + _STWPF_COLS]
    .merge(_wrev_std, on='ts_utc', how='left')
    .rename(columns=lambda c: c if c == 'ts_utc' else
                              'wf_horizon_h' if c == 'horizon_h' else
                              f'wf_{c}')
)

print(f'wfc_window : {len(wfc_window):,} rows  '
      f'(avg {len(wfc_window) / max(wind_d1.ts_utc.nunique(), 1):.1f} snapshots/slot)')
print(f'wind_d1   : {len(wind_d1):,} rows')
print(f'  wf_horizon_h range: {wind_d1.horizon_h.min()} – {wind_d1.horizon_h.max()} h')
print(f'wind_f1   : {len(wind_f1):,} rows, {wind_f1.shape[1]} columns')
print(f'  std_48h (stwpf_system_wide): median={_wrev_std.stwpf_system_wide_std_48h.median():.1f} MW, '
      f'max={_wrev_std.stwpf_system_wide_std_48h.max():.1f} MW')

# Free memory — raw multi-horizon data no longer needed after this point.
del wind_raw, wind_all, wfc_window

wfc_window : 3,649,187 rows  (avg 48.9 snapshots/slot)
wind_d1   : 74,591 rows
  wf_horizon_h range: 6 – 72 h
wind_f1   : 74,591 rows, 6 columns
  std_48h (stwpf_system_wide): median=631.7 MW, max=4824.3 MW

### NP4-190-CD — DAM Settlement Point Prices (hourly)

Columns: `postDateTime, DeliveryDate, HourEnding, SettlementPoint, SettlementPointPrice, DSTFlag`  
Filter to **hub prices** (`HB_NORTH`, `HB_SOUTH`, `HB_WEST`, `HB_HOUSTON`) — the 4 main liquid reference prices.  
Coverage: 2017-07 → 2025-12.

In [23]:
HUBS = ['HB_NORTH', 'HB_SOUTH', 'HB_WEST', 'HB_HOUSTON']

dam_raw = read_monthly_csvs(
    'NP4-190-CD',
    usecols=['DeliveryDate', 'HourEnding', 'SettlementPoint', 'SettlementPointPrice', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

dam_long = dam_raw[dam_raw['SettlementPoint'].isin(HUBS)].copy()
dam_long['SettlementPointPrice'] = pd.to_numeric(dam_long['SettlementPointPrice'], errors='coerce')
dam_long['ts_utc'] = parse_ts_cst(dam_long['DeliveryDate'], dam_long['HourEnding'], dam_long['DSTFlag'])
dam_long = (
    dam_long[['ts_utc', 'SettlementPoint', 'SettlementPointPrice']]
    .rename(columns={'SettlementPoint': 'hub', 'SettlementPointPrice': 'dam_price'})
    .drop_duplicates(subset=['ts_utc', 'hub'])
    .sort_values(['ts_utc', 'hub'])
    .reset_index(drop=True)
)

# Pivot to wide, then keep Houston + average of all 4 hubs (no HB_BUSAVG in DAM data)
_dam_pivot = dam_long.pivot_table(index='ts_utc', columns='hub', values='dam_price').reset_index()
_dam_pivot.columns.name = None
dam = pd.DataFrame({'ts_utc': _dam_pivot['ts_utc']})
dam['dam_price_houston'] = _dam_pivot['HB_HOUSTON']
dam['dam_price_avg']     = _dam_pivot[HUBS].mean(axis=1)   # simple average of 4 hubs
dam = dam.sort_values('ts_utc').reset_index(drop=True)

dataset_summary(dam, 'NP4-190-CD — DAM prices: Houston + 4-hub average')

────────────────────────────────────────────────────────────
NP4-190-CD — DAM prices: Houston + 4-hub average
  73,889 rows  ×  3 cols
  range : 2017-07-01 23:00:00  →  2026-01-01 23:00:00

  columns:
    ts_utc                              datetime64[us]
    dam_price_houston                   float64
    dam_price_avg                       float64

  nulls : none

       dam_price_houston  dam_price_avg
count          73889.000      73889.000
mean              52.784         51.039
std              326.831        326.655
min               -0.100         -2.845
5%                12.160         10.738
25%               18.690         17.880
50%               24.970         23.963
75%               37.710         35.777
95%               87.152         82.644
max             8995.110       8995.258

  head:

               ts_utc  dam_price_houston  dam_price_avg
0 2017-07-01 23:00:00              22.66        22.2350
1 2017-07-02 00:00:00              20.55        20.2275
2 2017-07-02 01:00:00              19.08        18.9225
3 2017-07-02 02:00:00              17.83        17.7475
4 2017-07-02 03:00:00              17.83        17.7350

The four settlement hubs — HB_NORTH (Dallas area), HB_SOUTH (Corpus Christi), HB_WEST (Midland/Odessa), HB_HOUSTON — cover the main load and generation centers. Price spreads between hubs reflect transmission congestion. Winter Storm Uri (Feb 2021) produced prices at the $9,000/MWh cap; these are clipped to 3,000 in the overview plot.

In [24]:
fig, axes = plt.subplots(2, 1, figsize=(16, 6), sharex=True)

axes[0].plot(dam['ts_utc'], dam['dam_price_houston'].clip(upper=3000),
             lw=0.25, alpha=0.7, color='#1f77b4', label='HB_HOUSTON')
axes[0].plot(dam['ts_utc'], dam['dam_price_avg'].clip(upper=3000),
             lw=0.25, alpha=0.6, color='#ff7f0e', label='4-hub avg')
axes[0].set_title('NP4-190-CD — DAM prices $/MWh (clipped at 3000; Uri 2021 off-scale)')
axes[0].set_ylabel('$/MWh')
axes[0].legend(fontsize=8, loc='upper left')

axes[1].plot(dam['ts_utc'], dam['dam_price_houston'] - dam['dam_price_avg'],
             lw=0.25, alpha=0.7, color='steelblue')
axes[1].axhline(0, color='black', lw=0.5, ls='--')
axes[1].set_title('NP4-190-CD — Houston vs 4-hub avg spread ($/MWh)')
axes[1].set_ylabel('$/MWh')

for ax in axes:
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    ax.tick_params(axis='x', rotation=30, labelsize=8)
    ax.grid(axis='x', alpha=0.25, linestyle='--')
    ax.grid(axis='y', alpha=0.2)

plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3178300312.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### NP4-523-CD — System Lambda (hourly)

Columns: `postDateTime, DeliveryDate, HourEnding, SystemLambda, DSTFlag`  
System-wide shadow price of energy (\$/MWh). Closely tracks RTM hub prices but is a single system-wide signal with no settlement point filtering needed.  
Coverage: 2017-07 → 2025-12.

In [25]:
lambda_raw = read_monthly_csvs(
    'NP4-523-CD',
    usecols=['DeliveryDate', 'HourEnding', 'SystemLambda', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

lam = lambda_raw.copy()
lam['SystemLambda'] = pd.to_numeric(lam['SystemLambda'], errors='coerce')
lam['ts_utc'] = parse_ts_cst(lam['DeliveryDate'], lam['HourEnding'], lam['DSTFlag'])
lam = (
    lam[['ts_utc', 'SystemLambda']]
    .rename(columns={'SystemLambda': 'system_lambda'})
    .drop_duplicates(subset=['ts_utc'])
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

dataset_summary(lam, 'NP4-523-CD — System Lambda')

────────────────────────────────────────────────────────────
NP4-523-CD — System Lambda
  74,545 rows  ×  2 cols
  range : 2017-07-01 23:00:00  →  2026-01-01 23:00:00

  columns:
    ts_utc                              datetime64[us]
    system_lambda                       float64

  nulls : none

       system_lambda
count      74545.000
mean          49.517
std          325.583
min          -94.179
5%             7.878
25%           16.801
50%           22.773
75%           34.700
95%           80.826
max         8982.970

  head:

               ts_utc  system_lambda
0 2017-07-01 23:00:00        22.0272
1 2017-07-02 00:00:00        20.0486
2 2017-07-02 01:00:00        18.8384
3 2017-07-02 02:00:00        17.6960
4 2017-07-02 03:00:00        17.6868

System Lambda is the marginal energy cost of serving an additional MWh at the system level — the LMP without loss and congestion components. It closely tracks real-time fuel costs and is the closest ERCOT equivalent to a system-wide spot price index.

In [26]:
fig, ax = plt.subplots(figsize=(16, 3.5))
ax.plot(lam['ts_utc'], lam['system_lambda'].clip(upper=3000), lw=0.3, color='steelblue', alpha=0.8)
ax.set_title('NP4-523-CD — System Lambda $/MWh (clipped at 3000)')
ax.set_ylabel('$/MWh')
ax.xaxis.set_major_locator(mdates.YearLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
ax.tick_params(axis='x', rotation=30, labelsize=8)
ax.grid(axis='x', alpha=0.25, linestyle='--')
ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3441216946.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### ℹ️ Structural Note — NP4-523-CD: 146 rows with horizon > 36h (November tail, D+2)

In **November files only** (2019, 2021–2025), the last DAM publications within the month cover delivery dates two days forward, pushing the final hours beyond the expected ≤36h day-ahead window.

| Field | Value |
|---|---|
| Affected rows | 146 |
| horizon_h range | ~57–59h |
| HourEnding affected | 23:00–24:00 of the last day of November |
| Affected files | `NP4-523-CD/<year>/11/` for 2019, 2021, 2022, 2023, 2024, 2025 |
| 2020 absent | November 2020 DAM timings did not extend past 36h |

**Assessment**: Structurally valid D+2 postings, not data corruption. The horizon exceeds 36h solely because end-of-November DAM publications cover the first hours of December delivery. No action required.

### NP4-188-CD — Ancillary Service Prices (hourly)

Columns: `postDateTime, DeliveryDate, HourEnding, AncillaryType, MCPC, DSTFlag`  
Market Clearing Price for Capacity (MCPC). `AncillaryType` values: `RRS`, `REGUP`, `REGDN`, `ECRS`, `NSRS`.  
During scarcity events, RRS and REGUP prices spike — useful as a grid-stress indicator.  
Coverage: 2017-07 → 2025-12.

> **Data quality fix (applied to raw CSVs):** From 2017-11 onward the monthly CSVs had `postDateTime`
> sorted descending while `DeliveryDate` sorted ascending, producing mirrored (date, postDateTime) pairs
> with deltas spanning −28 to +30 days. Fixed by `scripts/fix_np4_188_mirror.py`: both columns are
> re-sorted ascending and re-paired, restoring the correct 1-day relationship (100 months corrected).

In [27]:
anc_raw = read_monthly_csvs(
    'NP4-188-CD',
    usecols=['DeliveryDate', 'HourEnding', 'AncillaryType', 'MCPC', 'DSTFlag'],
    from_year=2017, from_month=7, to_year=2025,
)

anc = anc_raw.copy()
anc['MCPC'] = pd.to_numeric(anc['MCPC'], errors='coerce')
anc['ts_utc'] = parse_ts_cst(anc['DeliveryDate'], anc['HourEnding'], anc['DSTFlag'])
anc = (
    anc[['ts_utc', 'AncillaryType', 'MCPC']]
    .rename(columns={'AncillaryType': 'ancillary_type', 'MCPC': 'mcpc'})
    .drop_duplicates(subset=['ts_utc', 'ancillary_type'])
    .sort_values(['ts_utc', 'ancillary_type'])
    .reset_index(drop=True)
)

print('NP4-188-CD (ancillary service prices, long format)')
print(f'  rows: {len(anc):,}   range: {anc.ts_utc.min()} → {anc.ts_utc.max()}')
display(anc.groupby('ancillary_type', observed=True)['mcpc']
           .describe(percentiles=[.05, .25, .5, .75, .95])
           .round(3))

# Pivot to wide format: one column per ancillary type
anc_wide = anc.pivot_table(
    index='ts_utc', columns='ancillary_type', values='mcpc'
).reset_index()
anc_wide.columns.name = None
anc_wide.columns = ['ts_utc'] + [f'mcpc_{c.lower()}' for c in anc_wide.columns[1:]]

print(f'\nNP4-188-CD (wide): {len(anc_wide):,} rows')
print(f'  columns: {list(anc_wide.columns[1:])}')
null_report(anc_wide, 'NP4-188-CD (wide)')
display(anc_wide.head())

NP4-188-CD (ancillary service prices, long format)
  rows: 320,669   range: 2017-07-01 23:00:00 → 2026-01-01 23:00:00

,count,mean,std,min,5%,25%,50%,75%,95%,max
ancillary_type,,,,,,,,,,
ECRS,22489.0,16.899,136.991,0.02,0.05,0.50,1.00,3.05,34.210,4085.33
NSPIN,74545.0,25.154,344.333,0.01,0.45,0.97,1.87,5.00,32.000,12866.70
REGDN,74545.0,17.030,299.290,0.00,0.47,1.50,3.50,7.11,20.640,17925.10
REGUP,74545.0,41.499,634.492,0.00,0.95,2.01,4.60,10.38,38.600,24992.90
RRS,74545.0,50.036,760.365,0.17,0.53,1.63,5.01,12.86,41.808,25674.30

NP4-188-CD (wide): 74,545 rows
  columns: ['mcpc_ecrs', 'mcpc_nspin', 'mcpc_regdn', 'mcpc_regup', 'mcpc_rrs']

NP4-188-CD (wide): 74,545 rows
  mcpc_ecrs: 69.83% null

               ts_utc  mcpc_ecrs  mcpc_nspin  mcpc_regdn  mcpc_regup  mcpc_rrs
0 2017-07-01 23:00:00        NaN        0.12        5.00        3.00      3.45
1 2017-07-02 00:00:00        NaN        0.12        4.28        2.61      2.61
2 2017-07-02 01:00:00        NaN        0.61        3.50        1.93      2.11
3 2017-07-02 02:00:00        NaN        0.61        3.46        2.11      2.00
4 2017-07-02 03:00:00        NaN        0.61        2.61        2.26      2.00

MCPC (Market Clearing Price for Capacity) is the DAM-cleared price for ancillary services, split into two groups: **upward** products (RRS, REGUP, ECRS — spinning reserve and frequency regulation) and **downward** products (REGDN, NSRS — absorbing excess generation). Not all products are procured every hour; availability depends on the study period.

In [28]:
_anc_colors = {
    'mcpc_rrs':   'steelblue',
    'mcpc_regup': 'darkorange',
    'mcpc_ecrs':  'purple',
    'mcpc_regdn': 'green',
    'mcpc_nsrs':  'brown',
}
# Split available ancillary columns into two groups for subplot layout
_anc_cols = [c for c in anc_wide.columns if c.startswith('mcpc_')]
_grp0 = [c for c in ['mcpc_rrs', 'mcpc_regup', 'mcpc_ecrs'] if c in _anc_cols]
_grp1 = [c for c in ['mcpc_regdn', 'mcpc_nsrs'] if c in _anc_cols]
# Any unexpected types go into grp1
_grp1 += [c for c in _anc_cols if c not in _grp0 and c not in _grp1]

fig, axes = plt.subplots(2, 1, figsize=(16, 7), sharex=True)
for col in _grp0:
    axes[0].plot(anc_wide['ts_utc'], anc_wide[col].clip(upper=3000),
                 lw=0.3, alpha=0.7, label=col.replace('mcpc_', '').upper(),
                 color=_anc_colors.get(col, 'gray'))
axes[0].set_title('NP4-188-CD — Ancillary MCPC $/MW: ' + ', '.join(c.replace('mcpc_','').upper() for c in _grp0) + ' (clipped at 3000)')
axes[0].set_ylabel('$/MW')
axes[0].legend(fontsize=8)

for col in _grp1:
    axes[1].plot(anc_wide['ts_utc'], anc_wide[col].clip(upper=3000),
                 lw=0.3, alpha=0.7, label=col.replace('mcpc_', '').upper(),
                 color=_anc_colors.get(col, 'gray'))
axes[1].set_title('NP4-188-CD — Ancillary MCPC $/MW: ' + ', '.join(c.replace('mcpc_','').upper() for c in _grp1) + ' (clipped at 3000)')
axes[1].set_ylabel('$/MW')
axes[1].legend(fontsize=8)

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/972774116.py:39: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### ℹ️ Structural Note — NP4-188-CD: 19,632 rows with horizon > 36h (November tail, D+2)

Same structural pattern as NP4-523-CD. In **November files only** (2017–2025, except 2020), end-of-month DAM publications cover December delivery dates, pushing horizons beyond 36h.

| Field | Value |
|---|---|
| Affected rows | 19,632 |
| horizon_h range | ~36.1–58.9h |
| Unique postDateTimes | ~194 (23–29 per November) |
| Affected files | `NP4-188-CD/<year>/11/` for 2017–2025 (except 2020) |
| Ancillary types | All four types affected equally |

**Assessment**: Structurally valid D+2 postings, not data corruption. Same cause as NP4-523-CD — end-of-November DAM covers first days of December delivery. No action required.

### NP3-233-CD — Hourly Resource Outage Capacity (total + IRR)

Schema changed at 2021-06: system-total columns dropped, zone-level columns added.

| Period | Source columns | Output columns |
|---|---|---|
| 2017-07 – 2021-05 | `TotalResourceMW`, `TotalIRRMW` (direct) | `total_*` only; `houston_*` = NaN |
| 2021-06 – 2025-12 | Sum of 4 zone cols | `total_*` reconstructed |
| 2021-05 – 2025-12 | `TotalResourceMWZoneHouston`, `TotalIRRMWZoneHouston` | `houston_*` filled |

No `DSTFlag`. Rolling-actual: keep latest `postDateTime` per (Date, HourEnding) slot.  
Single output `gen`: `ts_utc, total_resource_mw, total_irr_mw, re_share, houston_resource_mw, houston_irr_mw, houston_re_share`.

In [29]:

# ── System total: full range 2017-07 to 2025-12 ──────────────────────────────
ZONE_RES = ['TotalResourceMWZoneSouth', 'TotalResourceMWZoneNorth',
            'TotalResourceMWZoneWest',  'TotalResourceMWZoneHouston']
ZONE_IRR = ['TotalIRRMWZoneSouth', 'TotalIRRMWZoneNorth',
            'TotalIRRMWZoneWest',  'TotalIRRMWZoneHouston']

_sys_a = read_monthly_csvs(
    'NP3-233-CD',
    usecols=['postDateTime', 'Date', 'HourEnding', 'TotalResourceMW', 'TotalIRRMW'],
    from_year=2017, from_month=7, to_year=2021, to_month=5,
).rename(columns={'TotalResourceMW': 'total_resource_mw', 'TotalIRRMW': 'total_irr_mw'})
for _c in ['total_resource_mw', 'total_irr_mw']:
    _sys_a[_c] = pd.to_numeric(_sys_a[_c], errors='coerce')

_sys_b = read_monthly_csvs(
    'NP3-233-CD',
    usecols=['postDateTime', 'Date', 'HourEnding'] + ZONE_RES + ZONE_IRR,
    from_year=2021, from_month=6, to_year=2025,
)
for _c in ZONE_RES + ZONE_IRR:
    _sys_b[_c] = pd.to_numeric(_sys_b[_c], errors='coerce')
_sys_b['total_resource_mw'] = _sys_b[ZONE_RES].sum(axis=1)
_sys_b['total_irr_mw']      = _sys_b[ZONE_IRR].sum(axis=1)

# ── gen_all: multi-horizon data, used for D+1 + revision std features ─────────
# Build before drop_duplicates so all postings per delivery slot are preserved.
# No DSTFlag in NP3-233-CD — ts_utc is local time (CST naive), consistent with postDateTime.
_sys_all_raw = pd.concat([
    _sys_a[['postDateTime', 'Date', 'HourEnding', 'total_resource_mw', 'total_irr_mw']],
    _sys_b[['postDateTime', 'Date', 'HourEnding', 'total_resource_mw', 'total_irr_mw']],
], ignore_index=True)
_sys_all_raw['postDateTime'] = pd.to_datetime(_sys_all_raw['postDateTime'])
_he_g       = pd.to_numeric(_sys_all_raw['HourEnding'], errors='coerce')
_del_date_g = pd.to_datetime(_sys_all_raw['Date'], format='%m/%d/%Y', errors='coerce')
_sys_all_raw['ts_utc']     = _del_date_g + pd.to_timedelta(_he_g - 1, unit='h')
_post_floor_g              = _sys_all_raw['postDateTime'].dt.floor('h')
_sys_all_raw['horizon_h']  = ((_sys_all_raw['ts_utc'] - _post_floor_g).dt.total_seconds() / 3600).astype('Int64')
_post_date_g               = _sys_all_raw['postDateTime'].dt.normalize()
_sys_all_raw['days_ahead'] = (_del_date_g - _post_date_g).dt.days

gen_all = (
    _sys_all_raw[['ts_utc', 'horizon_h', 'days_ahead', 'total_resource_mw', 'total_irr_mw']]
    .drop_duplicates(subset=['ts_utc', 'horizon_h', 'days_ahead'])
    .sort_values(['ts_utc', 'horizon_h'])
    .reset_index(drop=True)
)

# ── gen: single row per delivery slot (latest posting = actual scheduled capacity)
_sys_all = _sys_all_raw.sort_values('postDateTime').drop_duplicates(subset=['Date', 'HourEnding'], keep='last')
_he = pd.to_numeric(_sys_all['HourEnding'], errors='coerce')
_sys_all['ts_utc']   = pd.to_datetime(_sys_all['Date'], format='%m/%d/%Y', errors='coerce') + pd.to_timedelta(_he - 1, unit='h')
_sys_all['re_share'] = _sys_all['total_irr_mw'] / _sys_all['total_resource_mw']
_sys_all = (
    _sys_all[['ts_utc', 'total_resource_mw', 'total_irr_mw', 're_share']]
    .sort_values('ts_utc').reset_index(drop=True)
)

# ── Houston zone: 2021-05 to 2025-12 ─────────────────────────────────────────
_hou_raw = read_monthly_csvs(
    'NP3-233-CD',
    from_year=2021, from_month=5, to_year=2025,
)
_hou = _hou_raw.copy()
_hou['postDateTime']        = pd.to_datetime(_hou['postDateTime'])
_hou['houston_resource_mw'] = pd.to_numeric(_hou['TotalResourceMWZoneHouston'], errors='coerce')
_hou['houston_irr_mw']      = pd.to_numeric(_hou['TotalIRRMWZoneHouston'],      errors='coerce')
_hou = _hou.sort_values('postDateTime').drop_duplicates(subset=['Date', 'HourEnding'], keep='last')
_he = pd.to_numeric(_hou['HourEnding'], errors='coerce')
_hou['ts_utc'] = (
    pd.to_datetime(_hou['Date'], format='%m/%d/%Y', errors='coerce')
    + pd.to_timedelta(_he - 1, unit='h')
)
_hou['houston_re_share'] = _hou['houston_irr_mw'] / _hou['houston_resource_mw']
_hou = (
    _hou[['ts_utc', 'houston_resource_mw', 'houston_irr_mw', 'houston_re_share']]
    .sort_values('ts_utc').reset_index(drop=True)
)

# ── Merge: system total (full range) + Houston zone (2021-05+) ────────────────
gen = (
    _sys_all.merge(_hou, on='ts_utc', how='left')
    .sort_values('ts_utc').reset_index(drop=True)
)

dataset_summary(gen, 'NP3-233-CD — Generation: system total (full) + Houston zone (2021-05+)')
print(f'gen_all: {len(gen_all):,} rows  |  horizon_h: {gen_all.horizon_h.min()} → {gen_all.horizon_h.max()} h')
print(f'  days_ahead: {gen_all.days_ahead.min()} → {gen_all.days_ahead.max()}')

────────────────────────────────────────────────────────────
NP3-233-CD — Generation: system total (full) + Houston zone (2021-05+)
  74,711 rows  ×  7 cols
  range : 2017-07-01 00:00:00  →  2026-01-07 22:00:00

  columns:
    ts_utc                              datetime64[us]
    total_resource_mw                   float64
    total_irr_mw                        float64
    re_share                            float64
    houston_resource_mw                 float64
    houston_irr_mw                      float64
    houston_re_share                    float64

  nulls :
    total_resource_mw: 0.14%
    total_irr_mw: 0.14%
    re_share: 0.14%
    houston_resource_mw: 45.83%
    houston_irr_mw: 45.83%
    houston_re_share: 45.83%

,total_resource_mw,total_irr_mw,re_share,houston_resource_mw,houston_irr_mw,houston_re_share
count,74608.000,74608.000,74608.000,40470.000,40470.000,40470.000
mean,13647.943,3871.449,0.382,3252.128,295.611,0.110
std,7494.582,1829.747,0.274,1623.261,207.356,0.098
min,1692.000,1109.000,0.045,428.000,-7.000,-0.004
5%,4420.000,1629.000,0.095,1025.000,0.000,0.000
25%,7211.000,2477.000,0.191,1877.000,152.000,0.040
50%,11479.000,3707.000,0.279,2972.000,277.000,0.089
75%,19973.250,4959.000,0.509,4492.000,421.000,0.158
95%,26957.300,6608.650,0.929,6102.000,665.000,0.279
max,34750.000,22567.000,2.621,8561.000,1239.000,1.326

  head:

,ts_utc,total_resource_mw,total_irr_mw,re_share,houston_resource_mw,houston_irr_mw,houston_re_share
0,2017-07-01 00:00:00,9895.0,1935.0,0.195553,NaN,NaN,NaN
1,2017-07-01 01:00:00,9895.0,1937.0,0.195755,NaN,NaN,NaN
2,2017-07-01 02:00:00,9895.0,1937.0,0.195755,NaN,NaN,NaN
3,2017-07-01 03:00:00,9895.0,1939.0,0.195958,NaN,NaN,NaN
4,2017-07-01 04:00:00,9895.0,1939.0,0.195958,NaN,NaN,NaN

gen_all: 13,472,091 rows  |  horizon_h: -25 → 190 h
  days_ahead: -2 → 7

In [30]:

# ── NP3-233-CD: 6PM D-1 snapshot + 48h revision std ─────────────────────────
# Same 6PM/48h window logic as NP3-565-CD.
# Total system only (Houston zone starts 2021-05; excluded to avoid NaN block).

_GEN_COLS = ['total_resource_mw', 'total_irr_mw']

_del_date_g = gen_all['ts_utc'].dt.normalize()
_cutoff_g   = _del_date_g - pd.Timedelta(days=1) + pd.Timedelta(hours=18)
_h_min_g    = (gen_all['ts_utc'] - _cutoff_g).dt.total_seconds() / 3600
_h_max_g    = _h_min_g + 48

gfc_window = gen_all[
    (gen_all['horizon_h'] >= _h_min_g) &
    (gen_all['horizon_h'] <= _h_max_g)
].copy()

# Point estimate: min horizon_h per delivery slot = latest posting ≤ 6PM
gen_d1 = (
    gfc_window.loc[gfc_window.groupby('ts_utc')['horizon_h'].idxmin()]
    .drop(columns='days_ahead')
    .sort_values('ts_utc')
    .reset_index(drop=True)
)

# Revision std over 48h window (ddof=1)
_grev_std = (
    gfc_window.groupby('ts_utc')[_GEN_COLS]
    .std(ddof=1)
    .rename(columns={c: f'{c}_std_48h' for c in _GEN_COLS})
    .reset_index()
)

# Combined output with genf_ prefix for master merge
gen_f1 = (
    gen_d1[['ts_utc', 'horizon_h'] + _GEN_COLS]
    .merge(_grev_std, on='ts_utc', how='left')
    .rename(columns=lambda c: c if c == 'ts_utc' else
                              'genf_horizon_h' if c == 'horizon_h' else
                              f'genf_{c}')
)

print(f'gfc_window : {len(gfc_window):,} rows  '
      f'(avg {len(gfc_window) / max(gen_d1.ts_utc.nunique(), 1):.1f} snapshots/slot)')
print(f'gen_d1    : {len(gen_d1):,} rows')
print(f'  genf_horizon_h range: {gen_d1.horizon_h.min()} – {gen_d1.horizon_h.max()} h')
print(f'gen_f1    : {len(gen_f1):,} rows, {gen_f1.shape[1]} columns')
print(f'  std_48h (total_resource_mw): median={_grev_std.total_resource_mw_std_48h.median():.1f} MW, '
      f'max={_grev_std.total_resource_mw_std_48h.max():.1f} MW')

# Free memory — raw multi-horizon data no longer needed after this point.
del gen_all, _sys_all_raw, gfc_window

gfc_window : 3,651,000 rows  (avg 48.9 snapshots/slot)
gen_d1    : 74,592 rows
  genf_horizon_h range: 6 – 72 h
gen_f1    : 74,592 rows, 6 columns
  std_48h (total_resource_mw): median=469.1 MW, max=3204.3 MW

#### NP3-233-CD Horizon Exploration — Dec 2024 Sample

Total generation capacity (`TotalResourceMWZoneHouston`) by lead time. Each postDateTime publishes a ~7-day rolling window; ~156 updates per delivery hour.  
Plot 1 overlays selected horizons over a week. Plot 2 shows revision for a single delivery day.

In [31]:
# ── Load Dec 2024, TotalResourceMWZoneHouston ──────────────────────────────
_path233 = 'data/raw/ercot/NP3-233-CD/2024/12/NP3-233-CD_202412.csv'
_raw233 = pd.read_csv(_path233, usecols=[
    'postDateTime', 'Date', 'HourEnding', 'TotalResourceMWZoneHouston'
])
_df233 = _raw233.copy()
_df233['TotalResourceMWZoneHouston'] = pd.to_numeric(_df233['TotalResourceMWZoneHouston'], errors='coerce')

# HourEnding=24 → hour 23 of same day (23:00–00:00)
_he233 = _df233['HourEnding'].astype(int)
_df233['del_dt'] = (
    pd.to_datetime(_df233['Date'], format='%m/%d/%Y')
    + pd.to_timedelta(_he233 - 1, unit='h')
)

# Horizon (floor post to hour)
_df233['post_floor'] = pd.to_datetime(_df233['postDateTime'].str[:19]).dt.floor('h')
_df233['horizon_h'] = ((_df233['del_dt'] - _df233['post_floor']).dt.total_seconds() / 3600).round().astype('Int64')

_df233 = _df233[(_df233['horizon_h'] >= 0) & (_df233['horizon_h'] <= 172)].copy()

print(f"NP3-233-CD Dec 2024: {len(_df233):,} rows (valid horizons)")
print(f"Horizon range: {_df233['horizon_h'].min()} → {_df233['horizon_h'].max()} h")

# ── Plot 1: week overlay ────────────────────────────────────────────────────
HORIZONS = [2, 6, 12, 24, 48, 72, 120, 168]
_week233 = _df233[(_df233['del_dt'] >= '2024-12-08') & (_df233['del_dt'] < '2024-12-15')]

fig, ax = plt.subplots(figsize=(14, 5))
colors = plt.cm.plasma_r(np.linspace(0.1, 0.9, len(HORIZONS)))

for h, c in zip(HORIZONS, colors):
    sub = _week233[_week233['horizon_h'] == h].sort_values('del_dt')
    if not sub.empty:
        ax.plot(sub['del_dt'], sub['TotalResourceMWZoneHouston'], label=f'{h}h ahead', color=c, lw=1.5, alpha=0.85)

ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
ax.xaxis.set_major_locator(mdates.DayLocator())
ax.set_xlabel('Delivery hour')
ax.set_ylabel('TotalResourceMW Houston Zone (MW)')
ax.set_title('NP3-233-CD — Houston generation capacity by lead time, Dec 8–14 2024')
ax.legend(title='Lead time', bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# ── Plot 2: forecast revision for Dec 10 ───────────────────────────────────
_day233 = _df233[_df233['del_dt'].dt.date == pd.Timestamp('2024-12-10').date()].copy()
_pivot233 = (
    _day233.groupby(['horizon_h', 'del_dt'])['TotalResourceMWZoneHouston']
    .mean().unstack('del_dt')
)

fig, ax = plt.subplots(figsize=(14, 5))
for col in _pivot233.columns:
    ax.plot(_pivot233.index, _pivot233[col], lw=1.0, alpha=0.6, label=col.strftime('%H:00'))

ax.invert_xaxis()
ax.set_xlabel('Horizon (hours before delivery) — right = closer to delivery')
ax.set_ylabel('TotalResourceMW Houston Zone (MW)')
ax.set_title('NP3-233-CD — Capacity revision for Dec 10 2024 (each line = one delivery hour)')
ax.axvline(24, color='red',    ls='--', lw=1, label='24h-ahead')
ax.axvline(2,  color='orange', ls='--', lw=1, label='2h-ahead')
ax.legend(title='Delivery hour', bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=7, ncol=2)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

NP3-233-CD Dec 2024: 128,247 rows (valid horizons)
Horizon range: 0 → 172 h

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/1447104365.py:45: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/1447104365.py:67: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Full-history overview: total resource capacity (gray, left axis) overlaid with renewable energy share % (green, right axis). RE share = (wind + solar + hydro) / total, computed from within the same source file. Houston-zone data is available from 2021-05 onward following ERCOT's zone-level reporting expansion.

In [32]:
fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)

# Top: system total generation + RE share
ax0b = axes[0].twinx()
axes[0].plot(gen['ts_utc'], gen['total_resource_mw'], lw=0.25, color='gray', alpha=0.6, label='System gen (MW)')
ax0b.plot(gen['ts_utc'], gen['re_share'] * 100, lw=0.3, color='mediumseagreen', alpha=0.8, label='RE share %')
axes[0].set_title('NP3-233-CD — System total generation (MW) and renewable share (%)')
axes[0].set_ylabel('MW', color='gray')
ax0b.set_ylabel('RE share (%)', color='mediumseagreen')
lines0, labs0 = axes[0].get_legend_handles_labels()
lines0b, labs0b = ax0b.get_legend_handles_labels()
axes[0].legend(lines0 + lines0b, labs0 + labs0b, fontsize=8, loc='upper left')

# Middle: Houston zone generation + RE share (data from 2021-05+)
ax1b = axes[1].twinx()
axes[1].plot(gen['ts_utc'], gen['houston_resource_mw'], lw=0.25, color='gray', alpha=0.6, label='Houston gen (MW)')
ax1b.plot(gen['ts_utc'], gen['houston_re_share'] * 100, lw=0.3, color='mediumseagreen', alpha=0.8, label='RE share %')
axes[1].set_title('NP3-233-CD — Houston generation (MW) and renewable share (%) [zone data from 2021-05+]')
axes[1].set_ylabel('MW', color='gray')
ax1b.set_ylabel('RE share (%)', color='mediumseagreen')
lines1, labs1 = axes[1].get_legend_handles_labels()
lines1b, labs1b = ax1b.get_legend_handles_labels()
axes[1].legend(lines1 + lines1b, labs1 + labs1b, fontsize=8, loc='upper left')

# Bottom: Houston / total ratio
axes[2].plot(gen['ts_utc'], gen['houston_resource_mw'] / gen['total_resource_mw'], lw=0.3, color='darkorange', alpha=0.8)
axes[2].set_title('NP3-233-CD — Houston / total generation ratio [zone data from 2021-05+]')
axes[2].set_ylabel('ratio')

for _ax in axes:
    _ax.xaxis.set_major_locator(mdates.YearLocator())
    _ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    _ax.tick_params(axis='x', rotation=30, labelsize=8)
    _ax.grid(axis='x', alpha=0.25, linestyle='--')
    _ax.grid(axis='y', alpha=0.2)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3256249372.py:37: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### Weather Station Data (hourly)

Four ASOS stations covering the main ERCOT load/pricing regions:

| Code | City | Region |
|------|------|--------|
| KIAH | Houston | Houston |
| KAUS | Austin | Austin |
| KDFW | Dallas | DFW |
| KSAT | San Antonio | San Antonio |

Source: Open-Meteo API via `scripts/houston_weather.py`.
Files: `WEATHER_ROOT/<STATION>_<YYYY-MM>.csv` (one per station-month).

**Timestamp**: `datetime` is local `America/Chicago` time (start-of-hour).
Converted to fixed UTC-6 (`ts_utc`) to align with ERCOT datasets — the same convention used throughout this notebook.

In [33]:
WEATHER_STATIONS = ['Houston_avg', 'Houston_stdev', 'Texas_avg', 'Texas_stdev']

def read_weather_csvs(chunksize: int = 200_000) -> pd.DataFrame:
    """Load all weather CSV files from WEATHER_ROOT, reading in chunks."""
    files = sorted(WEATHER_ROOT.glob('*.csv'))
    if not files:
        raise FileNotFoundError(f'No weather files in {WEATHER_ROOT}')
    chunks = []
    for f in files:
        for chunk in pd.read_csv(f, chunksize=chunksize):
            chunks.append(chunk)
    return pd.concat(chunks, ignore_index=True)

_df_weather = read_weather_csvs()

# Treat datetime as fixed CST (UTC-6) — no DST conversion.
_df_weather['ts_utc'] = pd.to_datetime(_df_weather['datetime'])

WEATHER_COLS = [
    'ts_utc', 'station_code', 'city',
    'temp_f', 'dew_point_f', 'humidity_pct', 'precip_in',
    'wind_speed_mph', 'wind_gust_mph', 'pressure_hpa',
]

weather = (
    _df_weather.drop(columns=['datetime'])
    [[c for c in WEATHER_COLS if c in _df_weather.columns]]
    .sort_values(['station_code', 'ts_utc'])
    .reset_index(drop=True)
)

dataset_summary(weather, 'Weather Stations (all)')

────────────────────────────────────────────────────────────
Weather Stations (all)
  2,976 rows  ×  10 cols
  range : 2025-12-01 00:00:00  →  2025-12-31 23:00:00

  columns:
    ts_utc                              datetime64[us]
    station_code                        str
    city                                str
    temp_f                              float64
    dew_point_f                         float64
    humidity_pct                        int64
    precip_in                           float64
    wind_speed_mph                      float64
    wind_gust_mph                       float64
    pressure_hpa                        float64

  nulls : none

,temp_f,dew_point_f,humidity_pct,precip_in,wind_speed_mph,wind_gust_mph,pressure_hpa
count,2976.000,2976.000,2976.000,2976.000,2976.000,2976.000,2976.000
mean,56.146,45.680,71.115,0.001,6.210,13.636,1002.248
std,11.912,15.099,20.806,0.010,3.145,6.467,10.989
min,28.100,11.700,14.000,0.000,0.100,0.900,981.100
5%,37.975,20.500,32.000,0.000,1.800,4.900,986.975
25%,46.175,33.575,56.000,0.000,3.900,8.900,993.800
50%,55.900,44.400,74.000,0.000,5.800,12.500,1000.100
75%,66.100,60.600,88.000,0.000,8.000,17.200,1011.700
95%,75.700,66.700,99.000,0.004,12.000,26.400,1021.000
max,83.100,70.600,100.000,0.276,19.900,41.400,1031.100

  station_code  (4 unique):

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3091357164.py:107: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

              count
station_code
KAUS            744
KDFW            744
KIAH            744
KSAT            744

  city  (4 unique):

             count
city
Austin         744
Dallas         744
Houston        744
San Antonio    744

  head:

,ts_utc,station_code,city,temp_f,dew_point_f,humidity_pct,precip_in,wind_speed_mph,wind_gust_mph,pressure_hpa
0,2025-12-01 00:00:00,KAUS,Austin,44.8,29.3,54,0.0,8.6,17.2,1006.6
1,2025-12-01 01:00:00,KAUS,Austin,44.2,30.0,57,0.0,8.4,16.8,1005.6
2,2025-12-01 02:00:00,KAUS,Austin,43.6,30.9,61,0.0,8.1,16.6,1005.3
3,2025-12-01 03:00:00,KAUS,Austin,42.8,32.2,66,0.0,8.1,17.2,1004.5
4,2025-12-01 04:00:00,KAUS,Austin,42.6,32.8,68,0.0,6.4,16.1,1004.3

In [34]:
# ── Weather DST transition snapshots ─────────────────────────────────────────
# Spring-forward 2019-03-10: 2:00 AM CST does not exist → source row becomes NaT
#   (CDT 3:00 AM = 08:00 UTC = 02:00 UTC-6, so no gap in ts_utc)
# Fall-back 2019-11-03: 1:00 AM appears twice in source; ambiguous=False → both
#   treated as CST (07:00 UTC = 01:00 UTC-6) → duplicate at 01:00, gap at 00:00

_sp_date = '2019-03-10'
_fb_date = '2019-11-03'

for _code in WEATHER_STATIONS:
    _w = weather[weather['station_code'] == _code].copy().reset_index(drop=True)

    print(f'\n{"━"*64}')
    print(f'  {_code}')

    _sp_idx = _w['ts_utc'].searchsorted(pd.Timestamp(f'{_sp_date} 00:00'))
    _sp = _w.iloc[max(0, _sp_idx - 1): _sp_idx + 8].reset_index(drop=True)
    print(f'\n  Spring-forward {_sp_date}  (NaT row sorted to end; CDT 03:00 → 02:00 UTC-6):')
    display(_sp)

    _fb_idx = _w['ts_utc'].searchsorted(pd.Timestamp(f'{_fb_date} 00:00'))
    _fb = _w.iloc[max(0, _fb_idx - 1): _fb_idx + 8].reset_index(drop=True)
    print(f'\n  Fall-back {_fb_date}  (ambiguous=False → CST; expect gap at 00:00, duplicate at 01:00):')
    display(_fb)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Houston_avg

  Spring-forward 2019-03-10  (NaT row sorted to end; CDT 03:00 → 02:00 UTC-6):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

  Fall-back 2019-11-03  (ambiguous=False → CST; expect gap at 00:00, duplicate at 01:00):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Houston_stdev

  Spring-forward 2019-03-10  (NaT row sorted to end; CDT 03:00 → 02:00 UTC-6):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

  Fall-back 2019-11-03  (ambiguous=False → CST; expect gap at 00:00, duplicate at 01:00):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Texas_avg

  Spring-forward 2019-03-10  (NaT row sorted to end; CDT 03:00 → 02:00 UTC-6):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

  Fall-back 2019-11-03  (ambiguous=False → CST; expect gap at 00:00, duplicate at 01:00):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Texas_stdev

  Spring-forward 2019-03-10  (NaT row sorted to end; CDT 03:00 → 02:00 UTC-6):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

  Fall-back 2019-11-03  (ambiguous=False → CST; expect gap at 00:00, duplicate at 01:00):

Empty DataFrame
Columns: [ts_utc, station_code, city, temp_f, dew_point_f, humidity_pct, precip_in, wind_speed_mph, wind_gust_mph, pressure_hpa]
Index: []

In [35]:
# ── Weather station time series: temperature and dew point by station ─────────
# Data: `weather` (long format, one row per station-hour)
# Columns used: ts_utc, station_code, city, temp_f, dew_point_f, wind_speed_mph

_wx_vars = [
    ('temp_f',        'Temperature (°F)',    'tab:red'),
    ('dew_point_f',   'Dew Point (°F)',      'tab:blue'),
    ('wind_speed_mph','Wind Speed (mph)',     'tab:green'),
]

_station_meta = (
    weather[['station_code', 'city']]
    .drop_duplicates()
    .sort_values('station_code')
)
_stations  = _station_meta['station_code'].tolist()
_city_map  = dict(zip(_station_meta['station_code'], _station_meta['city']))
_n_vars    = len(_wx_vars)
_colors    = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']  # one per station

fig, axes = plt.subplots(_n_vars, 1, figsize=(14, 8), sharex=True)
fig.suptitle('Weather Station Time Series — Temperature, Dew Point, Wind Speed', fontsize=13)

for ax, (col, ylabel, _) in zip(axes, _wx_vars):
    for code, color in zip(_stations, _colors):
        sub = weather[weather['station_code'] == code].sort_values('ts_utc')
        if col not in sub.columns or sub[col].isna().all():
            continue
        # Downsample to daily mean for readability over multi-year span
        daily = sub.set_index('ts_utc')[col].resample('D').mean()
        ax.plot(daily.index, daily.values,
                lw=0.8, alpha=0.75, color=color,
                label=f'{code} ({_city_map.get(code, code)})')
    ax.set_ylabel(ylabel, fontsize=10)
    ax.legend(fontsize=8, ncol=len(_stations), loc='upper right')
    ax.grid(axis='x', alpha=0.25, linestyle='--')
    ax.grid(axis='y', alpha=0.2)
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    ax.tick_params(axis='x', rotation=30, labelsize=8)

axes[-1].set_xlabel('Date (UTC-6)', fontsize=10)
plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/477484032.py:44: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 4. Validation

Cross-dataset checks: coverage, interval regularity, missing-slot heatmap,
and full-period time-series overview.  
DST transition correctness is verified centrally in §2.1.

In [36]:
def coverage_report(df: pd.DataFrame, ts_col: str, label: str, freq: str = 'h') -> None:
    ts = df[ts_col].dropna().sort_values()
    if ts.empty:
        print(f'{label}: empty')
        return
    full_idx = pd.date_range(ts.min(), ts.max(), freq=freq)
    missing = full_idx.difference(ts)
    pct = len(missing) / len(full_idx) * 100
    print(f'{label}: {len(ts):>10,} rows | expected {len(full_idx):>10,} | '
          f'gaps {len(missing):>6,} ({pct:.2f}%)')

print('Coverage (unique ts_utc vs full expected range):')
coverage_report(load346,  'ts_utc', 'NP6-346-CD load')
coverage_report(load345,  'ts_utc', 'NP6-345-CD load')
coverage_report(wind,     'ts_utc', 'NP4-732-CD wind')
coverage_report(lam,      'ts_utc', 'NP4-523-CD lambda')
coverage_report(gen,      'ts_utc', 'NP3-233-CD gen')
coverage_report(anc_wide, 'ts_utc', 'NP4-188-CD anc')

# DAM is wide (one row per ts_utc) — report once
print()
coverage_report(dam, 'ts_utc', 'NP4-190-CD DAM (wide: houston+avg)')

# RTM (905): per hub (HB_HOUSTON + HB_BUSAVG only)
for hub in HUBS_RTM:
    coverage_report(rtm905_hourly[rtm905_hourly['hub'] == hub], 'ts_utc', f'NP6-905-CD RTM   {hub}')

# NP3-565-CD: fc565 (multi-horizon) deleted after D+1 extraction — check fc565_f1 (D+1 snapshot)
print()
coverage_report(fc565_f1, 'ts_utc', 'NP3-565-CD  D+1 forecast (fc565_f1)')

# NP6-905-CD: raw 15-min coverage (HB_HOUSTON)
print()
coverage_report(rtm905[rtm905['hub'] == 'HB_HOUSTON'],
                'ts_utc', 'NP6-905-CD RTM  HB_HOUSTON (15-min raw)', freq='15min')

Coverage (unique ts_utc vs full expected range):
NP6-346-CD load:     74,521 rows | expected     74,545 | gaps     24 (0.03%)
NP6-345-CD load:     74,521 rows | expected     74,545 | gaps     24 (0.03%)
NP4-732-CD wind:     74,760 rows | expected     74,760 | gaps      0 (0.00%)
NP4-523-CD lambda:     74,545 rows | expected     74,545 | gaps      0 (0.00%)
NP3-233-CD gen:     74,711 rows | expected     74,711 | gaps      0 (0.00%)
NP4-188-CD anc:     74,545 rows | expected     74,545 | gaps      0 (0.00%)

NP4-190-CD DAM (wide: houston+avg):     73,889 rows | expected     74,545 | gaps    656 (0.88%)
NP6-905-CD RTM   HB_HOUSTON:     74,546 rows | expected     74,546 | gaps      0 (0.00%)
NP6-905-CD RTM   HB_BUSAVG:     74,546 rows | expected     74,546 | gaps      0 (0.00%)

NP3-565-CD  D+1 forecast (fc565_f1):     74,592 rows | expected     74,592 | gaps      0 (0.00%)

NP6-905-CD RTM  HB_HOUSTON (15-min raw):    298,177 rows | expected    298,180 | gaps      3 (0.00%)

#### 4.2 Interval Regularity

Verifies that consecutive timestamps are exactly 1 h (or 15 min) apart. An irregular gap indicates a missing delivery slot; a gap smaller than expected points to a duplicate row that survived deduplication.

In [37]:
# ── Interval frequency check ──────────────────────────────────────────────────
# Verifies consecutive timestamp gaps match the expected interval.
# Gaps larger than 1h (or 15min) indicate missing delivery slots.

def interval_check(df, ts_col, label, expected_td):
    ts = df[ts_col].dropna().sort_values().drop_duplicates().reset_index(drop=True)
    diffs = ts.diff().dropna()
    n_ok  = (diffs == expected_td).sum()
    n_bad = (diffs != expected_td).sum()
    print(f'  {label:<55}  regular={n_ok:,}  irregular={n_bad}', end='')
    if n_bad:
        top = diffs[diffs != expected_td].value_counts().head(3)
        print(f'  top gaps: {top.to_dict()}')
    else:
        print()

h1  = pd.Timedelta(hours=1)
m15 = pd.Timedelta(minutes=15)

print('Interval check (consecutive timestamp gaps):')
interval_check(load346, 'ts_utc', 'NP6-346-CD load (1h)',        h1)
interval_check(load345, 'ts_utc', 'NP6-345-CD load (1h)',        h1)
interval_check(wind,    'ts_utc', 'NP4-732-CD wind (1h)',         h1)
interval_check(lam,     'ts_utc', 'NP4-523-CD lambda (1h)',       h1)
interval_check(gen,     'ts_utc', 'NP3-233-CD gen (1h)',          h1)
# dam is wide (one row per ts_utc) — check directly, no hub loop needed
interval_check(dam,     'ts_utc', 'NP4-190-CD DAM (1h)',          h1)
for hub in HUBS_RTM:
    interval_check(rtm905[rtm905['hub'] == hub].sort_values('ts_utc'),
                   'ts_utc', f'NP6-905-CD RTM {hub} (15min)', m15)

# Verify RTM 905 has exactly 4 intervals per (hour, hub)
print('\nRTM 905 — intervals per (hour, hub) value_counts:')
counts = (rtm905.assign(ts_hour=rtm905['ts_utc'].dt.floor('h'))
                .groupby(['ts_hour', 'hub'])['ts_utc'].count()
                .value_counts().sort_index()
                .rename('n_(hour,hub) pairs'))
print(counts.to_string())
print('  (4 = normal; 3 = spring-forward hour; 5 = possible fall-back overlap)')

Interval check (consecutive timestamp gaps):
  NP6-346-CD load (1h)                                     regular=74,519  irregular=1  top gaps: {Timedelta('1 days 01:00:00'): 1}
  NP6-345-CD load (1h)                                     regular=74,519  irregular=1  top gaps: {Timedelta('1 days 01:00:00'): 1}
  NP4-732-CD wind (1h)                                     regular=74,759  irregular=0
  NP4-523-CD lambda (1h)                                   regular=74,544  irregular=0
  NP3-233-CD gen (1h)                                      regular=74,710  irregular=0
  NP4-190-CD DAM (1h)                                      regular=73,855  irregular=33  top gaps: {Timedelta('1 days 01:00:00'): 5, Timedelta('0 days 02:00:00'): 4, Timedelta('2 days 01:00:00'): 4}
  NP6-905-CD RTM HB_HOUSTON (15min)                        regular=298,174  irregular=2  top gaps: {Timedelta('0 days 00:45:00'): 1, Timedelta('0 days 00:30:00'): 1}
  NP6-905-CD RTM HB_BUSAVG (15min)                         regular=298,174  irregular=2  top gaps: {Timedelta('0 days 00:45:00'): 1, Timedelta('0 days 00:30:00'): 1}

RTM 905 — intervals per (hour, hub) value_counts:
ts_utc
1         2
3         8
4    149082
  (4 = normal; 3 = spring-forward hour; 5 = possible fall-back overlap)

#### 4.3 Missing-Slot Heatmap

Aggregates missing slots by calendar month. Clusters of missing months reveal systematic outages or backfill gaps; isolated red bars flag one-off data quality issues worth investigating before modelling.

In [38]:
# ── Missing-slot heatmap: gaps by year-month ──────────────────────────────────

def missing_yearmonth(df, ts_col, freq='h'):
    ts = df[ts_col].dropna().sort_values()
    if ts.empty:
        return pd.Series(dtype=float)
    full_idx = pd.date_range(ts.min(), ts.max(), freq=freq)
    missing_ts = full_idx.difference(ts)
    if len(missing_ts) == 0:
        return pd.Series(dtype=float)
    return (pd.Series(missing_ts.to_period('M').astype(str))
            .value_counts().sort_index().rename('missing'))

check_list = [
    (load346,                                            'ts_utc', 'NP6-346-CD load',             'h'),
    (lam,                                                'ts_utc', 'NP4-523-CD lambda',           'h'),
    (gen,                                                'ts_utc', 'NP3-233-CD gen',              'h'),
    (dam,                                                'ts_utc', 'NP4-190-CD DAM (wide)',        'h'),
    (rtm905_hourly[rtm905_hourly['hub']=='HB_HOUSTON'],  'ts_utc', 'NP6-905-CD RTM HB_HOUSTON',   'h'),
    (rtm905[rtm905['hub'] == 'HB_HOUSTON'],              'ts_utc', 'NP6-905-CD RTM 15-min',       '15min'),
]

fig, axes = plt.subplots(len(check_list), 1, figsize=(16, 3 * len(check_list)), sharex=False)
fig.suptitle('Missing slots by year-month', fontsize=13, y=1.01)

any_gaps = False
for ax, (df, ts_col, label, freq) in zip(axes, check_list):
    by_ym = missing_yearmonth(df, ts_col, freq)
    if by_ym.empty:
        ax.text(0.5, 0.5, 'No gaps ✓', ha='center', va='center',
                transform=ax.transAxes, fontsize=13, color='green')
        ax.set_title(f'{label} — no missing slots')
    else:
        any_gaps = True
        by_ym.plot(kind='bar', ax=ax, color='salmon', width=0.85, legend=False)
        ax.set_title(f'{label} — missing {"hours" if freq == "h" else "15-min slots"}/month')
        ax.set_ylabel('Missing slots')
        ax.tick_params(axis='x', rotation=60, labelsize=7)
    ax.set_xlabel('')

plt.tight_layout()
plt.show()

if not any_gaps:
    print('All checked datasets: no missing slots ✓')

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/2231195990.py:42: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### 4.4 Exact Missing Timestamps

Lists the precise missing `ts_utc` values per dataset (up to 50; summarised beyond that). Use this alongside the heatmap above to identify specific hours that may need interpolation or exclusion before modelling.

In [39]:
# ── Missing ts_utc — exact timestamps per dataset ────────────────────────────
MAX_PRINT = 50   # list individual slots up to this many; summarise beyond

def missing_ts_report(df, ts_col, label, freq='h', max_print=MAX_PRINT):
    ts = df[ts_col].dropna().drop_duplicates().sort_values()
    if ts.empty:
        print(f'\n  {label}: no data')
        return
    full_idx = pd.date_range(ts.min(), ts.max(), freq=freq)
    missing = full_idx.difference(ts)
    n = len(missing)
    pct = n / len(full_idx) * 100
    if n == 0:
        print(f'  {label:<52}  ✓ no gaps')
        return
    print(f'\n  {label:<52}  {n:,} missing / {len(full_idx):,} ({pct:.3f}%)')
    for ts_val in missing[:max_print]:
        print(f'      {ts_val}')
    if n > max_print:
        print(f'      … {n - max_print:,} more')

print('Missing ts_utc slots (exact timestamps, up to 50 per dataset):')
print()

print('─ ERCOT hourly datasets ─────────────────────────────────────────────────')
missing_ts_report(load346,  'ts_utc', 'NP6-346-CD  load 4 zones')
missing_ts_report(load345,  'ts_utc', 'NP6-345-CD  load 8 zones')
missing_ts_report(lam,      'ts_utc', 'NP4-523-CD  system lambda')
missing_ts_report(anc_wide, 'ts_utc', 'NP4-188-CD  ancillary')
missing_ts_report(gen,      'ts_utc', 'NP3-233-CD  generation')
missing_ts_report(wind,     'ts_utc', 'NP4-732-CD  wind')

print()
print('─ NP4-190-CD DAM (wide: houston + avg) ─────────────────────────────────')
missing_ts_report(dam, 'ts_utc', 'NP4-190-CD  DAM (wide)')

print()
print('─ NP6-905-CD RTM hourly (per hub) ──────────────────────────────────────')
for hub in HUBS_RTM:
    missing_ts_report(rtm905_hourly[rtm905_hourly['hub'] == hub],
                      'ts_utc', f'NP6-905-CD  RTM hourly {hub}')

print()
print('─ NP6-905-CD RTM 15-min (HB_HOUSTON) ───────────────────────────────────')
missing_ts_report(rtm905[rtm905['hub'] == 'HB_HOUSTON'],
                  'ts_utc', 'NP6-905-CD  RTM 15-min HB_HOUSTON', freq='15min')

print()
print('─ Weather stations ──────────────────────────────────────────────────────')
for code in WEATHER_STATIONS:
    missing_ts_report(weather[weather['station_code'] == code],
                      'ts_utc', f'Weather  {code}')

Missing ts_utc slots (exact timestamps, up to 50 per dataset):

─ ERCOT hourly datasets ─────────────────────────────────────────────────

  NP6-346-CD  load 4 zones                              24 missing / 74,545 (0.032%)
      2025-12-04 00:00:00
      2025-12-04 01:00:00
      2025-12-04 02:00:00
      2025-12-04 03:00:00
      2025-12-04 04:00:00
      2025-12-04 05:00:00
      2025-12-04 06:00:00
      2025-12-04 07:00:00
      2025-12-04 08:00:00
      2025-12-04 09:00:00
      2025-12-04 10:00:00
      2025-12-04 11:00:00
      2025-12-04 12:00:00
      2025-12-04 13:00:00
      2025-12-04 14:00:00
      2025-12-04 15:00:00
      2025-12-04 16:00:00
      2025-12-04 17:00:00
      2025-12-04 18:00:00
      2025-12-04 19:00:00
      2025-12-04 20:00:00
      2025-12-04 21:00:00
      2025-12-04 22:00:00
      2025-12-04 23:00:00

  NP6-345-CD  load 8 zones                              24 missing / 74,545 (0.032%)
      2025-12-04 00:00:00
      2025-12-04 01:00:00
      2025-12-04 02:00:00
      2025-12-04 03:00:00
      2025-12-04 04:00:00
      2025-12-04 05:00:00
      2025-12-04 06:00:00
      2025-12-04 07:00:00
      2025-12-04 08:00:00
      2025-12-04 09:00:00
      2025-12-04 10:00:00
      2025-12-04 11:00:00
      2025-12-04 12:00:00
      2025-12-04 13:00:00
      2025-12-04 14:00:00
      2025-12-04 15:00:00
      2025-12-04 16:00:00
      2025-12-04 17:00:00
      2025-12-04 18:00:00
      2025-12-04 19:00:00
      2025-12-04 20:00:00
      2025-12-04 21:00:00
      2025-12-04 22:00:00
      2025-12-04 23:00:00
  NP4-523-CD  system lambda                             ✓ no gaps
  NP4-188-CD  ancillary                                 ✓ no gaps
  NP3-233-CD  generation                                ✓ no gaps
  NP4-732-CD  wind                                      ✓ no gaps

─ NP4-190-CD DAM (wide: houston + avg) ─────────────────────────────────

  NP4-190-CD  DAM (wide)                                656 missing / 74,545 (0.880%)
      2023-03-02 00:00:00
      2023-03-02 01:00:00
      2023-03-02 02:00:00
      2023-03-02 03:00:00
      2023-03-02 04:00:00
      2023-03-02 05:00:00
      2023-03-02 06:00:00
      2023-03-02 07:00:00
      2023-03-02 08:00:00
      2023-03-02 09:00:00
      2023-03-02 10:00:00
      2023-03-02 11:00:00
      2023-03-02 12:00:00
      2023-03-02 13:00:00
      2023-03-02 14:00:00
      2023-03-02 15:00:00
      2023-03-02 16:00:00
      2023-03-02 17:00:00
      2023-03-02 18:00:00
      2023-03-02 19:00:00
      2023-03-02 20:00:00
      2023-03-02 21:00:00
      2023-03-02 22:00:00
      2023-03-02 23:00:00
      2023-03-03 00:00:00
      2023-03-03 01:00:00
      2023-03-03 02:00:00
      2023-03-03 03:00:00
      2023-03-03 04:00:00
      2023-03-03 05:00:00
      2023-03-03 06:00:00
      2023-03-03 07:00:00
      2023-03-03 08:00:00
      2023-03-03 09:00:00
      2023-03-03 10:00:00
      2023-03-03 11:00:00
      2023-03-03 12:00:00
      2023-03-03 13:00:00
      2023-03-03 14:00:00
      2023-03-03 15:00:00
      2023-03-03 16:00:00
      2023-03-03 17:00:00
      2023-03-03 18:00:00
      2023-03-03 19:00:00
      2023-03-03 20:00:00
      2023-03-03 21:00:00
      2023-03-03 22:00:00
      2023-03-03 23:00:00
      2023-03-04 00:00:00
      2023-03-04 01:00:00
      … 606 more

─ NP6-905-CD RTM hourly (per hub) ──────────────────────────────────────
  NP6-905-CD  RTM hourly HB_HOUSTON                     ✓ no gaps
  NP6-905-CD  RTM hourly HB_BUSAVG                      ✓ no gaps

─ NP6-905-CD RTM 15-min (HB_HOUSTON) ───────────────────────────────────

  NP6-905-CD  RTM 15-min HB_HOUSTON                     3 missing / 298,180 (0.001%)
      2023-04-13 14:45:00
      2023-04-13 15:00:00
      2025-12-04 23:45:00

─ Weather stations ──────────────────────────────────────────────────────

  Weather  Houston_avg: no data

  Weather  Houston_stdev: no data

  Weather  Texas_avg: no data

  Weather  Texas_stdev: no data

#### 4.5 Full-History Time Series with Gap Shading

Complete 2017–2025 series for each dataset; red bands mark contiguous missing-slot spans. Visually confirms data continuity and highlights anomalous periods (Winter Storm Uri Feb 2021, COVID-19 demand dip Apr 2020, 2018 wind schema transition).

In [40]:

# ── Per-dataset detailed time series — missing data highlighted ───────────────

_clr  = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']

FULL_START = pd.Timestamp('2017-07-01')
FULL_END   = pd.Timestamp('2025-12-31 23:00:00')
_full_h    = pd.date_range(FULL_START, FULL_END, freq='h')

def _gap_spans(ax, ts, full_idx):
    """Shade missing slots as red bands; return gap count."""
    missing = full_idx.difference(ts.dropna().drop_duplicates())
    n = len(missing)
    if n == 0:
        return 0
    freq_td = full_idx.freq
    cur = missing[0]
    spans = []
    for i in range(1, len(missing)):
        if missing[i] - missing[i - 1] > freq_td * 1.5:
            spans.append((cur, missing[i - 1] + freq_td))
            cur = missing[i]
    spans.append((cur, missing[-1] + freq_td))
    for s, e in spans:
        ax.axvspan(s, e, color='red', alpha=0.3, lw=0, zorder=0)
    return n

def _fmt(ax):
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    ax.tick_params(axis='x', rotation=30, labelsize=8)
    ax.grid(axis='x', alpha=0.2, ls='--')
    ax.grid(axis='y', alpha=0.15)
    ax.set_xlim(FULL_START, FULL_END + pd.Timedelta(days=1))

fig, axes = plt.subplots(9, 1, figsize=(16, 38), constrained_layout=True)
fig.suptitle('Per-Dataset Detailed Time Series  (2017-07-01 → 2025-12-31)\n'
             'Red shading = missing slots relative to full expected range', fontsize=13, y=1.002)

# 1. NP6-346-CD — 4 pricing zones
ax = axes[0]
for col, c in zip(['north', 'south', 'west', 'houston'], _clr):
    s = load346.set_index('ts_utc')[col].reindex(_full_h)
    ax.plot(_full_h, s, lw=0.3, color=c, alpha=0.7, label=col.upper())
n = _gap_spans(ax, load346['ts_utc'], _full_h)
ax.set_title(f'NP6-346-CD — Actual load, 4 pricing zones  |  gaps={n:,}')
ax.set_ylabel('MW'); ax.legend(fontsize=8, ncol=4, loc='upper left'); _fmt(ax)

# 2. NP6-345-CD — Coast zone + system total
ax = axes[1]
for col, c in zip(['coast', 'total'], ['#1f77b4', '#ff7f0e']):
    s = load345.set_index('ts_utc')[col].reindex(_full_h)
    ax.plot(_full_h, s, lw=0.3, color=c, alpha=0.7, label=col.upper())
n = _gap_spans(ax, load345['ts_utc'], _full_h)
ax.set_title(f'NP6-345-CD — Actual load: Coast zone + system Total  |  gaps={n:,}')
ax.set_ylabel('MW'); ax.legend(fontsize=8, ncol=2, loc='upper left'); _fmt(ax)

# 3. NP3-565-CD — D+1 load forecast (system total) + 7-day revision std
ax = axes[2]
ax2 = ax.twinx()
s_fc = fc565_f1.set_index('ts_utc')['fc_system_total'].reindex(_full_h)
ax.plot(_full_h, s_fc, lw=0.3, color='steelblue', alpha=0.75, label='D+1 forecast')
s_std = fc565_f1.set_index('ts_utc')['fc_system_total_std_48h'].reindex(_full_h)
ax2.plot(_full_h, s_std, lw=0.25, color='darkred', alpha=0.5, label='7-day rev std')
n = _gap_spans(ax, fc565_f1['ts_utc'], _full_h)
ax.set_title(f'NP3-565-CD — D+1 load forecast system total + 7-day revision std  |  gaps={n:,}')
ax.set_ylabel('MW'); ax2.set_ylabel('Rev std (MW)', color='darkred')
l1, b1 = ax.get_legend_handles_labels(); l2, b2 = ax2.get_legend_handles_labels()
ax.legend(l1 + l2, b1 + b2, fontsize=8, loc='upper left'); _fmt(ax)

# 4. NP6-905-CD — RTM hourly mean (HB_HOUSTON + HB_BUSAVG, clipped)
ax = axes[3]
for hub, c in zip(HUBS_RTM, ['#1f77b4', '#ff7f0e']):
    s = (rtm905_hourly[rtm905_hourly['hub'] == hub]
         .set_index('ts_utc')['rtm_price_mean'].reindex(_full_h).clip(upper=3000))
    ax.plot(_full_h, s, lw=0.25, color=c, alpha=0.6, label=hub.replace('HB_', ''))
n = _gap_spans(ax, rtm905_hourly[rtm905_hourly['hub'] == 'HB_HOUSTON']['ts_utc'], _full_h)
ax.set_title(f'NP6-905-CD — RTM hourly mean $/MWh (clipped ≤3000)  |  gaps HB_HOUSTON={n:,}')
ax.set_ylabel('$/MWh'); ax.legend(fontsize=8, ncol=2, loc='upper left'); _fmt(ax)

# 5. NP6-905-CD — RTM intra-hour std (realized volatility)
ax = axes[4]
for hub, c in zip(HUBS_RTM, ['#1f77b4', '#ff7f0e']):
    s = (rtm905_hourly[rtm905_hourly['hub'] == hub]
         .set_index('ts_utc')['rtm_price_std'].reindex(_full_h).clip(upper=500))
    ax.plot(_full_h, s, lw=0.2, color=c, alpha=0.5, label=hub.replace('HB_', ''))
n = _gap_spans(ax, rtm905_hourly[rtm905_hourly['hub'] == 'HB_HOUSTON']['ts_utc'], _full_h)
ax.set_title(f'NP6-905-CD — RTM intra-hour price std (realized vol, clipped ≤500)  |  gaps={n:,}')
ax.set_ylabel('$/MWh'); ax.legend(fontsize=8, ncol=2, loc='upper left'); _fmt(ax)

# 6. NP4-732-CD — wind actual + STWPF + error
ax = axes[5]
ax2 = ax.twinx()
for col, c, lbl in [('system_wide_gen', 'forestgreen', 'Actual GEN'),
                    ('stwpf_system_wide', 'darkorange', 'STWPF')]:
    s = wind.set_index('ts_utc')[col].reindex(_full_h)
    ax.plot(_full_h, s, lw=0.25, color=c, alpha=0.65, label=lbl)
s_err = wind.set_index('ts_utc')['wind_error_system'].reindex(_full_h)
ax2.plot(_full_h, s_err, lw=0.2, color='crimson', alpha=0.4, label='Error (GEN-STWPF)')
n = _gap_spans(ax, wind['ts_utc'], _full_h)
ax.set_title(f'NP4-732-CD — Wind system-wide: actual, STWPF, error (MW)  |  gaps={n:,}')
ax.set_ylabel('MW'); ax2.set_ylabel('Error MW', color='crimson')
l1, b1 = ax.get_legend_handles_labels(); l2, b2 = ax2.get_legend_handles_labels()
ax.legend(l1 + l2, b1 + b2, fontsize=8, loc='upper left'); _fmt(ax)

# 7. NP4-190-CD — DAM prices (wide: houston + 4-hub avg)
ax = axes[6]
for col, c, lbl in [('dam_price_houston', '#1f77b4', 'HOUSTON'),
                    ('dam_price_avg',     '#ff7f0e', 'avg(4 hubs)')]:
    s = dam.set_index('ts_utc')[col].reindex(_full_h).clip(upper=3000)
    ax.plot(_full_h, s, lw=0.25, color=c, alpha=0.6, label=lbl)
n = _gap_spans(ax, dam['ts_utc'], _full_h)
ax.set_title(f'NP4-190-CD — DAM hub prices $/MWh (clipped ≤3000)  |  gaps={n:,}')
ax.set_ylabel('$/MWh'); ax.legend(fontsize=8, ncol=2, loc='upper left'); _fmt(ax)

# 8. NP4-523-CD lambda + NP4-188-CD MCPC
ax = axes[7]
ax2 = ax.twinx()
s_lam = lam.set_index('ts_utc')['system_lambda'].reindex(_full_h).clip(upper=3000)
ax.plot(_full_h, s_lam, lw=0.3, color='navy', alpha=0.7, label='System Lambda')
anc_cols = [c for c in anc_wide.columns if c.startswith('mcpc_')]
_clr8 = ['#1f77b4','#ff7f0e','#2ca02c','#d62728','#9467bd','#8c564b','#e377c2','#7f7f7f']
for col, c in zip(anc_cols, _clr8):
    s = anc_wide.set_index('ts_utc')[col].reindex(_full_h).clip(upper=300)
    ax2.plot(_full_h, s, lw=0.2, alpha=0.45, label=col.replace('mcpc_', '').upper(), color=c)
n = _gap_spans(ax, lam['ts_utc'], _full_h)
ax.set_title(f'NP4-523-CD Lambda (left, ≤3000) + NP4-188-CD MCPC (right, ≤300)  |  lambda gaps={n:,}')
ax.set_ylabel('Lambda $/MWh', color='navy'); ax2.set_ylabel('MCPC $/MWh')
l1, b1 = ax.get_legend_handles_labels(); l2, b2 = ax2.get_legend_handles_labels()
ax.legend(l1 + l2, b1 + b2, fontsize=7, ncol=3, loc='upper left'); _fmt(ax)

# 9. NP3-233-CD — generation + RE share
ax = axes[8]
ax2 = ax.twinx()
for col, c, lbl in [('total_resource_mw', 'gray', 'Total gen'),
                    ('total_irr_mw', 'mediumseagreen', 'Renewables (IRR)')]:
    s = gen.set_index('ts_utc')[col].reindex(_full_h)
    ax.plot(_full_h, s, lw=0.25, color=c, alpha=0.65, label=lbl)
s_re = gen.set_index('ts_utc')['re_share'].reindex(_full_h).mul(100)
ax2.plot(_full_h, s_re, lw=0.3, color='darkgreen', alpha=0.8, label='RE share %')
n = _gap_spans(ax, gen['ts_utc'], _full_h)
ax.set_title(f'NP3-233-CD — Total gen, renewables MW, RE share %  |  gaps={n:,}')
ax.set_ylabel('MW'); ax2.set_ylabel('RE share (%)', color='darkgreen')
l1, b1 = ax.get_legend_handles_labels(); l2, b2 = ax2.get_legend_handles_labels()
ax.legend(l1 + l2, b1 + b2, fontsize=8, loc='upper left'); _fmt(ax)

plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/3100625147.py:146: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### 4.6 Diurnal and Seasonal Patterns

Average load, DAM price, and RTM price by hour of day (CST/UTC-6) and by month. These summaries confirm expected ERCOT market structure: afternoon demand peaks (15:00–18:00 CST), summer heat-driven load amplification, and price spikes at peak hours.

In [41]:
_months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
fig.suptitle('Diurnal (CST hour of day, UTC-6) and Seasonal (month) Patterns', fontsize=13)

# row 0: by UTC hour of day
# 0,0  Total load by hour
ax = axes[0, 0]
load346.assign(hr=load346['ts_utc'].dt.hour).groupby('hr')['total'].mean().plot(
    ax=ax, marker='o', ms=4, color='steelblue', lw=1.5)
ax.set_title('Avg total load by hour (CST/UTC-6)')
ax.set_xlabel('CST hour (UTC-6)'); ax.set_ylabel('MW')
ax.set_xticks(range(0, 24, 2)); ax.grid(alpha=0.3)

# 0,1  DAM price mean + P95 by hour (HB_HOUSTON) — dam is wide, use dam_price_houston directly
ax = axes[0, 1]
d = dam.assign(hr=lambda df: df['ts_utc'].dt.hour)
grp = d.groupby('hr')['dam_price_houston']
pd.DataFrame({'Mean': grp.mean(), 'P95': grp.quantile(0.95)}).plot(
    ax=ax, marker='o', ms=3, lw=1.2)
ax.set_title('DAM price by hour — HB_HOUSTON')
ax.set_xlabel('CST hour (UTC-6)'); ax.set_ylabel('$/MWh')
ax.set_xticks(range(0, 24, 2)); ax.grid(alpha=0.3)

# 0,2  RTM intra-hour std (realized vol) by hour (HB_HOUSTON)
ax = axes[0, 2]
d = rtm905_hourly[rtm905_hourly['hub'] == 'HB_HOUSTON'].assign(hr=lambda df: df['ts_utc'].dt.hour)
d.groupby('hr')['rtm_price_std'].mean().plot(
    ax=ax, marker='o', ms=4, color='crimson', lw=1.5)
ax.set_title('RTM intra-hour price std by hour\n(HB_HOUSTON — realized vol proxy)')
ax.set_xlabel('CST hour (UTC-6)'); ax.set_ylabel('$/MWh')
ax.set_xticks(range(0, 24, 2)); ax.grid(alpha=0.3)

# row 1: by month
# 1,0  Total load by month
ax = axes[1, 0]
load346.assign(mo=load346['ts_utc'].dt.month).groupby('mo')['total'].mean().plot(
    kind='bar', ax=ax, color='steelblue', alpha=0.85, width=0.8)
ax.set_title('Avg total load by month')
ax.set_xticklabels(_months, rotation=30, ha='right')
ax.set_ylabel('MW'); ax.grid(axis='y', alpha=0.3)

# 1,1  Wind system-wide generation by month
ax = axes[1, 1]
wind.assign(mo=wind['ts_utc'].dt.month).groupby('mo')['system_wide_gen'].mean().plot(
    kind='bar', ax=ax, color='forestgreen', alpha=0.85, width=0.8)
ax.set_title('Avg wind generation by month')
ax.set_xticklabels(_months, rotation=30, ha='right')
ax.set_ylabel('MW'); ax.grid(axis='y', alpha=0.3)

# 1,2  Renewable share by month
ax = axes[1, 2]
gen.assign(mo=gen['ts_utc'].dt.month).groupby('mo')['re_share'].mean().mul(100).plot(
    kind='bar', ax=ax, color='mediumseagreen', alpha=0.85, width=0.8)
ax.set_title('Avg renewable share by month')
ax.set_xticklabels(_months, rotation=30, ha='right')
ax.set_ylabel('%'); ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/1991038964.py:60: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### 4.7 Extreme Price Events and Annual Statistics

Counts DAM/RTM hours above 500 $/MWh or below −50 $/MWh, and prints the all-time maximum and minimum with timestamps. The annual hub-level table (mean, p50, p95, p99, max) tracks multi-year market structure shifts — shale gas glut 2019, Uri 2021 cap event, and the renewable build-out price suppression from 2022 onward.

In [42]:
_clr = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']

# ── Extreme price summary ─────────────────────────────────────────────────────
print('=== Extreme price events ===\n')

for ds_label, df_sub, price_col in [
    ('DAM (houston)',  dam,           'dam_price_houston'),
    ('RTM hourly',     rtm905_hourly, 'rtm_price_mean'),
]:
    print(f'{ds_label}:')
    for thr, direction in [(500, '>'), (-50, '<')]:
        mask = df_sub[price_col] > thr if direction == '>' else df_sub[price_col] < thr
        n, pct = mask.sum(), mask.mean() * 100
        print(f'  {price_col} {direction} {thr}: {n:,} ({pct:.3f}%)')
    idx_max = df_sub[price_col].idxmax()
    idx_min = df_sub[price_col].idxmin()
    hub_info = f'  hub={df_sub.loc[idx_max, "hub"]}' if 'hub' in df_sub.columns else ''
    print(f'  max = {df_sub.loc[idx_max, price_col]:,.1f} $/MWh  @ {df_sub.loc[idx_max, "ts_utc"]}{hub_info}')
    print(f'  min = {df_sub.loc[idx_min, price_col]:,.2f} $/MWh  @ {df_sub.loc[idx_min, "ts_utc"]}')
    print()

# Annual DAM stats — HB_HOUSTON
print('Annual DAM statistics (HB_HOUSTON):')
d_n = dam[['ts_utc', 'dam_price_houston']].copy()
d_n['year'] = d_n['ts_utc'].dt.year
annual = d_n.groupby('year')['dam_price_houston'].agg(
    mean='mean', p50='median',
    p95=lambda x: x.quantile(0.95),
    p99=lambda x: x.quantile(0.99),
    max='max',
    pct_neg=lambda x: round((x < 0).mean() * 100, 2),
    pct_gt500=lambda x: round((x > 500).mean() * 100, 3),
)
display(annual.round(2))

# ── Winter Storm Uri zoom (Feb 2021) ─────────────────────────────────────────
lo, hi = pd.Timestamp('2021-02-09'), pd.Timestamp('2021-02-21')
fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
fig.suptitle('Winter Storm Uri — Feb 9–20, 2021', fontsize=13)

ax = axes[0]
for col, c, lbl in [('dam_price_houston', '#1f77b4', 'HOUSTON'),
                    ('dam_price_avg',     '#ff7f0e', 'avg(4 hubs)')]:
    sub = dam[(dam['ts_utc'] >= lo) & (dam['ts_utc'] <= hi)].sort_values('ts_utc')
    ax.plot(sub['ts_utc'], sub[col], lw=1.5, label=lbl, color=c)
ax.set_title('DAM hub prices')
ax.set_ylabel('$/MWh')
ax.legend(fontsize=9, ncol=2)
ax.grid(alpha=0.3)

ax = axes[1]
for hub, c in zip(HUBS_RTM, ['#1f77b4', '#ff7f0e']):
    sub = rtm905_hourly[(rtm905_hourly['hub'] == hub) &
                        (rtm905_hourly['ts_utc'] >= lo) &
                        (rtm905_hourly['ts_utc'] <= hi)].sort_values('ts_utc')
    ax.plot(sub['ts_utc'], sub['rtm_price_mean'], lw=1.5, label=hub.replace('HB_', ''), color=c)
ax.set_title('RTM hourly mean prices')
ax.set_ylabel('$/MWh')
ax.legend(fontsize=9, ncol=2)
ax.grid(alpha=0.3)

ax = axes[2]
ax2 = ax.twinx()
uri_load = load346[(load346['ts_utc'] >= lo) & (load346['ts_utc'] <= hi)].sort_values('ts_utc')
uri_wind = wind[(wind['ts_utc'] >= lo) & (wind['ts_utc'] <= hi)].sort_values('ts_utc')
ax.plot(uri_load['ts_utc'], uri_load['total'], color='steelblue', lw=1.5, label='Total load (MW)')
ax2.plot(uri_wind['ts_utc'], uri_wind['system_wide_gen'], color='forestgreen',
         lw=1.5, alpha=0.8, label='Wind gen (MW)')
ax.set_title('Total load and wind generation')
ax.set_ylabel('MW (load)', color='steelblue')
ax2.set_ylabel('MW (wind)', color='forestgreen')
lines1, labs1 = ax.get_legend_handles_labels()
lines2, labs2 = ax2.get_legend_handles_labels()
ax.legend(lines1 + lines2, labs1 + labs2, fontsize=9)
ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

=== Extreme price events ===

DAM (houston):
  dam_price_houston > 500: 477 (0.646%)
  dam_price_houston < -50: 0 (0.000%)
  max = 8,995.1 $/MWh  @ 2021-02-17 00:00:00
  min = -0.10 $/MWh  @ 2025-01-05 02:00:00

RTM hourly:
  rtm_price_mean > 500: 991 (0.665%)
  rtm_price_mean < -50: 6 (0.004%)
  max = 9,062.5 $/MWh  @ 2021-02-17 04:00:00  hub=HB_HOUSTON
  min = -173.18 $/MWh  @ 2022-11-04 18:00:00

Annual DAM statistics (HB_HOUSTON):

        mean    p50     p95      p99      max  pct_neg  pct_gt500
year
2017   28.00  23.04   57.15    89.08   306.24     0.00       0.00
2018   33.86  25.34   58.40   116.08  2057.51     0.00       0.34
2019   38.51  21.30   56.05   299.06  5011.16     0.00       0.68
2020   22.92  18.18   44.39    90.60  2026.17     0.00       0.09
2021  148.21  30.00   90.72  7000.15  8995.11     0.00       1.92
2022   69.92  50.47  161.92   409.91  2523.86     0.00       0.68
2023   58.07  22.68  138.99   810.35  4188.23     0.00       1.47
2024   28.29  19.76   60.66   152.50  2215.08     0.01       0.26
2025   34.40  28.77   70.35   112.35   772.08     0.02       0.05
2026   19.84  20.40   31.54    32.30    32.36     0.00       0.00

/var/folders/vf/16_9fg814l76_gcv900gxyzc0000gn/T/ipykernel_51379/1435325160.py:78: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### 4.8 Dataset Publication Latency (postDateTime)

How quickly does ERCOT publish each dataset after the operating hour? This determines which datasets are usable as **D+1 forecasting features** vs. only as **lagged features**.

Analysis run over all CSV files (no sampling), reading `postDateTime` only.

| Dataset | Rows | Dates | Avg daily mean post time | Latest post time ever | Availability for D+1 |
|---------|------|-------|--------------------------|----------------------|----------------------|
| NP6-346-CD (Wind forecast) | 75,937 | 3,164 | 05:50 UTC | 05:50:38 UTC | ✅ Safe — next-day batch |
| NP6-345-CD (Wind actual) | 103,870 | 4,321 | 05:50 UTC | 05:50:03 UTC | ✅ Safe — same batch as 346-CD |
| NP4-190-CD (DAM prices) | 76,176,352 | 4,302 | 12:42 UTC | 20:21:03 UTC | ✅ Safe — posted after DAM clears (~noon) |
| NP4-523-CD (System Lambda) | 75,961 | 3,165 | 12:38 UTC | 17:53:15 UTC | ✅ Safe — published alongside 190-CD |
| NP4-188-CD (Ancillary MCPC) | 327,749 | 3,156 | 12:38 UTC | 17:53:15 UTC | ✅ Safe — published alongside 523-CD |
| NP6-905-CD (RTM prices) | 607,708 | 3,165 | 11:54 UTC | 23:47:18 UTC | ⛔ Lags only — posts near real-time until ~23:47 UTC |

**Key takeaway**: DAM prices, ancillary prices, and wind forecasts are reliably published by ~12:45 UTC — well before the 24-hour-ahead delivery window. RTM prices post up to 23:47 UTC and cannot be used as same-day D+1 features; only prior-day lags are safe.

This confirms the **D+1 leakage boundary** used in §5 feature construction.

## 5. Build Processed Data

Merge all hourly-frequency datasets on `ts_utc`.  
Pivot RTM and DAM to wide format (one column per hub).  
Primary load source: NP6-346-CD (2017-07 onward); NP6-345-CD TOTAL used for 2014-2017 gap if needed.

Derived features added here:
- `dam_rtm_spread` = DAM price − RTM hourly mean (per hub)
- `re_share` = TotalIRRMW / TotalResourceMW
- `net_load_mw` = total load − total renewable MW

In [43]:

# Pivot RTM to wide (one column per hub: HB_HOUSTON, HB_BUSAVG)
rtm_wide = rtm905_hourly.pivot_table(
    index='ts_utc', columns='hub',
    values=['rtm_price_mean', 'rtm_price_std', 'rtm_price_max', 'rtm_price_min']
).reset_index()
rtm_wide.columns = [
    'ts_utc' if c[1] == '' else f"{c[0]}_{c[1].lower()}"
    for c in rtm_wide.columns
]

# dam is already wide: dam_price_houston, dam_price_avg

# fc565_f1 (D+1 load forecast + 7-day revision std) built in §3 NP3-565-CD section.
# wind_f1  (D+1 STWPF + 7-day revision std)         built in §3 NP4-732-CD section.
# gen_f1   (D+1 outage capacity + 7-day revision std) built in §3 NP3-233-CD section.

# Build full hourly index spanning all data
ts_min = min(rtm905_hourly['ts_utc'].min(), load346['ts_utc'].min())
ts_max = max(rtm905_hourly['ts_utc'].max(), load346['ts_utc'].max())
ercot_combined = pd.DataFrame({'ts_utc': pd.date_range(ts_min, ts_max, freq='h')})

# Sequential merges (left join preserves full time index)
ercot_combined = (
    ercot_combined
    .merge(load346[['ts_utc', 'houston', 'total']]
           .rename(columns={'houston': 'load_houston', 'total': 'load_total'}),
           on='ts_utc', how='left')
    .merge(load345.rename(columns=lambda c: f'wz_{c}' if c != 'ts_utc' else c),
           on='ts_utc', how='left')
    .merge(rtm_wide,   on='ts_utc', how='left')
    .merge(dam,        on='ts_utc', how='left')
    .merge(lam,        on='ts_utc', how='left')
    .merge(gen,        on='ts_utc', how='left')
    .merge(gen_f1,     on='ts_utc', how='left')
    .merge(anc_wide,   on='ts_utc', how='left')
    .merge(fc565_f1,   on='ts_utc', how='left')
    .merge(wind_f1,    on='ts_utc', how='left')
)

# Derived: DA-RT spread for Houston and system-level
if 'rtm_price_mean_hb_houston' in ercot_combined.columns and 'dam_price_houston' in ercot_combined.columns:
    ercot_combined['dam_rtm_spread_houston'] = (
        ercot_combined['dam_price_houston'] - ercot_combined['rtm_price_mean_hb_houston']
    )
if 'rtm_price_mean_hb_busavg' in ercot_combined.columns and 'dam_price_avg' in ercot_combined.columns:
    ercot_combined['dam_rtm_spread_avg'] = (
        ercot_combined['dam_price_avg'] - ercot_combined['rtm_price_mean_hb_busavg']
    )

if 'total_irr_mw' in ercot_combined.columns and 'load_total' in ercot_combined.columns:
    ercot_combined['net_load_mw'] = ercot_combined['load_total'] - ercot_combined['total_irr_mw']

# Calendar features
ercot_combined['hour']    = ercot_combined['ts_utc'].dt.hour
ercot_combined['month']   = ercot_combined['ts_utc'].dt.month
ercot_combined['weekday'] = ercot_combined['ts_utc'].dt.dayofweek   # 0=Mon
_hour_ct = (ercot_combined['ts_utc'] - pd.Timedelta(hours=6)).dt.hour
ercot_combined['is_peak'] = ((_hour_ct >= 7) & (_hour_ct <= 22) &
                              (ercot_combined['weekday'] < 5)).astype(int)
ercot_combined['season']  = ercot_combined['month'].map({
    12:'winter', 1:'winter', 2:'winter',
    3:'spring',  4:'spring', 5:'spring',
    6:'summer',  7:'summer', 8:'summer', 9:'summer',
    10:'fall',   11:'fall'
})

print('Processed data table:')
print(f'  rows: {len(ercot_combined):,}')
print(f'  range: {ercot_combined.ts_utc.min()} → {ercot_combined.ts_utc.max()}')
print(f'  columns ({len(ercot_combined.columns)}): {list(ercot_combined.columns)}')
null_report(ercot_combined, 'ercot_combined')

Processed data table:
  rows: 74,569
  range: 2017-06-29 23:00:00 → 2025-12-31 23:00:00
  columns (57): ['ts_utc', 'load_houston', 'load_total', 'wz_coast', 'wz_east', 'wz_far_west', 'wz_north', 'wz_north_c', 'wz_southern', 'wz_south_c', 'wz_west', 'wz_total', 'rtm_price_max_hb_busavg', 'rtm_price_max_hb_houston', 'rtm_price_mean_hb_busavg', 'rtm_price_mean_hb_houston', 'rtm_price_min_hb_busavg', 'rtm_price_min_hb_houston', 'rtm_price_std_hb_busavg', 'rtm_price_std_hb_houston', 'dam_price_houston', 'dam_price_avg', 'system_lambda', 'total_resource_mw', 'total_irr_mw', 're_share', 'houston_resource_mw', 'houston_irr_mw', 'houston_re_share', 'genf_horizon_h', 'genf_total_resource_mw', 'genf_total_irr_mw', 'genf_total_resource_mw_std_48h', 'genf_total_irr_mw_std_48h', 'mcpc_ecrs', 'mcpc_nspin', 'mcpc_regdn', 'mcpc_regup', 'mcpc_rrs', 'fc_horizon_h', 'fc_coast', 'fc_system_total', 'fc_coast_std_48h', 'fc_system_total_std_48h', 'wf_horizon_h', 'wf_stwpf_system_wide', 'wf_stwpf_lz_south_houston', 'wf_stwpf_system_wide_std_48h', 'wf_stwpf_lz_south_houston_std_48h', 'dam_rtm_spread_houston', 'dam_rtm_spread_avg', 'net_load_mw', 'hour', 'month', 'weekday', 'is_peak', 'season']

ercot_combined: 74,569 rows
  load_houston: 0.06% null
  load_total: 0.06% null
  wz_coast: 0.06% null
  wz_east: 0.06% null
  wz_far_west: 0.06% null
  wz_north: 0.06% null
  wz_north_c: 0.06% null
  wz_southern: 0.06% null
  wz_south_c: 0.06% null
  wz_west: 0.06% null
  wz_total: 0.06% null
  rtm_price_max_hb_busavg: 0.03% null
  rtm_price_max_hb_houston: 0.03% null
  rtm_price_mean_hb_busavg: 0.03% null
  rtm_price_mean_hb_houston: 0.03% null
  rtm_price_min_hb_busavg: 0.03% null
  rtm_price_min_hb_houston: 0.03% null
  rtm_price_std_hb_busavg: 0.03% null
  rtm_price_std_hb_houston: 0.03% null
  dam_price_houston: 0.94% null
  dam_price_avg: 0.94% null
  system_lambda: 0.06% null
  total_resource_mw: 0.17% null
  total_irr_mw: 0.17% null
  re_share: 0.17% null
  houston_resource_mw: 45.95% null
  houston_irr_mw: 45.95% null
  houston_re_share: 45.95% null
  genf_horizon_h: 0.07% null
  genf_total_resource_mw: 0.23% null
  genf_total_irr_mw: 0.23% null
  genf_total_resource_mw_std_48h: 0.16% null
  genf_total_irr_mw_std_48h: 0.16% null
  mcpc_ecrs: 69.87% null
  mcpc_nspin: 0.06% null
  mcpc_regdn: 0.06% null
  mcpc_regup: 0.06% null
  mcpc_rrs: 0.06% null
  fc_horizon_h: 0.07% null
  fc_coast: 0.07% null
  fc_system_total: 0.07% null
  fc_coast_std_48h: 0.07% null
  fc_system_total_std_48h: 0.07% null
  wf_horizon_h: 0.07% null
  wf_stwpf_system_wide: 0.07% null
  wf_stwpf_lz_south_houston: 0.07% null
  wf_stwpf_system_wide_std_48h: 0.07% null
  wf_stwpf_lz_south_houston_std_48h: 0.07% null
  dam_rtm_spread_houston: 0.94% null
  dam_rtm_spread_avg: 0.94% null
  net_load_mw: 0.24% null

#### Post-Merge Quality Checks

Validates that `master` is internally consistent: load is positive, prices are within plausible physical bounds, renewable share lies in [0, 1], and DAM/RTM hub non-null counts are symmetric. Spring-forward all-NaN rows are counted as a proxy for timestamp edge-case handling.

#### `ercot_combined` Column Descriptions

| Column | Source | Description |
|---|---|---|
| `ts_utc` | — | Delivery hour timestamp (naive, fixed UTC-6 / CST) |
| **Actual Load** | NP6-346-CD | |
| `load_houston` | NP6-346-CD | Actual load — Houston pricing zone (MWh) |
| `load_total` | NP6-346-CD | Actual total system load (MWh) |
| **Load by Weather Zone** | NP6-345-CD | |
| `wz_coast` | NP6-345-CD | Actual load — Coast weather zone (MWh) |
| `wz_east` | NP6-345-CD | Actual load — East weather zone (MWh) |
| `wz_far_west` | NP6-345-CD | Actual load — Far West weather zone (MWh) |
| `wz_north` | NP6-345-CD | Actual load — North weather zone (MWh) |
| `wz_north_c` | NP6-345-CD | Actual load — North Central weather zone (MWh) |
| `wz_southern` | NP6-345-CD | Actual load — Southern weather zone (MWh) |
| `wz_south_c` | NP6-345-CD | Actual load — South Central weather zone (MWh) |
| `wz_west` | NP6-345-CD | Actual load — West weather zone (MWh) |
| `wz_total` | NP6-345-CD | Actual total system load from weather-zone dataset (MWh) |
| **RTM Prices** | NP6-905-CD | Hourly aggregates of 15-min real-time settlement prices |
| `rtm_price_mean_hb_houston` | NP6-905-CD | Mean RTM price — Houston hub ($/MWh) |
| `rtm_price_std_hb_houston` | NP6-905-CD | Intra-hour RTM price std — Houston hub (realized volatility proxy) |
| `rtm_price_max_hb_houston` | NP6-905-CD | Max RTM price within hour — Houston hub ($/MWh) |
| `rtm_price_min_hb_houston` | NP6-905-CD | Min RTM price within hour — Houston hub ($/MWh) |
| `rtm_price_mean_hb_busavg` | NP6-905-CD | Mean RTM price — system bus average hub ($/MWh) |
| `rtm_price_std_hb_busavg` | NP6-905-CD | Intra-hour RTM price std — system bus average (realized volatility proxy) |
| `rtm_price_max_hb_busavg` | NP6-905-CD | Max RTM price within hour — system bus average ($/MWh) |
| `rtm_price_min_hb_busavg` | NP6-905-CD | Min RTM price within hour — system bus average ($/MWh) |
| **DAM Prices** | NP4-190-CD | Day-ahead market clearing prices (published ~10–11 AM for next day) |
| `dam_price_houston` | NP4-190-CD | DAM settlement price — Houston hub ($/MWh) |
| `dam_price_avg` | NP4-190-CD | DAM settlement price — simple average of 4 hubs ($/MWh) |
| **System Lambda** | NP4-523-CD | |
| `system_lambda` | NP4-523-CD | DAM marginal energy cost of serving an additional MW ($/MWh) |
| **Outage Capacity (Actuals)** | NP3-233-CD | Scheduled resource outage capacity — latest posting per delivery slot |
| `total_resource_mw` | NP3-233-CD | Total scheduled resource outage capacity, system-wide (MW) |
| `total_irr_mw` | NP3-233-CD | Total intermittent renewable resource capacity in outage schedule (MW) |
| `re_share` | NP3-233-CD | Renewable share of outage capacity (total_irr_mw / total_resource_mw) |
| `houston_resource_mw` | NP3-233-CD | Total outage capacity — Houston zone (MW, available 2021-05+) |
| `houston_irr_mw` | NP3-233-CD | IRR outage capacity — Houston zone (MW, available 2021-05+) |
| `houston_re_share` | NP3-233-CD | Renewable share — Houston zone (2021-05+) |
| **Outage Capacity (Forecast)** | NP3-233-CD | 6PM D-1 snapshot + 48h revision std (D+1 delivery) |
| `genf_total_resource_mw` | NP3-233-CD | Scheduled outage capacity forecast at 6PM D-1 (MW) |
| `genf_total_irr_mw` | NP3-233-CD | IRR outage capacity forecast at 6PM D-1 (MW) |
| `genf_total_resource_mw_std_48h` | NP3-233-CD | Std of outage capacity postings over prior 48h — supply schedule uncertainty |
| `genf_total_irr_mw_std_48h` | NP3-233-CD | Std of IRR outage postings over prior 48h |
| `genf_horizon_h` | NP3-233-CD | Forecast horizon of the 6PM D-1 snapshot (hours before delivery) |
| **Ancillary Prices** | NP4-188-CD | DAM market clearing prices for capacity (MCPC) |
| `mcpc_rrs` | NP4-188-CD | MCPC — Responsive Reserve Service ($/MW) |
| `mcpc_regup` | NP4-188-CD | MCPC — Regulation Up ($/MW) |
| `mcpc_regdn` | NP4-188-CD | MCPC — Regulation Down ($/MW) |
| `mcpc_nonspin` | NP4-188-CD | MCPC — Non-Spinning Reserve ($/MW) |
| **Load Forecast** | NP3-565-CD | 6PM D-1 snapshot + 48h revision std (D+1 delivery, InUseFlag=Y only) |
| `fc_coast` | NP3-565-CD | Load forecast at 6PM D-1 — Coast weather zone (MWh) |
| `fc_system_total` | NP3-565-CD | Load forecast at 6PM D-1 — system total (MWh) |
| `fc_coast_std_48h` | NP3-565-CD | Std of Coast load forecast postings over prior 48h — demand uncertainty |
| `fc_system_total_std_48h` | NP3-565-CD | Std of system total load forecast postings over prior 48h |
| `fc_horizon_h` | NP3-565-CD | Forecast horizon of the 6PM D-1 snapshot (hours before delivery) |
| **Wind Forecast** | NP4-732-CD | 6PM D-1 snapshot + 48h revision std (D+1 delivery, STWPF only) |
| `wf_stwpf_system_wide` | NP4-732-CD | Wind power forecast at 6PM D-1 — system-wide (MW) |
| `wf_stwpf_lz_south_houston` | NP4-732-CD | Wind power forecast at 6PM D-1 — South Houston load zone (MW) |
| `wf_stwpf_system_wide_std_48h` | NP4-732-CD | Std of system wind forecast over prior 48h — wind uncertainty |
| `wf_stwpf_lz_south_houston_std_48h` | NP4-732-CD | Std of Houston wind forecast over prior 48h |
| `wf_horizon_h` | NP4-732-CD | Forecast horizon of the 6PM D-1 snapshot (hours before delivery) |
| **Derived** | — | |
| `dam_rtm_spread_houston` | derived | DAM − RTM mean price, Houston hub ($/MWh); positive = DA premium |
| `dam_rtm_spread_avg` | derived | DAM − RTM mean price, system average ($/MWh) |
| `net_load_mw` | derived | load_total − total_irr_mw; net demand after renewables (MW) |
| **Calendar** | — | |
| `hour` | derived | Hour of day (0–23, CST) |
| `month` | derived | Month (1–12) |
| `weekday` | derived | Day of week (0=Monday … 6=Sunday) |
| `is_peak` | derived | 1 if weekday 7AM–10PM CST, 0 otherwise |
| `season` | derived | winter / spring / summer / fall |

In [44]:

# ── Post-merge sanity checks ─────────────────────────────────────────────────
print("=== ercot_combined sanity checks ===")
print(f"  Rows: {len(ercot_combined):,}  |  Columns: {len(ercot_combined.columns)}")
print(f"  Range: {ercot_combined.ts_utc.min()} → {ercot_combined.ts_utc.max()}")
print()

def _check(label, mask):
    n = int(mask.sum())
    total = int(mask.notna().sum())
    print(f"  {label:<55} {n:>8,} / {total:,}")

print("Bounds checks (failing rows / non-null rows):")
if "load_total" in ercot_combined.columns:
    _check("load_total <= 0  (bad)",      ercot_combined["load_total"] <= 0)
if "system_lambda" in ercot_combined.columns:
    _check("system_lambda < 0  (negative)", ercot_combined["system_lambda"] < 0)
if "re_share" in ercot_combined.columns:
    _check("re_share < 0 or > 1  (out of range)",
           (ercot_combined["re_share"] < 0) | (ercot_combined["re_share"] > 1))
if "total_resource_mw" in ercot_combined.columns:
    _check("total_resource_mw <= 0  (bad)", ercot_combined["total_resource_mw"] <= 0)
for col in ["dam_price_houston", "dam_price_avg"]:
    if col in ercot_combined.columns:
        _check(f"{col} < -500  (spike)", ercot_combined[col] < -500)
for col in ["rtm_price_mean_hb_houston", "rtm_price_mean_hb_busavg"]:
    if col in ercot_combined.columns:
        _check(f"{col} < -500  (spike)", ercot_combined[col] < -500)
print()

print("Data availability (non-null rows):")
for col in ["dam_price_houston", "dam_price_avg",
            "rtm_price_mean_hb_houston", "rtm_price_mean_hb_busavg"]:
    if col in ercot_combined.columns:
        n = ercot_combined[col].notna().sum()
        print(f"  {col:<40}  {n:>7,}")
print()

# Spring-forward NaT check
price_cols = [c for c in ercot_combined.columns
              if c.startswith(("dam_price", "rtm_price_mean", "load_total"))]
if price_cols:
    all_null_rows = ercot_combined[price_cols].isna().all(axis=1)
    n_empty = int(all_null_rows.sum())
    n_years = ercot_combined["ts_utc"].dt.year.nunique()
    print(f"Fully-empty rows (all price cols null): {n_empty}")
    print(f"  Expected ~{n_years} (one spring-forward gap per year)")
    if n_empty > n_years * 2:
        print("  WARNING: more empty rows than expected — investigate")
    if n_empty > 0:
        print("  Dates:", ercot_combined.loc[all_null_rows, "ts_utc"].dt.date.unique()[:10])

=== ercot_combined sanity checks ===
  Rows: 74,569  |  Columns: 57
  Range: 2017-06-29 23:00:00 → 2025-12-31 23:00:00

Bounds checks (failing rows / non-null rows):
  load_total <= 0  (bad)                                         0 / 74,569
  system_lambda < 0  (negative)                                667 / 74,569
  re_share < 0 or > 1  (out of range)                        2,478 / 74,569
  total_resource_mw <= 0  (bad)                                  0 / 74,569
  dam_price_houston < -500  (spike)                              0 / 74,569
  dam_price_avg < -500  (spike)                                  0 / 74,569
  rtm_price_mean_hb_houston < -500  (spike)                      0 / 74,569
  rtm_price_mean_hb_busavg < -500  (spike)                       0 / 74,569

Data availability (non-null rows):
  dam_price_houston                          73,865
  dam_price_avg                              73,865
  rtm_price_mean_hb_houston                  74,546
  rtm_price_mean_hb_busavg                   74,546

Fully-empty rows (all price cols null): 0
  Expected ~9 (one spring-forward gap per year)

Inspect the shape, column dtypes, and summary statistics of `master`. Key checks: no unexpected all-null columns, numeric ranges are physically plausible, and `ts_utc` spans the full 2017-07 → 2025-12 window.

In [45]:
display(ercot_combined.head())
display(ercot_combined.describe())

,ts_utc,load_houston,load_total,wz_coast,wz_east,wz_far_west,wz_north,wz_north_c,wz_southern,wz_south_c,...,wf_stwpf_system_wide_std_48h,wf_stwpf_lz_south_houston_std_48h,dam_rtm_spread_houston,dam_rtm_spread_avg,net_load_mw,hour,month,weekday,is_peak,season
0,2017-06-29 23:00:00,12325.89,46147.01,12772.35,1750.20,2442.93,1133.77,14642.03,3858.07,7928.67,...,NaN,NaN,NaN,NaN,NaN,23,6,3,1,summer
1,2017-06-30 00:00:00,11794.53,43793.35,12221.90,1663.85,2363.99,1094.61,13802.06,3649.33,7460.13,...,NaN,NaN,NaN,NaN,NaN,0,6,4,1,summer
2,2017-06-30 01:00:00,11430.60,42145.28,11844.95,1604.83,2306.38,1048.68,13253.64,3507.53,7096.73,...,NaN,NaN,NaN,NaN,NaN,1,6,4,1,summer
3,2017-06-30 02:00:00,11244.33,41212.93,11652.00,1533.51,2270.51,1038.57,12964.89,3393.53,6918.35,...,NaN,NaN,NaN,NaN,NaN,2,6,4,1,summer
4,2017-06-30 03:00:00,11290.21,41049.55,11699.66,1576.41,2240.14,989.58,12925.32,3333.60,6854.05,...,NaN,NaN,NaN,NaN,NaN,3,6,4,1,summer

,ts_utc,load_houston,load_total,wz_coast,wz_east,wz_far_west,wz_north,wz_north_c,wz_southern,wz_south_c,...,wf_stwpf_lz_south_houston,wf_stwpf_system_wide_std_48h,wf_stwpf_lz_south_houston_std_48h,dam_rtm_spread_houston,dam_rtm_spread_avg,net_load_mw,hour,month,weekday,is_peak
count,74569,74521.000000,74521.000000,74521.000000,74521.000000,74521.000000,74521.000000,74521.000000,74521.000000,74521.000000,...,74519.000000,74519.000000,74519.000000,73865.000000,73865.000000,74393.000000,74569.000000,74569.000000,74569.000000,74569.000000
mean,2021-09-30 11:00:00,12490.123637,47774.395748,12942.900062,1734.340268,4708.641589,1274.121815,14142.431649,3831.444804,7737.632866,...,2587.167183,745.150742,202.205064,1.694930,1.769442,43904.855767,11.500154,6.698735,3.000000,0.476136
min,2017-06-29 23:00:00,4770.730000,26808.680000,4935.200000,500.000000,1086.590000,300.000000,7439.160000,1859.650000,3923.680000,...,14.200000,39.204101,5.827944,-7243.090000,-7242.000000,19423.220000,0.000000,1.000000,0.000000,0.000000
25%,2019-08-15 17:00:00,10371.850000,39514.800000,10748.090000,1431.240000,3405.750000,934.520000,11406.910000,3103.810000,6149.160000,...,1227.500000,425.229761,111.453262,-1.360000,-1.452500,36050.820000,6.000000,4.000000,1.000000,0.000000
50%,2021-09-30 11:00:00,11800.990000,45419.970000,12228.670000,1631.750000,4121.590000,1172.430000,13141.990000,3647.660000,7249.750000,...,2250.000000,631.729429,168.128001,1.937500,1.842500,41343.520000,12.000000,7.000000,3.000000,0.000000
75%,2023-11-16 05:00:00,14191.120000,54245.030000,14705.860000,1972.740000,6189.570000,1537.890000,16151.630000,4454.920000,8948.580000,...,3621.050000,934.336210,253.630077,6.957500,6.512500,49874.560000,18.000000,10.000000,5.000000,1.000000
max,2025-12-31 23:00:00,22693.080000,85558.980000,23515.820000,3674.090000,9461.680000,3066.370000,28268.770000,7209.290000,15564.030000,...,8220.600000,4824.277057,1612.878561,8464.412500,8461.325000,81187.980000,23.000000,12.000000,6.000000,1.000000
std,NaN,2851.889746,11189.454341,2955.032348,423.547502,1694.870625,432.758865,3851.538206,942.486211,2134.622293,...,1704.220034,467.960000,134.646083,167.127884,164.574627,10783.195860,6.922315,3.442574,2.000322,0.499434

## 6. Save Outputs

All outputs are saved as **Apache Parquet** (columnar, compressed) for fast loading in downstream analysis. ERCOT datasets go to `data/processed/ercot/`; weather to `data/processed/weather/`. The `hourly_master` table is the primary analysis artifact; per-dataset files are provided for dataset-specific work.

In [46]:

def _save(df, name):
    p = PROCESSED_ROOT / f'{name}.parquet'
    df.to_parquet(p, index=False)
    print(f'  {name}.parquet  ({p.stat().st_size / 1e6:.1f} MB, {len(df):,} rows)')

def _save_w(df, name):
    p = WEATHER_PROCESSED / f'{name}.parquet'
    df.to_parquet(p, index=False)
    print(f'  {name}.parquet  ({p.stat().st_size / 1e6:.1f} MB, {len(df):,} rows)')

# ── Combined ───────────────────────────────────────────────────────────────────
print('\n── Combined ──────────────────────────────────────────────────────────')
_save(ercot_combined, 'ercot_combined')

# ── NP6-346-CD: Houston and total only ────────────────────────────────────────
print('\n── NP6-346-CD — Actual load, Houston + total ────────────────────────')
_save(load346[['ts_utc', 'houston']], 'np6_346_houston')
_save(load346[['ts_utc', 'total']],   'np6_346_total')

# ── NP6-345-CD: coast and total only ──────────────────────────────────────────
print('\n── NP6-345-CD — Actual load, coast + total ──────────────────────────')
_save(load345[['ts_utc', 'coast']], 'np6_345_coast')
_save(load345[['ts_utc', 'total']], 'np6_345_total')

# ── NP4-732-CD: system-wide group and Houston group ───────────────────────────
print('\n── NP4-732-CD — Wind power ───────────────────────────────────────────')
_WIND_SYS = ['system_wide_gen', 'cop_hsl_system_wide', 'stwpf_system_wide',
             'wgrpp_system_wide', 'system_wide_hsl', 'wind_error_system']
_WIND_HOU = ['gen_lz_south_houston', 'cop_hsl_lz_south_houston', 'stwpf_lz_south_houston',
             'wgrpp_lz_south_houston', 'wind_error_houston']
_save(wind[['ts_utc'] + _WIND_SYS], 'np4_732_wind_system')
_save(wind[['ts_utc'] + _WIND_HOU], 'np4_732_wind_houston')

# ── NP4-190-CD: Houston hub and 4-hub average ─────────────────────────────────
print('\n── NP4-190-CD — DAM prices ───────────────────────────────────────────')
_save(dam[['ts_utc', 'dam_price_houston']], 'np4_190_dam_houston')
_save(dam[['ts_utc', 'dam_price_avg']],     'np4_190_dam_avg')

# ── NP6-905-CD: hourly only, one file per hub ─────────────────────────────────
print('\n── NP6-905-CD — RTM prices (hourly) ─────────────────────────────────')
for _hub, _slug in [('HB_HOUSTON', 'houston'), ('HB_BUSAVG', 'busavg')]:
    _save(rtm905_hourly[rtm905_hourly['hub'] == _hub]
          [['ts_utc', 'rtm_price_mean', 'rtm_price_std', 'rtm_price_max', 'rtm_price_min']]
          .reset_index(drop=True),
          f'np6_905_rtm_hourly_{_slug}')

# ── NP4-523-CD: system lambda (single series) ─────────────────────────────────
print('\n── NP4-523-CD — System Lambda ────────────────────────────────────────')
_save(lam, 'np4_523_system_lambda')

# ── NP4-188-CD: one file per ancillary type ───────────────────────────────────
print('\n── NP4-188-CD — Ancillary prices ─────────────────────────────────────')
for _col in [c for c in anc_wide.columns if c != 'ts_utc']:
    _save(anc_wide[['ts_utc', _col]], f'np4_188_{_col}')

# ── NP3-233-CD: system total group and Houston group ──────────────────────────
print('\n── NP3-233-CD — Resource outage capacity ─────────────────────────────')
_save(gen[['ts_utc', 'total_resource_mw', 'total_irr_mw', 're_share']],
      'np3_233_outage_total')
_save(gen[['ts_utc', 'houston_resource_mw', 'houston_irr_mw', 'houston_re_share']].dropna(),
      'np3_233_outage_houston')

# ── Forecast features ──────────────────────────────────────────────────────────
print('\n── Forecast features ─────────────────────────────────────────────────')
_save(fc565_f1, 'np3_565_forecast1')
_save(wind_f1,  'np4_732_forecast1')
_save(gen_f1,   'np3_233_forecast1')

# ── Weather stations ───────────────────────────────────────────────────────────
print('\n── Weather stations ──────────────────────────────────────────────────')
_save_w(weather, 'weather_hourly')

── Combined ──────────────────────────────────────────────────────────
  ercot_combined.parquet  (18.6 MB, 74,569 rows)

── NP6-346-CD — Actual load, Houston + total ────────────────────────
  np6_346_houston.parquet  (1.2 MB, 74,521 rows)
  np6_346_total.parquet  (1.2 MB, 74,521 rows)

── NP6-345-CD — Actual load, coast + total ──────────────────────────
  np6_345_coast.parquet  (1.2 MB, 74,521 rows)
  np6_345_total.parquet  (1.2 MB, 74,521 rows)

── NP4-732-CD — Wind power ───────────────────────────────────────────
  np4_732_wind_system.parquet  (3.2 MB, 74,760 rows)
  np4_732_wind_houston.parquet  (2.6 MB, 74,760 rows)

── NP4-190-CD — DAM prices ───────────────────────────────────────────
  np4_190_dam_houston.parquet  (0.8 MB, 73,889 rows)
  np4_190_dam_avg.parquet  (1.0 MB, 73,889 rows)

── NP6-905-CD — RTM prices (hourly) ─────────────────────────────────
  np6_905_rtm_hourly_houston.parquet  (2.0 MB, 74,546 rows)
  np6_905_rtm_hourly_busavg.parquet  (2.0 MB, 74,546 rows)

── NP4-523-CD — System Lambda ────────────────────────────────────────
  np4_523_system_lambda.parquet  (1.2 MB, 74,545 rows)

── NP4-188-CD — Ancillary prices ─────────────────────────────────────
  np4_188_mcpc_ecrs.parquet  (0.7 MB, 74,545 rows)
  np4_188_mcpc_nspin.parquet  (0.8 MB, 74,545 rows)
  np4_188_mcpc_regdn.parquet  (0.8 MB, 74,545 rows)
  np4_188_mcpc_regup.parquet  (0.8 MB, 74,545 rows)
  np4_188_mcpc_rrs.parquet  (0.8 MB, 74,545 rows)

── NP3-233-CD — Resource outage capacity ─────────────────────────────
  np3_233_outage_total.parquet  (1.6 MB, 74,711 rows)
  np3_233_outage_houston.parquet  (0.5 MB, 40,470 rows)

── Forecast features ─────────────────────────────────────────────────
  np3_565_forecast1.parquet  (3.3 MB, 74,592 rows)
  np4_732_forecast1.parquet  (3.0 MB, 74,591 rows)
  np3_233_forecast1.parquet  (1.5 MB, 74,592 rows)

── Weather stations ──────────────────────────────────────────────────
  weather_hourly.parquet  (0.0 MB, 2,976 rows)